//+------------------------------------------------------------------+
//|                                                   BiotakMenu.mqh |
//|                 ماژول رابط کاربری — منوی دایره‌ای (Circular Menu) |
//|                                          Version 4.0 Circular    |
//+------------------------------------------------------------------+
#ifndef BIOTAK_MENU_MQH
#define BIOTAK_MENU_MQH

#property strict

#include "HTFCandles.mqh"

//+------------------------------------------------------------------+
//| Embedded icon resources (BMP, generated by tools/gen-icons.ps1)   |
//+------------------------------------------------------------------+
#resource "\\Files\\Icons\\zone_off.bmp"
#resource "\\Files\\Icons\\zone_on.bmp"
#resource "\\Files\\Icons\\zones_off.bmp"
#resource "\\Files\\Icons\\zones_on.bmp"
#resource "\\Files\\Icons\\ssls_off.bmp"
#resource "\\Files\\Icons\\ssls_on.bmp"
#resource "\\Files\\Icons\\chk_off.bmp"
#resource "\\Files\\Icons\\chk_on.bmp"
#resource "\\Files\\Icons\\dots_off.bmp"
#resource "\\Files\\Icons\\dots_on.bmp"
#resource "\\Files\\Icons\\tl_off.bmp"
#resource "\\Files\\Icons\\tl_on.bmp"
#resource "\\Files\\Icons\\atr_off.bmp"
#resource "\\Files\\Icons\\atr_on.bmp"
#resource "\\Files\\Icons\\box_off.bmp"
#resource "\\Files\\Icons\\box_on.bmp"
#resource "\\Files\\Icons\\htf_off.bmp"
#resource "\\Files\\Icons\\htf_on.bmp"
// TH3TOOL-OFF: custom_* icons retired with the tool:
// #resource "\\Files\\Icons\\custom_off.bmp"
// #resource "\\Files\\Icons\\custom_on.bmp"
#resource "\\Files\\Icons\\pin_off.bmp"
#resource "\\Files\\Icons\\pin_on.bmp"
#resource "\\Files\\Icons\\tools_off.bmp"
#resource "\\Files\\Icons\\tools_on.bmp"
#resource "\\Files\\Icons\\badge.bmp"
#resource "\\Files\\Icons\\orb_bg.bmp"
#resource "\\Files\\Icons\\circ_off.bmp"
#resource "\\Files\\Icons\\circ_on.bmp"
#resource "\\Files\\Icons\\step_off.bmp"
#resource "\\Files\\Icons\\step_on.bmp"
#resource "\\Files\\Icons\\factor_off.bmp"
#resource "\\Files\\Icons\\factor_on.bmp"
#resource "\\Files\\Icons\\knob.bmp"

//+------------------------------------------------------------------+
//| Circular menu geometry                                           |
//+------------------------------------------------------------------+
#define CIRC_BTN_SIZE    44
#define CIRC_ICON_SIZE   28
#define CIRC_BG_SIZE     52    // circular glass skin: 44px diameter + 4px glow margin
#define CIRC_BG_MARGIN   4
#define CIRC_ICON_OFFSET ((CIRC_BTN_SIZE - CIRC_ICON_SIZE) / 2)
#define CIRC_ORB_SIZE    64
#define CIRC_ORB_RADIUS  (CIRC_ORB_SIZE / 2)
#define CIRC_ORB_BG_SIZE 72    // scaled orb canvas: 64px orb + 4px glow margin
#define CIRC_ORB_BG_MARGIN 4
#define CIRC_BADGE_SIZE  16
#define CIRC_BADGE_FLOAT 12   // badge float gap outside the item skin edge
#define CIRC_ITEM_REACH  (CIRC_BTN_SIZE / 2 + CIRC_BADGE_FLOAT + CIRC_BADGE_SIZE / 2)  // outermost badge pixel from item center
#define CIRC_RADIUS      64
#define CIRC_GAP         6
#define CIRC_RAIL        90
#define CIRC_PAD         10
#define CIRC_HIDE_POS   -500
#define CIRC_EDGE_TRIGGER 90
#define CIRC_MIN_RADIUS  40
#define ORB_DRAG_THRESHOLD 3  // px of movement before a press counts as a drag

//--- feature indices (panel + state keys — stable, never reorder)
//    Slot 0/1 = ZONES & LEVELS — the PRIMARY feature of this indicator.
//    (The old separate Lines-Visibility toggle is gone: its master switch
//    is row 0 of the Zones & Levels card, and hotkey L still toggles it.)
#define CIR_ZONES           1   // Zones & Levels — main card (levels + mid zones)
#define CIR_TRIGGER         0   // Trigger Zones (overlay; unified lines live on card 7)
#define CIR_ATR             2   // ATR Labels (g_atrLabelsVisible)
#define CIR_TH              3   // TH Labels (g_thLabelsVisible)
#define CIR_VLOCK           4   // View Lock (g_viewLockEnabled; old TF-lock is keyboard-only now)
// TH3TOOL-OFF: CIR_TH3 slot retired (was 5, TH3 Tool / Freq)
// #define CIR_TH3             5   // TH3 Tool / Freq
#define CIR_HTF             6   // HTF Candles
#define CIR_TOOLS           7   // Tools sub-menu

// Tools half-circle
#define CIR_PIN             8   // Custom Price Pin
#define CIR_STEP_OVERRIDE   9   // Step Mode Override
#define CIR_FACTOR_OVERRIDE 10  // Factor Override

//--- ring layout (main circle — 7 items; Zones first = the main feature)
// TH3TOOL-OFF: RING_TH3 slot retired (was 5) — HTF/TOOLS shifted down.
#define RING_COUNT 7
#define CIRC_ITEM_COUNT RING_COUNT  // alias for legacy code
#define RING_ZONES    0
#define RING_TRIGGER  1
#define RING_ATR      2
#define RING_TH       3
#define RING_VLOCK    4
#define RING_HTF      5
#define RING_TOOLS    6

//--- Tools half-circle (sub-menu under Tools)
#define TOOL_COUNT 3
#define TOOL_PIN              0
#define TOOL_STEP_OVERRIDE    1
#define TOOL_FACTOR_OVERRIDE  2
#define TOOL_RADIUS 56   // >44 to avoid overlap with Tools button (44px diameter)
#define TOOL_SPREAD 110.0  // 3 items → 55° step
#define TOOL_GAP    6

//--- palette (glass-like dark buttons; skins carry the visuals, buttons are hit areas)
#define CLR_CIRC_BG_OFF     clrNONE
#define CLR_CIRC_BORDER_OFF clrNONE
#define CLR_CIRC_BG_ON      clrNONE
#define CLR_CIRC_BORDER_ON  clrNONE
#define CLR_CIRC_ORB_BG     clrNONE
#define CLR_CIRC_ORB_BORDER clrNONE
#define CLR_CIRC_ORB_TXT    C'255,200,60'
#define CLR_CIRC_BADGE_BG   C'255,171,0'
#define CLR_CIRC_BADGE_TXT  C'18,22,33'

// Refresh flags are owned by BiotakKit.mqh (REFRESH_NONE..REFRESH_ALL).

//+------------------------------------------------------------------+
//| UI State Management (UIState/g_UI/GetGVName live in BiotakKit) |
//+------------------------------------------------------------------+

// Tools sub-panels mapping
int RingPanel(const int ringIdx)  { return RingFeature(ringIdx); }
int ToolPanel(const int toolIdx)
{
   int feat = ToolFeature(toolIdx);
   if(feat == CIR_PIN) return 8; // PIN panel
   if(feat == CIR_STEP_OVERRIDE) return 9; // Step Mode override panel
   if(feat == CIR_FACTOR_OVERRIDE) return 10; // Factor override panel
   return -1;
}

//--- Ring / Tools mapping helpers (feature indices are stable panel keys)
int RingFeature(const int ringIdx)
{
   switch(ringIdx)
   {
      case RING_ZONES:   return CIR_ZONES;
      case RING_TRIGGER: return CIR_TRIGGER;
      case RING_ATR:     return CIR_ATR;
      case RING_TH:      return CIR_TH;
       case RING_VLOCK:   return CIR_VLOCK;
       // TH3TOOL-OFF: case RING_TH3: return CIR_TH3;
       case RING_HTF:     return CIR_HTF;
      case RING_TOOLS:   return CIR_TOOLS;
   }
   return -1;
}

int ToolFeature(const int toolIdx)
{
   if(toolIdx == TOOL_PIN)             return CIR_PIN;
   if(toolIdx == TOOL_STEP_OVERRIDE)   return CIR_STEP_OVERRIDE;
   if(toolIdx == TOOL_FACTOR_OVERRIDE) return CIR_FACTOR_OVERRIDE;
   return -1;
}

// Tools half-circle state (transient, not persisted)
static bool g_ToolsOpen = false;

//--- real-time orb drag state (CHARTEVENT_MOUSE_MOVE engine)
static bool g_OrbDragging   = false;
static bool g_OrbWasDragged = false;   // suppresses the click that fires after a drag
static bool g_OrbMovedThisEvent = false;
static int  g_OrbGrabDX = 0, g_OrbGrabDY = 0;
static int  g_OrbPressX = 0, g_OrbPressY = 0;
static uint g_OrbLastRedrawTick = 0;

//--- ring item long-press state (hold 250ms → open settings panel)
static int  g_LongPressItem   = -1;     // which item is being held (-1 = none)
static uint g_LongPressStart  = 0;      // GetTickCount when press started
static int  g_LongPressX      = 0;      // mouse X at press start
static int  g_LongPressY      = 0;      // mouse Y at press start
static bool g_LongPressFired  = false;  // true after panel opened (prevents toggle on release)
#define LONG_PRESS_TIME 250
#define LONG_PRESS_MOVE 8
#define CIRC_DRAG_REDRAW_INTERVAL 30

//--- chart lock while dragging or while a settings panel is open
static int  g_ChartLockCount        = 0;
static bool g_ScrollWasEnabled      = true;
static bool g_ContextMenuWasEnabled = true;

void CircLockChart()
{
   if(g_ChartLockCount++ == 0)
   {
      g_ScrollWasEnabled      = (ChartGetInteger(0, CHART_MOUSE_SCROLL) != 0);
      g_ContextMenuWasEnabled = (ChartGetInteger(0, CHART_CONTEXT_MENU) != 0);
      ChartSetInteger(0, CHART_MOUSE_SCROLL, false);
      ChartSetInteger(0, CHART_CONTEXT_MENU, false);
   }
}

void CircUnlockChart()
{
   if(g_ChartLockCount == 0) return;
   if(--g_ChartLockCount == 0)
   {
      ChartSetInteger(0, CHART_MOUSE_SCROLL, g_ScrollWasEnabled);
      ChartSetInteger(0, CHART_CONTEXT_MENU, g_ContextMenuWasEnabled);
   }
}

//--- drag arbitration (DRAG_* names shared with the settings panels)
enum DragEngineOwner
{
   DRAG_NONE        = 0,
   DRAG_MENU        = 1,   // orb move / ring-item long-press
   DRAG_PANEL_KNOB  = 3,   // settings-panel slider knob
   DRAG_PANEL_MOVE  = 5    // settings-panel drag-to-move (header grab)
};
static DragEngineOwner g_DragOwner = DRAG_NONE;

bool DragCanGrab(const DragEngineOwner who)
{
   return (g_DragOwner == DRAG_NONE || g_DragOwner == who);
}

void DragClaim(const DragEngineOwner who)
{
   g_DragOwner = who;
}

void DragReleaseIf(const DragEngineOwner who)
{
   if(g_DragOwner == who) g_DragOwner = DRAG_NONE;
}

static bool g_MouseWasDown = false;

bool MousePressStart(const bool leftDown)
{
   const bool pressStart = (leftDown && !g_MouseWasDown);
   g_MouseWasDown = leftDown;
   return pressStart;
}

static uint g_UIClickSuppressUntil = 0;
void UISuppressNextClick() { g_UIClickSuppressUntil = GetTickCount() + 350; }
bool UIShouldSuppressClick() { return (GetTickCount() < g_UIClickSuppressUntil); }

//+------------------------------------------------------------------+
//| Ring item under the cursor (-1 = none).                          |
//+------------------------------------------------------------------+
int CircItemAt(const int mx, const int my)
{
   for(int i = 0; i < RING_COUNT; i++)
   {
      int ix, iy;
      CircLayout(i, ix, iy);
      int bx = ix - CIRC_BTN_SIZE / 2;
      int by = iy - CIRC_BTN_SIZE / 2;
      if(mx >= bx - CIRC_BG_MARGIN && mx <= bx + CIRC_BTN_SIZE + CIRC_BG_MARGIN &&
         my >= by - CIRC_BG_MARGIN && my <= by + CIRC_BTN_SIZE + CIRC_BG_MARGIN)
         return i;
   }
   return -1;
}

//+------------------------------------------------------------------+
//| Point over ANY menu control (orb or ring item)?                   |
//+------------------------------------------------------------------+
bool CircPointOnMenu(const int mx, const int my)
{
   int ox = g_UI.menuX - CIRC_ORB_SIZE/2 - CIRC_ORB_BG_MARGIN;
   int oy = g_UI.menuY - CIRC_ORB_SIZE/2 - CIRC_ORB_BG_MARGIN;
   int os = CIRC_ORB_SIZE + 2*CIRC_ORB_BG_MARGIN;
   if(mx >= ox && mx <= ox + os && my >= oy && my <= oy + os) return true;
   if(CircItemAt(mx, my) >= 0) return true;
   if(ToolsItemAt(mx, my) >= 0) return true;
   return false;
}

//+------------------------------------------------------------------+
//| Circular menu object names                                       |
//+------------------------------------------------------------------+
string CircOrbBg()        { return g_UI.btnPrefix + "CircOrbBg"; }
string CircOrbIcon()      { return g_UI.btnPrefix + "CircOrbIcon"; }
string CircBtn(const int i)      { return g_UI.btnPrefix + "CircBtn" + IntegerToString(i); }
string CircIcon(const int i)     { return g_UI.btnPrefix + "CircIcon" + IntegerToString(i); }
string CircBg(const int i)        { return g_UI.btnPrefix + "CircBg" + IntegerToString(i); }
string CircBadgeBg(const int i)  { return g_UI.btnPrefix + "CircBadge" + IntegerToString(i); }
string CircBadgeTxt(const int i) { return g_UI.btnPrefix + "CircBadgeTxt" + IntegerToString(i); }

#define UI_STATE_VERSION 11

void ResetUIToDefaults()
{
   g_UI.menuVisible = true;
   g_UI.menuX = 100;
   g_UI.menuY = 200;
   g_UI.showHTF = false;
}

void LoadUIState()
{
   string gvMen   = GetGVName("MEN");
   string gvMenuX = GetGVName("MENUX");
   string gvMenuY = GetGVName("MENUY");
   string gvHtf   = GetGVName("HTF_EN");

   g_UI.menuVisible = GlobalVariableCheck(gvMen)   ? (GlobalVariableGet(gvMen)   > 0.5) : true;
   g_UI.menuX       = GlobalVariableCheck(gvMenuX) ? (int)GlobalVariableGet(gvMenuX)     : 100;
   g_UI.menuY       = GlobalVariableCheck(gvMenuY) ? (int)GlobalVariableGet(gvMenuY)     : 200;
   g_UI.showHTF     = GlobalVariableCheck(gvHtf)   ? (GlobalVariableGet(gvHtf)   > 0.5) : false;
}

void DeleteLegacyMenuObjects()
{
   string legacy = "BiotakMenu_" + IntegerToString(ChartID()) + "_";
   for(int i = 0; i < RING_COUNT; i++)
   {
      ObjectDelete(0, legacy + "CircIcon" + IntegerToString(i));
      ObjectDelete(0, legacy + "CircBg" + IntegerToString(i));
      ObjectDelete(0, legacy + "CircBadge" + IntegerToString(i));
      ObjectDelete(0, legacy + "CircBadgeTxt" + IntegerToString(i));
   }
   for(int t = 0; t < TOOL_COUNT; t++)
   {
      ObjectDelete(0, legacy + "ToolsBg" + IntegerToString(t));
      ObjectDelete(0, legacy + "ToolsIcon" + IntegerToString(t));
      ObjectDelete(0, legacy + "ToolsBadge" + IntegerToString(t));
      ObjectDelete(0, legacy + "ToolsBadgeTxt" + IntegerToString(t));
   }
   ObjectDelete(0, legacy + "CircOrbBg");
   ObjectDelete(0, legacy + "CircOrbIcon");
}

void InitializeUIStates()
{
   DeleteLegacyMenuObjects();
   g_UI.btnPrefix = "BiotakMenuV2_" + IntegerToString(ChartID()) + "_";
   g_UI.gvPrefix = "BIOMENU_" + _Symbol + "_" + IntegerToString(ChartID()) + "_";
   RuntimeSettingsSetPersistPrefix(g_UI.gvPrefix);   // OV_ overrides saved under this prefix

   bool versionOk = false;
   if(GlobalVariableCheck(GetGVName("VER")))
   {
      double ver = GlobalVariableGet(GetGVName("VER"));
      versionOk = ((int)ver == UI_STATE_VERSION);
   }

   if(versionOk && GlobalVariableCheck(GetGVName("INIT")))
   {
      LoadUIState();
   }
   else
   {
      ClearAllGVs();
      ResetUIToDefaults();
      SaveUIStates(true);
   }
}

void ClearAllGVs()
{
   const string pfx = g_UI.gvPrefix;
   const int    len = StringLen(pfx);
   if(len == 0) return;   // never sweep with an unset prefix (would hit every GV)
   for(int i = GlobalVariablesTotal() - 1; i >= 0; i--)
   {
      const string name = GlobalVariableName(i);
      if(StringLen(name) >= len && StringSubstr(name, 0, len) == pfx)
         GlobalVariableDel(name);
   }
}

void SaveUIStates(const bool flushNow = false)
{
   GlobalVariableSet(GetGVName("VER"), UI_STATE_VERSION);
   GlobalVariableSet(GetGVName("INIT"), 1.0);
   GlobalVariableSet(GetGVName("MEN"), g_UI.menuVisible ? 1.0 : 0.0);
   GlobalVariableSet(GetGVName("MENUX"), g_UI.menuX);
   GlobalVariableSet(GetGVName("MENUY"), g_UI.menuY);
   GlobalVariableSet(GetGVName("HTF_EN"), g_UI.showHTF ? 1.0 : 0.0);
   if(flushNow) GlobalVariablesFlush();
}

bool CircFeatureOn(const int i)
{
   if(i == CIR_ZONES)           return g_showMidZones;
   if(i == CIR_TRIGGER)         return g_triggerLevelsEnabled;
   if(i == CIR_ATR)             return g_atrLabelsVisible;
   if(i == CIR_TH)              return g_thLabelsVisible;
   if(i == CIR_VLOCK)           return g_viewLockEnabled;
   // TH3TOOL-OFF: if(i == CIR_TH3) return g_enableTH3Tool;
   if(i == CIR_HTF)             return g_UI.showHTF;
   if(i == CIR_PIN)             return g_customPriceLineCreated;
   if(i == CIR_STEP_OVERRIDE)   return (g_stepModeOverride != -1);
   if(i == CIR_FACTOR_OVERRIDE) return (g_factorValueOverride > 0.0);
   if(i == CIR_TOOLS)           return g_ToolsOpen;
   return false;
}

bool CircHasBadge(const int i)
{
   // NOBADGES (user decision 2026-09-04): NO badges on ring buttons at all —
   // neither the "On" marker nor value texts ("Aut"/"H1"/...). Every badge
   // create/show/move/update path is gated by this function; the delete
   // paths stay to purge badges left by older versions. Settings panels
   // still open via long-press. To restore: return (i != CIR_TOOLS).
   return false;
   // return (i != CIR_TOOLS);   // every main-ring feature shows a badge; Tools opens its sub-menu
}

void CircConfigureIcon(const string name, const int i, const bool on, const int x, const int y)
{
   ObjectSetInteger(0, name, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, name, OBJPROP_XDISTANCE, x - CIRC_ICON_SIZE / 2);
   ObjectSetInteger(0, name, OBJPROP_YDISTANCE, y - CIRC_ICON_SIZE / 2);
   ObjectSetInteger(0, name, OBJPROP_XSIZE, CIRC_ICON_SIZE);
   ObjectSetInteger(0, name, OBJPROP_YSIZE, CIRC_ICON_SIZE);
   string res = CircIconRes(i, on);
   ObjectSetString(0, name, OBJPROP_BMPFILE, 0, res);
   ObjectSetString(0, name, OBJPROP_BMPFILE, 1, res);
   ObjectSetString(0, name, OBJPROP_TOOLTIP, CircItemTooltip(i));
   ObjectSetInteger(0, name, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, name, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, name, OBJPROP_BACK, false);
   ObjectSetInteger(0, name, OBJPROP_ZORDER, 1011);
}

string CircIconRes(const int i, const bool on)
{
   string base;
   if(i == CIR_ZONES)           base = "zones";   // Mid-zone band icon (the main Zones & Levels feature)
   else if(i == CIR_TRIGGER)    base = "zone";    // Trigger level-ladder icon
   else if(i == CIR_ATR)        base = "atr";     // ATR range-bracket icon
   else if(i == CIR_TH)         base = "dots";    // TH dotted-level icon
   else if(i == CIR_VLOCK)      base = "box";     // View lock (same padlock skin)
   // TH3TOOL-OFF: else if(i == CIR_TH3) base = "custom";  // TH3 tool/gauge icon
   else if(i == CIR_HTF)        base = "htf";     // HTF candle icon
   else if(i == CIR_PIN)        base = "pin";     // Pin icon
   else if(i == CIR_STEP_OVERRIDE)   base = "step";    // Step mode override icon
   else if(i == CIR_FACTOR_OVERRIDE) base = "factor";  // Factor slider icon
   else if(i == CIR_TOOLS)      base = "tools";
   else                         base = "htf";
   return "::Files\\Icons\\" + base + (on ? "_on.bmp" : "_off.bmp");
}

//+------------------------------------------------------------------+
//| CARD HEADER ICON — one glyph PER SETTINGS CARD, chosen for the   |
//| content of that card (not the ring toggle that opened it).       |
//|  0 Trigger Zones = zone ladder · 1 Zones & Levels = band ·       |
//|  2 ATR = range bracket · 3 TH = dotted wave · 4 View lock = padlock · |
//|  5 retired (was TH3) · 6 HTF = candles · 7 Lines = line ·        |
//|  8 CustomPrice = pin · 9 StepMode = stairs · 10 Factor = gauge · |
//|  11 Structure = stair levels                                     |
//+------------------------------------------------------------------+
string CircCardIcon(const int item, const bool on)
{
   string base = "htf";
   if(item == 1)          base = "zones";   // Zones & Levels — MAIN card
   else if(item == 0)     base = "zone";    // Trigger zones overlay
   else if(item == 2)     base = "atr";     // ATR labels (range bracket)
   else if(item == 3)     base = "dots";    // TH labels
   else if(item == 4)     base = "box";     // View lock
   // TH3TOOL-OFF: else if(item == 5) base = "custom";  // TH3 tool
   else if(item == 6)     base = "htf";     // HTF candles
   else if(item == 7)     base = "tl";      // Lines (shares the line glyph with ATR)
   else if(item == 8)     base = "pin";     // Custom price pin
   else if(item == 9)     base = "step";    // Step mode
   else if(item == 10)    base = "factor";  // Factor step
   else if(item == 11)    base = "step";    // Structure levels (stair levels)
   return "::Files\\Icons\\" + base + (on ? "_on.bmp" : "_off.bmp");
}

string CircTimeframeLabel(const ENUM_TIMEFRAMES tf)
{
   switch(tf)
   {
      case PERIOD_M1:  return "M1";
      case PERIOD_M5:  return "M5";
      case PERIOD_M15: return "M15";
      case PERIOD_M30: return "M30";
      case PERIOD_H1:  return "H1";
      case PERIOD_H4:  return "H4";
      case PERIOD_D1:  return "D1";
      case PERIOD_W1:  return "W1";
      case PERIOD_MN1: return "MN1";
   }
   return "";
}

string CircBadgeText(const int i)
{
   if(i == CIR_ZONES)           return g_showMidZones ? "On" : "";
   if(i == CIR_TRIGGER)         return IntegerToString(inpMaxLevels);
   if(i == CIR_ATR)             return g_atrLabelsVisible ? "On" : "";
   if(i == CIR_TH)
   {
      if(g_thLabelsMode == 1) return "Fr";
      if(g_thLabelsMode == 2) return "St";
      if(g_thLabelsMode == 3) return "Bt";
      return "";
   }
   if(i == CIR_VLOCK)
   {
      if(g_viewLockEnabled) return "On";
      return "";
   }
   // TH3TOOL-OFF:
   //if(i == CIR_TH3)
   //{
   //   if(g_th3FreqOverride > 0) return DoubleToString(g_th3FreqOverride, 1) + "x";
   //   return "Aut";
   //}
   if(i == CIR_HTF)     return CircHtfBadgeLabel(g_HTFPeriod);
   if(i == CIR_PIN)
   {
      if(g_customTHStartPrice > 0) return DoubleToString(g_customTHStartPrice, 1);
      return "Off";
   }
   if(i == CIR_STEP_OVERRIDE)
   {
      if(g_stepModeOverride == 0) return "Tr";
      if(g_stepModeOverride == 1) return "Sub";
      if(g_stepModeOverride == 2) return "Pat";
      if(g_stepModeOverride == 3) return "Trd";
      return "Aut";
   }
   if(i == CIR_FACTOR_OVERRIDE)
   {
      if(g_factorValueOverride > 0) return DoubleToString(g_factorValueOverride, 0);
      return "Aut";
   }
   return "";
}

string CircHtfBadgeLabel(const int periodMinutes)
{
   if(periodMinutes <= 0) return "";
   if(periodMinutes >= 1440) return IntegerToString(periodMinutes / 1440) + "D";
   if(periodMinutes >= 60)   return IntegerToString(periodMinutes / 60) + "H";
   return IntegerToString(periodMinutes) + "M";
}

string CircItemTooltip(const int i)
{
   switch(i)
   {
      case CIR_ZONES:           return "Zones & Levels\nClick: toggle mid zones · Hold: full settings";
      case CIR_TRIGGER:         return "Trigger Zones\nClick: toggle trigger zones · Hold: settings";
      case CIR_ATR:             return "ATR Labels\nClick: toggle ATR labels · Hold: settings";
      case CIR_TH:              return "TH Labels Mode\nClick: cycle TH labels mode · Hold: settings";
       case CIR_VLOCK:           return "View Lock\nClick: keep this view across timeframes · Hold: settings";
       // TH3TOOL-OFF: case CIR_TH3: return "TH3 Pattern Frequency\nClick: toggle TH3 · Hold: settings";
       case CIR_HTF:             return "Higher Timeframe Candles\nClick: toggle HTF candles · Hold: settings";
      case CIR_PIN:             return "Custom Price Pin\nClick: activate pin placement · Drag line: adjust · ESC: clear";
      case CIR_STEP_OVERRIDE:   return "Step Mode Override\nClick: cycle override · Hold: settings";
      case CIR_FACTOR_OVERRIDE: return "Factor Value Override\nClick: cycle override · Hold: settings";
      case CIR_TOOLS:           return "Biotak Tools\nClick: open tools menu";
   }
   return "";
}

double CircFitRadius(const int cw, const int ch, const int ox, const int oy)
{
   double r = CIRC_RADIUS;
   for(int i = 0; i < RING_COUNT; i++)
   {
      double deg = (-90.0 + 360.0 * i / RING_COUNT) * M_PI / 180.0;
      double c = MathCos(deg);
      double s = MathSin(deg);
      double lim = 1e18;
      if(c > 1e-6)        lim = MathMin(lim, (cw - CIRC_PAD - ox - CIRC_ITEM_REACH) / c);
      else if(c < -1e-6)  lim = MathMin(lim, (ox - CIRC_PAD - CIRC_ITEM_REACH) / (-c));
      if(s > 1e-6)        lim = MathMin(lim, (ch - CIRC_PAD - oy - CIRC_ITEM_REACH) / s);
      else if(s < -1e-6)  lim = MathMin(lim, (oy - CIRC_PAD - CIRC_ITEM_REACH) / (-s));
      if(lim < 1e17) r = MathMin(r, lim);
   }
   if(r < CIRC_MIN_RADIUS) r = CIRC_MIN_RADIUS;
   if(r > CIRC_RADIUS) r = CIRC_RADIUS;
   return r;
}

void CircLayout(const int i, int &x, int &y)
{
   int cw = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS, 0);
   int ch = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS, 0);
   if(cw <= 0) cw = 1920;
   if(ch <= 0) ch = 1080;
   int ox = g_UI.menuX;
   int oy = g_UI.menuY;

   bool nearLeft   = (ox <= CIRC_EDGE_TRIGGER);
   bool nearRight  = (ox >= cw - CIRC_EDGE_TRIGGER);
   bool nearTop    = (oy <= CIRC_EDGE_TRIGGER);
   bool nearBottom = (oy >= ch - CIRC_EDGE_TRIGGER);

   if(nearLeft || nearRight || nearTop || nearBottom)
   {
      int step = CIRC_BTN_SIZE + CIRC_GAP;
      int trainLen = CIRC_ORB_SIZE / 2 + CIRC_BTN_SIZE / 2 + CIRC_GAP + (RING_COUNT - 1) * step;
      if(nearLeft || nearRight)
      {
         x = ox;
         int upRoom   = oy - CIRC_PAD - CIRC_BTN_SIZE / 2;
         int downRoom = ch - CIRC_PAD - oy - CIRC_BTN_SIZE / 2;
         int dir = (upRoom >= downRoom) ? -1 : 1;
         if(dir == -1 && upRoom < trainLen && downRoom >= trainLen) dir = 1;
         else if(dir == 1 && downRoom < trainLen && upRoom >= trainLen) dir = -1;
         y = oy + dir * (CIRC_ORB_SIZE / 2 + CIRC_BTN_SIZE / 2 + CIRC_GAP + i * step);
      }
      else
      {
         y = oy;
         int leftRoom  = ox - CIRC_PAD - CIRC_BTN_SIZE / 2;
         int rightRoom = cw - CIRC_PAD - ox - CIRC_BTN_SIZE / 2;
         int dir = (leftRoom >= rightRoom) ? -1 : 1;
         if(dir == -1 && leftRoom < trainLen && rightRoom >= trainLen) dir = 1;
         else if(dir == 1 && rightRoom < trainLen && leftRoom >= trainLen) dir = -1;
         x = ox + dir * (CIRC_ORB_SIZE / 2 + CIRC_BTN_SIZE / 2 + CIRC_GAP + i * step);
      }
   }
   else
   {
      double r = CircFitRadius(cw, ch, ox, oy);
      double deg = (-90.0 + 360.0 * i / RING_COUNT) * M_PI / 180.0;
      x = ox + (int)MathRound(r * MathCos(deg));
      y = oy + (int)MathRound(r * MathSin(deg));
   }
}

void ToolsLayout(const int toolIdx, int &x, int &y)
{
   int ax, ay;
   CircLayout(RING_TOOLS, ax, ay);
   int cw = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS, 0);
   int ch = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS, 0);
   if(cw <= 0) cw = 1920;
   if(ch <= 0) ch = 1080;
   bool nearLeft   = (g_UI.menuX <= CIRC_EDGE_TRIGGER);
   bool nearRight  = (g_UI.menuX >= cw - CIRC_EDGE_TRIGGER);
   bool nearTop    = (g_UI.menuY <= CIRC_EDGE_TRIGGER);
   bool nearBottom = (g_UI.menuY >= ch - CIRC_EDGE_TRIGGER);
   bool isRail = (nearLeft || nearRight || nearTop || nearBottom);
   double baseDeg;
   if(isRail)
   {
      if(nearLeft)       baseDeg = 0.0;    // east
      else if(nearRight) baseDeg = 180.0;  // west
      else if(nearTop)   baseDeg = 90.0;   // south
      else               baseDeg = 270.0;  // north
   }
   else
   {
      baseDeg = -90.0 + 360.0 * RING_TOOLS / RING_COUNT;
   }
   double spread = TOOL_SPREAD;
   double step = (TOOL_COUNT > 1) ? spread / (TOOL_COUNT - 1) : 0;
   double start = baseDeg - spread / 2.0;
   double deg = (start + toolIdx * step) * M_PI / 180.0;
   x = ax + (int)MathRound(TOOL_RADIUS * MathCos(deg));
   y = ay + (int)MathRound(TOOL_RADIUS * MathSin(deg));
   int minX = CIRC_PAD + CIRC_BTN_SIZE/2 + CIRC_BG_MARGIN;
   int maxX = cw - CIRC_PAD - CIRC_BTN_SIZE/2 - CIRC_BG_MARGIN;
   int minY = CIRC_PAD + CIRC_BTN_SIZE/2 + CIRC_BG_MARGIN;
   int maxY = ch - CIRC_PAD - CIRC_BTN_SIZE/2 - CIRC_BG_MARGIN;
   if(x < minX) x = minX;
   if(x > maxX) x = maxX;
   if(y < minY) y = minY;
   if(y > maxY) y = maxY;
}

int ToolsItemAt(const int mx, const int my)
{
   if(!g_ToolsOpen || !g_UI.menuVisible) return -1;
   for(int i = 0; i < TOOL_COUNT; i++)
   {
      int ix, iy;
      ToolsLayout(i, ix, iy);
      int bx = ix - CIRC_BTN_SIZE/2;
      int by = iy - CIRC_BTN_SIZE/2;
      if(mx >= bx - CIRC_BG_MARGIN && mx <= bx + CIRC_BTN_SIZE + CIRC_BG_MARGIN &&
         my >= by - CIRC_BG_MARGIN && my <= by + CIRC_BTN_SIZE + CIRC_BG_MARGIN)
         return i;
   }
   return -1;
}

string ToolsBg(const int i)   { return g_UI.btnPrefix + "ToolsBg" + IntegerToString(i); }
string ToolsIcon(const int i) { return g_UI.btnPrefix + "ToolsIcon" + IntegerToString(i); }
string ToolsBadgeBg(const int i) { return g_UI.btnPrefix + "ToolsBadge" + IntegerToString(i); }
string ToolsBadgeTxt(const int i) { return g_UI.btnPrefix + "ToolsBadgeTxt" + IntegerToString(i); }

// Badge anchor for a Tools item: pushed outward from the menu center
void ToolsBadgePos(const int i, int &x, int &y)
{
   int cx, cy;
   ToolsLayout(i, cx, cy);
   int cw = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS, 0);
   int ch = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS, 0);
   if(cw <= 0) cw = 1920;
   if(ch <= 0) ch = 1080;
   double dx = cx - g_UI.menuX;
   double dy = cy - g_UI.menuY;
   if(g_UI.menuX <= CIRC_EDGE_TRIGGER)      { dx = 1;  dy = 0;  }
   else if(g_UI.menuX >= cw - CIRC_EDGE_TRIGGER) { dx = -1; dy = 0;  }
   else if(g_UI.menuY <= CIRC_EDGE_TRIGGER) { dx = 0;  dy = 1;  }
   else if(g_UI.menuY >= ch - CIRC_EDGE_TRIGGER) { dx = 0;  dy = -1; }
   else
   {
      double len = MathSqrt(dx * dx + dy * dy);
      if(len > 0.1) { dx /= len; dy /= len; } else { dx = 0; dy = 1; }
   }
   double off = CIRC_BTN_SIZE / 2 + CIRC_BADGE_FLOAT;
   x = (int)MathRound(cx + dx * off - CIRC_BADGE_SIZE / 2.0);
   y = (int)MathRound(cy + dy * off - CIRC_BADGE_SIZE / 2.0);
}

void ToolsCreateBadge(const int i)
{
   int badgeX, badgeY;
   ToolsBadgePos(i, badgeX, badgeY);
   int feat = ToolFeature(i);

   string bg = ToolsBadgeBg(i);
   if(ObjectFind(0, bg) < 0)
   {
      if(!ObjectCreate(0, bg, OBJ_BITMAP_LABEL, 0, 0, 0)) return;
   }
   ObjectSetInteger(0, bg, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, bg, OBJPROP_XDISTANCE, badgeX);
   ObjectSetInteger(0, bg, OBJPROP_YDISTANCE, badgeY);
   ObjectSetInteger(0, bg, OBJPROP_XSIZE, CIRC_BADGE_SIZE);
   ObjectSetInteger(0, bg, OBJPROP_YSIZE, CIRC_BADGE_SIZE);
   ObjectSetInteger(0, bg, OBJPROP_BGCOLOR, CLR_CIRC_BADGE_BG);
   ObjectSetString(0, bg, OBJPROP_BMPFILE, 0, "::Files\\Icons\\badge.bmp");
   ObjectSetString(0, bg, OBJPROP_BMPFILE, 1, "::Files\\Icons\\badge.bmp");
   ObjectSetString(0, bg, OBJPROP_TOOLTIP, CircBadgeTooltip(feat));
   ObjectSetInteger(0, bg, OBJPROP_STATE, false);
   ObjectSetInteger(0, bg, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, bg, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, bg, OBJPROP_ZORDER, 1012);

   string txt = ToolsBadgeTxt(i);
   if(ObjectFind(0, txt) < 0)
   {
      if(!ObjectCreate(0, txt, OBJ_LABEL, 0, 0, 0)) return;
   }
   ObjectSetInteger(0, txt, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, txt, OBJPROP_ANCHOR, ANCHOR_CENTER);
   ObjectSetInteger(0, txt, OBJPROP_XDISTANCE, badgeX + CIRC_BADGE_SIZE / 2);
   ObjectSetInteger(0, txt, OBJPROP_YDISTANCE, badgeY + CIRC_BADGE_SIZE / 2);
   ObjectSetString(0, txt, OBJPROP_TEXT, CircBadgeText(feat));
   ObjectSetInteger(0, txt, OBJPROP_COLOR, CLR_CIRC_BADGE_TXT);
   ObjectSetInteger(0, txt, OBJPROP_FONTSIZE, 7);
   ObjectSetString(0, txt, OBJPROP_FONT, "Arial Bold");
   ObjectSetString(0, txt, OBJPROP_TOOLTIP, CircBadgeTooltip(feat));
   ObjectSetInteger(0, txt, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, txt, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, txt, OBJPROP_ZORDER, 1013);
}

void CircBadgeDir(const int i, double &dx, double &dy)
{
   int cw = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS, 0);
   int ch = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS, 0);
   if(cw <= 0) cw = 1920;
   if(ch <= 0) ch = 1080;
   int cx, cy;
   CircLayout(i, cx, cy);
   dx = cx - g_UI.menuX;
   dy = cy - g_UI.menuY;
   if(g_UI.menuX <= CIRC_EDGE_TRIGGER)           { dx = 1;  dy = 0;  return; }
   if(g_UI.menuX >= cw - CIRC_EDGE_TRIGGER)      { dx = -1; dy = 0;  return; }
   if(g_UI.menuY <= CIRC_EDGE_TRIGGER)           { dx = 0;  dy = 1;  return; }
   if(g_UI.menuY >= ch - CIRC_EDGE_TRIGGER)      { dx = 0;  dy = -1; return; }
   double len = MathSqrt(dx * dx + dy * dy);
   if(len > 0.1) { dx /= len; dy /= len; } else { dx = 0; dy = -1; }
}

void CircBadgePos(const int i, int &x, int &y)
{
   int cx, cy;
   CircLayout(i, cx, cy);
   double dx, dy;
   CircBadgeDir(i, dx, dy);
   double off = CIRC_BTN_SIZE / 2 + CIRC_BADGE_FLOAT;
   x = (int)MathRound(cx + dx * off - CIRC_BADGE_SIZE / 2.0);
   y = (int)MathRound(cy + dy * off - CIRC_BADGE_SIZE / 2.0);
}

string CircBadgeTooltip(const int i)
{
   string t = CircItemTooltip(i);
   int nl = StringFind(t, "\n");
   string name = (nl > 0) ? StringSubstr(t, 0, nl) : t;
   string val = CircBadgeText(i);
   if(StringLen(val) > 0) return name + " = " + val + "\nClick: settings";
   return name + "\nClick: settings";
}

void CircCreateBadge(const int i)
{
   int size = CIRC_BADGE_SIZE;
   int badgeX, badgeY;
   CircBadgePos(i, badgeX, badgeY);
   int feat = RingFeature(i);

   string bg = CircBadgeBg(i);
   if(ObjectFind(0, bg) < 0)
   {
      if(!ObjectCreate(0, bg, OBJ_BITMAP_LABEL, 0, 0, 0)) return;
   }
   ObjectSetInteger(0, bg, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, bg, OBJPROP_XDISTANCE, badgeX);
   ObjectSetInteger(0, bg, OBJPROP_YDISTANCE, badgeY);
   ObjectSetInteger(0, bg, OBJPROP_XSIZE, size);
   ObjectSetInteger(0, bg, OBJPROP_YSIZE, size);
   ObjectSetInteger(0, bg, OBJPROP_BGCOLOR, CLR_CIRC_BADGE_BG);
   ObjectSetString(0, bg, OBJPROP_BMPFILE, 0, "::Files\\Icons\\badge.bmp");
   ObjectSetString(0, bg, OBJPROP_BMPFILE, 1, "::Files\\Icons\\badge.bmp");
   ObjectSetString(0, bg, OBJPROP_TOOLTIP, CircBadgeTooltip(feat));
   ObjectSetInteger(0, bg, OBJPROP_STATE, false);
   ObjectSetInteger(0, bg, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, bg, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, bg, OBJPROP_ZORDER, 1012);

   // Badge text label (value shown inside the amber badge)
   string txt = CircBadgeTxt(i);
   if(ObjectFind(0, txt) < 0)
   {
      if(!ObjectCreate(0, txt, OBJ_LABEL, 0, 0, 0)) return;
   }
   ObjectSetInteger(0, txt, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, txt, OBJPROP_ANCHOR, ANCHOR_CENTER);
   ObjectSetInteger(0, txt, OBJPROP_XDISTANCE, badgeX + size / 2);
   ObjectSetInteger(0, txt, OBJPROP_YDISTANCE, badgeY + size / 2);
   ObjectSetString(0, txt, OBJPROP_TEXT, CircBadgeText(feat));
   ObjectSetInteger(0, txt, OBJPROP_COLOR, CLR_CIRC_BADGE_TXT);
   ObjectSetInteger(0, txt, OBJPROP_FONTSIZE, 7);
   ObjectSetString(0, txt, OBJPROP_FONT, "Arial Bold");
   ObjectSetString(0, txt, OBJPROP_TOOLTIP, CircBadgeTooltip(feat));
   ObjectSetInteger(0, txt, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, txt, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, txt, OBJPROP_ZORDER, 1013);
}

void CircCreateItem(const int i)
{
   int x, y;
   CircLayout(i, x, y);
   int bx = x - CIRC_BTN_SIZE / 2;
   int by = y - CIRC_BTN_SIZE / 2;
   int feat = RingFeature(i);
   bool on = CircFeatureOn(feat);

   string bg = CircBg(i);
   if(ObjectFind(0, bg) < 0)
   {
      if(!ObjectCreate(0, bg, OBJ_BITMAP_LABEL, 0, 0, 0)) return;
   }
   string bgRes = on ? "::Files\\Icons\\circ_on.bmp" : "::Files\\Icons\\circ_off.bmp";
   ObjectSetInteger(0, bg, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, bg, OBJPROP_XDISTANCE, bx - CIRC_BG_MARGIN);
   ObjectSetInteger(0, bg, OBJPROP_YDISTANCE, by - CIRC_BG_MARGIN);
   ObjectSetInteger(0, bg, OBJPROP_XSIZE, CIRC_BG_SIZE);
   ObjectSetInteger(0, bg, OBJPROP_YSIZE, CIRC_BG_SIZE);
   ObjectSetString(0, bg, OBJPROP_BMPFILE, 0, bgRes);
   ObjectSetString(0, bg, OBJPROP_BMPFILE, 1, bgRes);
   ObjectSetString(0, bg, OBJPROP_TOOLTIP, CircItemTooltip(feat));
   ObjectSetInteger(0, bg, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, bg, OBJPROP_SELECTED, false);
   ObjectSetInteger(0, bg, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, bg, OBJPROP_BACK, false);
   ObjectSetInteger(0, bg, OBJPROP_ZORDER, 1010);

   string icon = CircIcon(i);
   if(ObjectFind(0, icon) >= 0)
      ObjectDelete(0, icon);
   if(!ObjectCreate(0, icon, OBJ_BITMAP_LABEL, 0, 0, 0)) return;
   CircConfigureIcon(icon, feat, on,
      bx + CIRC_BTN_SIZE / 2,
      by + CIRC_BTN_SIZE / 2);

   if(CircHasBadge(feat))
   {
      CircCreateBadge(i);
      if(!on) CircShowBadge(i, false);   // feature off → keep badge hidden
   }
}

void ToolsCreateItem(const int toolIdx)
{
   int x, y;
   ToolsLayout(toolIdx, x, y);
   int bx = x - CIRC_BTN_SIZE/2;
   int by = y - CIRC_BTN_SIZE/2;
   int feat = ToolFeature(toolIdx);
   bool on = CircFeatureOn(feat);
   
   string bg = ToolsBg(toolIdx);
   if(ObjectFind(0, bg) < 0) if(!ObjectCreate(0, bg, OBJ_BITMAP_LABEL, 0, 0, 0)) return;
   string bgRes = on ? "::Files\\Icons\\circ_on.bmp" : "::Files\\Icons\\circ_off.bmp";
   ObjectSetInteger(0, bg, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, bg, OBJPROP_XDISTANCE, bx - CIRC_BG_MARGIN);
   ObjectSetInteger(0, bg, OBJPROP_YDISTANCE, by - CIRC_BG_MARGIN);
   ObjectSetInteger(0, bg, OBJPROP_XSIZE, CIRC_BG_SIZE);
   ObjectSetInteger(0, bg, OBJPROP_YSIZE, CIRC_BG_SIZE);
   ObjectSetString(0, bg, OBJPROP_BMPFILE, 0, bgRes);
   ObjectSetString(0, bg, OBJPROP_BMPFILE, 1, bgRes);
   ObjectSetString(0, bg, OBJPROP_TOOLTIP, CircItemTooltip(feat));
   ObjectSetInteger(0, bg, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, bg, OBJPROP_SELECTED, false);
   ObjectSetInteger(0, bg, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, bg, OBJPROP_BACK, false);
   ObjectSetInteger(0, bg, OBJPROP_ZORDER, 1010);
   
   string icon = ToolsIcon(toolIdx);
   if(ObjectFind(0, icon) >= 0)
      ObjectDelete(0, icon);
   if(!ObjectCreate(0, icon, OBJ_BITMAP_LABEL, 0, 0, 0)) return;
   CircConfigureIcon(icon, feat, on,
      bx + CIRC_BTN_SIZE / 2,
      by + CIRC_BTN_SIZE / 2);

   // Settings badge (click → open the item's panel). Created only when the
   // feature has a panel; hidden (off-screen) when the feature is off.
   if(CircHasBadge(feat))
   {
      ToolsCreateBadge(toolIdx);
      if(!CircFeatureOn(feat)) ToolsShowBadge(toolIdx, false);
   }
}

void ToolsShowBadge(const int i, const bool show)
{
   int x = CIRC_HIDE_POS, y = CIRC_HIDE_POS;
   if(show)
      ToolsBadgePos(i, x, y);
   int tx = (show ? x + CIRC_BADGE_SIZE / 2 : x);
   int ty = (show ? y + CIRC_BADGE_SIZE / 2 : y);
   if(ObjectFind(0, ToolsBadgeBg(i)) >= 0)
   {
      ObjectSetInteger(0, ToolsBadgeBg(i), OBJPROP_XDISTANCE, x);
      ObjectSetInteger(0, ToolsBadgeBg(i), OBJPROP_YDISTANCE, y);
   }
   if(ObjectFind(0, ToolsBadgeTxt(i)) >= 0)
   {
      ObjectSetInteger(0, ToolsBadgeTxt(i), OBJPROP_XDISTANCE, tx);
      ObjectSetInteger(0, ToolsBadgeTxt(i), OBJPROP_YDISTANCE, ty);
   }
}

void CircCreateOrb()
{
   int cw = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS, 0);
   int ch = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS, 0);
   if(cw <= 0) cw = 1920;
   if(ch <= 0) ch = 1080;
   g_UI.menuX = MathMax(CIRC_PAD + CIRC_ORB_SIZE / 2, MathMin(cw - CIRC_PAD - CIRC_ORB_SIZE / 2, g_UI.menuX));
   g_UI.menuY = MathMax(CIRC_PAD + CIRC_ORB_SIZE / 2, MathMin(ch - CIRC_PAD - CIRC_ORB_SIZE / 2, g_UI.menuY));

   int x = g_UI.menuX - CIRC_ORB_SIZE / 2;
   int y = g_UI.menuY - CIRC_ORB_SIZE / 2;

   string orbBg = CircOrbBg();
   if(ObjectFind(0, orbBg) < 0)
      ObjectCreate(0, orbBg, OBJ_BITMAP_LABEL, 0, 0, 0);
   ObjectSetInteger(0, orbBg, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, orbBg, OBJPROP_XDISTANCE, x - CIRC_ORB_BG_MARGIN);
   ObjectSetInteger(0, orbBg, OBJPROP_YDISTANCE, y - CIRC_ORB_BG_MARGIN);
   ObjectSetInteger(0, orbBg, OBJPROP_XSIZE, CIRC_ORB_BG_SIZE);
   ObjectSetInteger(0, orbBg, OBJPROP_YSIZE, CIRC_ORB_BG_SIZE);
   ObjectSetString(0, orbBg, OBJPROP_BMPFILE, 0, "::Files\\Icons\\orb_bg.bmp");
   ObjectSetString(0, orbBg, OBJPROP_BMPFILE, 1, "::Files\\Icons\\orb_bg.bmp");
   ObjectSetInteger(0, orbBg, OBJPROP_BGCOLOR, C'30,22,10');
   ObjectSetInteger(0, orbBg, OBJPROP_STATE, false);
   ObjectSetInteger(0, orbBg, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, orbBg, OBJPROP_SELECTED, false);
   ObjectSetInteger(0, orbBg, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, orbBg, OBJPROP_BACK, false);
   ObjectSetInteger(0, orbBg, OBJPROP_ZORDER, 2000);
   ObjectSetString(0, orbBg, OBJPROP_TOOLTIP, "Biotak Terminal Menu\nClick: open/close · Drag: move");

   // No center overlay: the medallion lives entirely in orb_bg.bmp (P-ICONS-04).
   // Delete the retired CircOrbIcon object on charts that still have it.
   ObjectDelete(0, CircOrbIcon());
}

void CreateMenu()
{
   CircCreateOrb();
   if(!g_UI.menuVisible) return;
   for(int i = 0; i < RING_COUNT; i++)
      CircCreateItem(i);
   if(g_ToolsOpen)
      for(int t = 0; t < TOOL_COUNT; t++) ToolsCreateItem(t);
}

void CreateToolsMenu()
{
   if(!g_UI.menuVisible) return;
   g_ToolsOpen = true;
   for(int t = 0; t < TOOL_COUNT; t++) ToolsCreateItem(t);
   CircUpdateItemState(RING_TOOLS);
   ChartRedraw();
}

void DeleteToolsMenu()
{
   for(int t = 0; t < TOOL_COUNT; t++)
   {
      ObjectDelete(0, ToolsBg(t));
      ObjectDelete(0, ToolsIcon(t));
      ObjectDelete(0, ToolsBadgeBg(t));
      ObjectDelete(0, ToolsBadgeTxt(t));
   }
   g_ToolsOpen = false;
   CircUpdateItemState(RING_TOOLS);
   ChartRedraw();
}

void DeleteMenu()
{
   for(int i = 0; i < RING_COUNT; i++)
   {
      ObjectDelete(0, CircIcon(i));
      ObjectDelete(0, CircBg(i));
      ObjectDelete(0, CircBadgeBg(i));
      ObjectDelete(0, CircBadgeTxt(i));
   }
   DeleteToolsMenu();
   ObjectDelete(0, CircOrbBg());
   ObjectDelete(0, CircOrbIcon());
}

void CircMoveItem(const int i)
{
   int x, y;
   CircLayout(i, x, y);
   int bx = x - CIRC_BTN_SIZE / 2;
   int by = y - CIRC_BTN_SIZE / 2;
   if(ObjectFind(0, CircIcon(i)) >= 0)
   {
      ObjectSetInteger(0, CircIcon(i), OBJPROP_XDISTANCE, x - CIRC_ICON_SIZE / 2);
      ObjectSetInteger(0, CircIcon(i), OBJPROP_YDISTANCE, y - CIRC_ICON_SIZE / 2);
   }
   if(ObjectFind(0, CircBg(i)) >= 0)
   {
      ObjectSetInteger(0, CircBg(i), OBJPROP_XDISTANCE, bx - CIRC_BG_MARGIN);
      ObjectSetInteger(0, CircBg(i), OBJPROP_YDISTANCE, by - CIRC_BG_MARGIN);
   }
   int feat = RingFeature(i);
   if(CircHasBadge(feat)) CircMoveBadge(i);
}

void CircMoveBadge(const int i)
{
   int feat = RingFeature(i);
   if(!CircFeatureOn(feat))
   {
      CircShowBadge(i, false);
      return;
   }
   int x, y;
   CircBadgePos(i, x, y);
   if(ObjectFind(0, CircBadgeBg(i)) >= 0)
   {
      ObjectSetInteger(0, CircBadgeBg(i), OBJPROP_XDISTANCE, x);
      ObjectSetInteger(0, CircBadgeBg(i), OBJPROP_YDISTANCE, y);
   }
   if(ObjectFind(0, CircBadgeTxt(i)) >= 0)
   {
      ObjectSetInteger(0, CircBadgeTxt(i), OBJPROP_XDISTANCE, x + CIRC_BADGE_SIZE / 2);
      ObjectSetInteger(0, CircBadgeTxt(i), OBJPROP_YDISTANCE, y + CIRC_BADGE_SIZE / 2);
   }
}

void ToolsMoveItem(const int t)
{
   int x, y;
   ToolsLayout(t, x, y);
   int bx = x - CIRC_BTN_SIZE/2;
   int by = y - CIRC_BTN_SIZE/2;
   if(ObjectFind(0, ToolsBg(t)) >= 0)
   {
      ObjectSetInteger(0, ToolsBg(t), OBJPROP_XDISTANCE, bx - CIRC_BG_MARGIN);
      ObjectSetInteger(0, ToolsBg(t), OBJPROP_YDISTANCE, by - CIRC_BG_MARGIN);
   }
   if(ObjectFind(0, ToolsIcon(t)) >= 0)
   {
      ObjectSetInteger(0, ToolsIcon(t), OBJPROP_XDISTANCE, x - CIRC_ICON_SIZE / 2);
      ObjectSetInteger(0, ToolsIcon(t), OBJPROP_YDISTANCE, y - CIRC_ICON_SIZE / 2);
   }
   // Badge follows the item while dragging the orb
   int featT = ToolFeature(t);
   if(CircHasBadge(featT) && ObjectFind(0, ToolsBadgeBg(t)) >= 0)
      ToolsShowBadge(t, CircFeatureOn(featT));
}

void CircApplyMenuPosition()
{
   int orbX = g_UI.menuX - CIRC_ORB_SIZE / 2;
   int orbY = g_UI.menuY - CIRC_ORB_SIZE / 2;
   if(ObjectFind(0, CircOrbBg()) >= 0)
   {
      ObjectSetInteger(0, CircOrbBg(), OBJPROP_XDISTANCE, orbX - CIRC_ORB_BG_MARGIN);
      ObjectSetInteger(0, CircOrbBg(), OBJPROP_YDISTANCE, orbY - CIRC_ORB_BG_MARGIN);
   }

   if(g_UI.menuVisible)
   {
      for(int i = 0; i < RING_COUNT; i++)
         CircMoveItem(i);
      if(g_ToolsOpen)
         for(int t = 0; t < TOOL_COUNT; t++) ToolsMoveItem(t);
   }
}

void UpdateCircularMenuPosition()
{
   if(ObjectFind(0, CircOrbBg()) < 0) return;
   int cw = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS, 0);
   int ch = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS, 0);
   if(cw <= 0) cw = 1920;
   if(ch <= 0) ch = 1080;

   if(g_UI.menuX < CIRC_PAD + CIRC_ORB_SIZE / 2) g_UI.menuX = CIRC_PAD + CIRC_ORB_SIZE / 2;
   if(g_UI.menuX > cw - CIRC_PAD - CIRC_ORB_SIZE / 2) g_UI.menuX = cw - CIRC_PAD - CIRC_ORB_SIZE / 2;
   if(g_UI.menuY < CIRC_PAD + CIRC_ORB_SIZE / 2) g_UI.menuY = CIRC_PAD + CIRC_ORB_SIZE / 2;
   if(g_UI.menuY > ch - CIRC_PAD - CIRC_ORB_SIZE / 2) g_UI.menuY = ch - CIRC_PAD - CIRC_ORB_SIZE / 2;

   CircApplyMenuPosition();
   SaveUIStates();
}

static bool g_PnlForegroundWasOn = false;
static int  g_PnlForegroundLock = 0;
void PnlLockForeground()
{
   if(g_PnlForegroundLock++ == 0)
   {
      g_PnlForegroundWasOn = (ChartGetInteger(0, CHART_FOREGROUND) != 0);
      if(g_PnlForegroundWasOn) ChartSetInteger(0, CHART_FOREGROUND, false);
   }
}
void PnlUnlockForeground()
{
   if(g_PnlForegroundLock == 0) return;
   if(--g_PnlForegroundLock == 0 && g_PnlForegroundWasOn)
      ChartSetInteger(0, CHART_FOREGROUND, true);
}

void CircHandleMouseMove(const int mx, const int my, const bool leftDown,
                         const bool pressStart)
{
   g_OrbMovedThisEvent = false;

   // Hidden menu: only the orb is interactive — and it must STAY draggable
   // while the ring is collapsed. A fresh press may therefore fall through to
   // the orb-grab logic below; hover and everything else is ignored.
   if(!g_UI.menuVisible && !g_OrbDragging && g_LongPressItem < 0 && !pressStart) return;

   if(g_LongPressItem >= 0)
   {
      if(leftDown)
      {
         if(MathAbs(mx - g_LongPressX) > LONG_PRESS_MOVE ||
            MathAbs(my - g_LongPressY) > LONG_PRESS_MOVE)
         {
            g_LongPressItem = -1;
            CircUnlockChart();
         }
         else if(!g_LongPressFired && GetTickCount() - g_LongPressStart >= LONG_PRESS_TIME)
         {
            g_LongPressFired = true;
            PnlOpen(g_LongPressItem);
            UISuppressNextClick();
         }
         return;
      }
      else
      {
         bool panelOpened = g_LongPressFired;   // long-press already opened the panel
         g_LongPressItem = -1;
         DragReleaseIf(DRAG_MENU);
         // Only an opened panel must swallow the release click; a plain item
         // click (released before the 250ms hold) must still reach the toggle.
         if(panelOpened) UISuppressNextClick();
         CircUnlockChart();
      }
   }

   if(!g_OrbDragging)
   {
      if(!pressStart) return;
      if(!DragCanGrab(DRAG_MENU)) return;

      const int hitIdx = CircItemAt(mx, my);
      // Items do not exist while the menu is hidden — never arm a long-press
      // on an invisible ring position (only the orb is interactive then).
      if(hitIdx >= 0 && g_UI.menuVisible)
      {
         int feat = RingFeature(hitIdx);
         if(feat == CIR_TOOLS) return; // tools toggles submenu on click, no long press
         g_LongPressItem  = RingPanel(hitIdx);
         g_LongPressStart = GetTickCount();
         g_LongPressX     = mx;
         g_LongPressY     = my;
         g_LongPressFired = false;
         DragClaim(DRAG_MENU);
         CircLockChart();
         return;
      }
      const int toolHit = ToolsItemAt(mx, my);
      if(toolHit >= 0)
      {
         g_LongPressItem  = ToolPanel(toolHit);
         g_LongPressStart = GetTickCount();
         g_LongPressX     = mx;
         g_LongPressY     = my;
         g_LongPressFired = false;
         DragClaim(DRAG_MENU);
         CircLockChart();
         return;
      }

      int ox = g_UI.menuX - CIRC_ORB_SIZE / 2;
      int oy = g_UI.menuY - CIRC_ORB_SIZE / 2;
      if(mx < ox || mx > ox + CIRC_ORB_SIZE || my < oy || my > oy + CIRC_ORB_SIZE) return;
      g_OrbDragging = true;
      g_OrbWasDragged = false;
      g_OrbGrabDX = g_UI.menuX - mx;
      g_OrbGrabDY = g_UI.menuY - my;
      g_OrbPressX = mx;
      g_OrbPressY = my;
      DragClaim(DRAG_MENU);
      CircLockChart();
      return;
   }

   if(!leftDown)
   {
      g_OrbDragging = false;
      DragReleaseIf(DRAG_MENU);
      // Only a REAL drag (>= ORB_DRAG_THRESHOLD px) may eat the release click.
      // Suppressing unconditionally made plain orb clicks unreliable whenever
      // the cursor was still moving at button-up (no click → menu won't toggle).
      if(g_OrbWasDragged) UISuppressNextClick();
      CircUnlockChart();
      if(g_OrbWasDragged) SaveUIStates();
      return;
   }

   if(MathAbs(mx - g_OrbPressX) > ORB_DRAG_THRESHOLD ||
      MathAbs(my - g_OrbPressY) > ORB_DRAG_THRESHOLD)
      g_OrbWasDragged = true;
   if(!g_OrbWasDragged) return;

   int cw = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS, 0);
   int ch = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS, 0);
   if(cw <= 0) cw = 1920;
   if(ch <= 0) ch = 1080;
   int nx = mx + g_OrbGrabDX;
   int ny = my + g_OrbGrabDY;
   int orbMinX = CIRC_PAD + CIRC_ORB_SIZE / 2;
   int orbMinY = CIRC_PAD + CIRC_ORB_SIZE / 2;
   int orbMaxX = cw - CIRC_PAD - CIRC_ORB_SIZE / 2;
   int orbMaxY = ch - CIRC_PAD - CIRC_ORB_SIZE / 2;
   if(nx <= CIRC_EDGE_TRIGGER || nx >= cw - CIRC_EDGE_TRIGGER ||
      ny <= CIRC_EDGE_TRIGGER || ny >= ch - CIRC_EDGE_TRIGGER)
   {
      int rx = MathMax(orbMinX, MathMin(orbMaxX, nx));
      int ry = MathMax(orbMinY, MathMin(orbMaxY, ny));
      int dLeft = rx - orbMinX, dRight = orbMaxX - rx;
      int dTop = ry - orbMinY, dBottom = orbMaxY - ry;
      int edge = 0, best = dLeft;
      if(dRight < best) { edge = 1; best = dRight; }
      if(dTop < best) { edge = 2; best = dTop; }
      if(dBottom < best) { edge = 3; best = dBottom; }
      if(edge == 0) rx = orbMinX;
      else if(edge == 1) rx = orbMaxX;
      else if(edge == 2) ry = orbMinY;
      else ry = orbMaxY;
      nx = rx; ny = ry;
   }
   else
   {
      nx = MathMax(orbMinX, MathMin(orbMaxX, nx));
      ny = MathMax(orbMinY, MathMin(orbMaxY, ny));
   }
   if(nx == g_UI.menuX && ny == g_UI.menuY) return;

   uint now = GetTickCount();
   if(now - g_OrbLastRedrawTick < CIRC_DRAG_REDRAW_INTERVAL) return;
   g_OrbLastRedrawTick = now;

   g_UI.menuX = nx;
   g_UI.menuY = ny;
   CircApplyMenuPosition();
   g_OrbMovedThisEvent = true;
   ChartRedraw();
}

void CircUpdateItemState(const int i)
{
   int feat = RingFeature(i);
   bool on = CircFeatureOn(feat);

   string icon = CircIcon(i);
   if(ObjectFind(0, icon) >= 0)
   {
      int ix, iy;
      CircLayout(i, ix, iy);
      CircConfigureIcon(icon, feat, on, ix, iy);
   }
   string bg = CircBg(i);
   if(ObjectFind(0, bg) >= 0)
   {
      string res = on ? "::Files\\Icons\\circ_on.bmp" : "::Files\\Icons\\circ_off.bmp";
      ObjectSetString(0, bg, OBJPROP_BMPFILE, 0, res);
      ObjectSetString(0, bg, OBJPROP_BMPFILE, 1, res);
   }

   if(CircHasBadge(feat)) CircShowBadge(i, on);
}

void ToolsUpdateItemState(const int t)
{
   int feat = ToolFeature(t);
   bool on = CircFeatureOn(feat);
   string icon = ToolsIcon(t);
   if(ObjectFind(0, icon) >= 0)
   {
      int tx, ty;
      ToolsLayout(t, tx, ty);
      CircConfigureIcon(icon, feat, on, tx, ty);
   }
   string bg = ToolsBg(t);
   if(ObjectFind(0, bg) >= 0)
   {
      string res = on ? "::Files\\Icons\\circ_on.bmp" : "::Files\\Icons\\circ_off.bmp";
      ObjectSetString(0, bg, OBJPROP_BMPFILE, 0, res);
      ObjectSetString(0, bg, OBJPROP_BMPFILE, 1, res);
   }
   // Refresh badge text + visibility (e.g. Step/Factor override → Auto)
   if(CircHasBadge(feat) && ObjectFind(0, ToolsBadgeBg(t)) >= 0)
   {
      ToolsShowBadge(t, on);
      string ttxt = ToolsBadgeTxt(t);
      if(ObjectFind(0, ttxt) >= 0)
      {
         ObjectSetString(0, ttxt, OBJPROP_TEXT, CircBadgeText(feat));
         ObjectSetString(0, ttxt, OBJPROP_TOOLTIP, CircBadgeTooltip(feat));
      }
      string tbg = ToolsBadgeBg(t);
      ObjectSetString(0, tbg, OBJPROP_TOOLTIP, CircBadgeTooltip(feat));
   }
}

void CircShowBadge(const int i, const bool show)
{
   int x = CIRC_HIDE_POS, y = CIRC_HIDE_POS;
   if(show)
      CircBadgePos(i, x, y);
   int tx = (show ? x + CIRC_BADGE_SIZE / 2 : x);
   int ty = (show ? y + CIRC_BADGE_SIZE / 2 : y);
   if(ObjectFind(0, CircBadgeBg(i)) >= 0)
   {
      ObjectSetInteger(0, CircBadgeBg(i), OBJPROP_XDISTANCE, x);
      ObjectSetInteger(0, CircBadgeBg(i), OBJPROP_YDISTANCE, y);
   }
   if(ObjectFind(0, CircBadgeTxt(i)) >= 0)
   {
      ObjectSetInteger(0, CircBadgeTxt(i), OBJPROP_XDISTANCE, tx);
      ObjectSetInteger(0, CircBadgeTxt(i), OBJPROP_YDISTANCE, ty);
   }
}

void UpdateCircularItemStates()
{
   for(int i = 0; i < RING_COUNT; i++)
      CircUpdateItemState(i);
   if(g_ToolsOpen)
      for(int t = 0; t < TOOL_COUNT; t++) ToolsUpdateItemState(t);
}

void UpdateCircularBadges()
{
   for(int i = 0; i < RING_COUNT; i++)
   {
      int feat = RingFeature(i);
      if(!CircHasBadge(feat)) continue;
      string bg = CircBadgeBg(i);
      if(ObjectFind(0, bg) >= 0)
         ObjectSetString(0, bg, OBJPROP_TOOLTIP, CircBadgeTooltip(feat));
      string txt = CircBadgeTxt(i);
      if(ObjectFind(0, txt) >= 0)
      {
         ObjectSetString(0, txt, OBJPROP_TEXT, CircBadgeText(feat));
         ObjectSetString(0, txt, OBJPROP_TOOLTIP, CircBadgeTooltip(feat));
      }
   }
}

//+------------------------------------------------------------------+
//| PERF: change-guarded periodic icon sync.                          |
//| Re-setting OBJPROP_BMPFILE makes MT4 re-decode the bitmap, so the |
//| old every-500ms unconditional pass churned the chart thread even  |
//| when nothing changed. We fingerprint the on/off state of all ring |
//| icons and only run the heavy pass when it actually differs.       |
//+------------------------------------------------------------------+
void UpdateMenuSyncIfChanged()
{
   static ulong s_LastStateHash = 0;

   // FNV-1a fingerprint of ring + tools on/off state AND badge TEXT, so
   // value-only changes (E/S hotkeys, factor override, TH mode) refresh the
   // badges — not just on/off flips.
   ulong h = 1469598103934665603;
   for(int i = 0; i < RING_COUNT; i++)
   {
      int feat = RingFeature(i);
      ulong v = (ulong)(CircFeatureOn(feat) ? 1 : 0);
      h = (h ^ (v + 0x9E3779B97F4A7C15 * (ulong)(feat + 1))) * 1099511628211;
      string t = CircBadgeText(feat);
      for(int c = 0; c < StringLen(t); c++)
         h = (h ^ StringGetCharacter(t, c)) * 1099511628211;
   }
   for(int t = 0; t < TOOL_COUNT; t++)
   {
      int feat = ToolFeature(t);
      ulong v = (ulong)(CircFeatureOn(feat) ? 1 : 0);
      h = (h ^ (v + 0x9E3779B97F4A7C15 * (ulong)(feat + 1))) * 1099511628211;
      string bt = CircBadgeText(feat);
      for(int c = 0; c < StringLen(bt); c++)
         h = (h ^ StringGetCharacter(bt, c)) * 1099511628211;
   }
   if(h == s_LastStateHash) return;   // nothing visible changed -> no churn
   s_LastStateHash = h;

   if(g_UI.menuVisible)
      UpdateCircularItemStates();
   UpdateCircularBadges();
}

int CircIndexFromName(const string name)
{
   string pfx;
   // NOTE: check "CircBadgeTxt" BEFORE "CircBadge" — the plain-prefix match
   // would otherwise swallow the text object and mis-parse its index.
   pfx = g_UI.btnPrefix + "CircBadgeTxt";
   if(StringFind(name, pfx) == 0) return (int)StringToInteger(StringSubstr(name, StringLen(pfx)));
   pfx = g_UI.btnPrefix + "CircBg";
   if(StringFind(name, pfx) == 0) return (int)StringToInteger(StringSubstr(name, StringLen(pfx)));
   pfx = g_UI.btnPrefix + "CircIcon";
   if(StringFind(name, pfx) == 0) return (int)StringToInteger(StringSubstr(name, StringLen(pfx)));
   pfx = g_UI.btnPrefix + "CircBadge";
   if(StringFind(name, pfx) == 0) return (int)StringToInteger(StringSubstr(name, StringLen(pfx)));
   return -1;
}

int ToolsIndexFromName(const string name)
{
   string pfx;
   // NOTE: check "ToolsBadgeTxt" BEFORE "ToolsBadge" — the plain-prefix match
   // would otherwise swallow the text object and mis-parse its index.
   pfx = g_UI.btnPrefix + "ToolsBadgeTxt";
   if(StringFind(name, pfx) == 0) return (int)StringToInteger(StringSubstr(name, StringLen(pfx)));
   pfx = g_UI.btnPrefix + "ToolsBg";
   if(StringFind(name, pfx) == 0) return (int)StringToInteger(StringSubstr(name, StringLen(pfx)));
   pfx = g_UI.btnPrefix + "ToolsIcon";
   if(StringFind(name, pfx) == 0) return (int)StringToInteger(StringSubstr(name, StringLen(pfx)));
   pfx = g_UI.btnPrefix + "ToolsBadge";
   if(StringFind(name, pfx) == 0) return (int)StringToInteger(StringSubstr(name, StringLen(pfx)));
   return -1;
}

//+------------------------------------------------------------------+
//| Handle Button Click Events                                       |
//+------------------------------------------------------------------+
int HandleButtonClick(const string clickedObject)
{
   if(clickedObject == CircOrbBg())
   {
      if(g_OrbWasDragged)
      {
         g_OrbWasDragged = false;
         return REFRESH_NONE;
      }
      ToggleMenuVisibility();
      return REFRESH_NONE;
   }

   // --- Tools half-circle items ---
   int tidx = ToolsIndexFromName(clickedObject);
   if(tidx >= 0)
   {
      if(StringFind(clickedObject, g_UI.btnPrefix + "ToolsBadge") == 0)
      {
         UISuppressNextClick();
         PnlOpen(ToolPanel(tidx));
         return REFRESH_NONE;
      }
      if(g_LongPressFired)
      {
         g_LongPressFired = false;
         g_LongPressItem = -1;
         return REFRESH_NONE;
      }
      int tfeat = ToolFeature(tidx);
      int tflags = REFRESH_NONE;
      if(tfeat == CIR_PIN)
      {
         g_waitingForCustomPriceClick = true;
         g_customPriceKeyboardOverride = true;
         string overrideFlagName = "Biotak_CustomPriceOverride_" + GetCachedSymbol();
         GlobalVariableSet(overrideFlagName, 1.0);
         ObjectDelete(0, g_customPriceHorizontalLineName);
         g_customPriceLineCreated = false;
         double currentPrice = iClose(_Symbol, (ENUM_TIMEFRAMES)GetCachedPeriod(), 0);
         g_customTHStartPrice = currentPrice;
         g_thStartPointType = TH_START_POINT_CUSTOM_PRICE;
         string gvarName = "Biotak_CustomPrice_" + GetCachedSymbol();
         GlobalVariableSet(gvarName, currentPrice);
         CreateCustomPriceLine(currentPrice, Digits, true);
         g_redrawTHLevelsNeeded = true;
         tflags = REFRESH_ALL;
      }
      else if(tfeat == CIR_STEP_OVERRIDE)
      {
         g_stepModeOverride++;
         if(g_stepModeOverride > 3) g_stepModeOverride = -1;
         string stepModeGvarName = "Biotak_StepMode_" + GetCachedChartIdStr();
         if(g_stepModeOverride == -1) GlobalVariableDel(stepModeGvarName);
         else GlobalVariableSet(stepModeGvarName, (double)g_stepModeOverride);
         g_forceClearOnNextDraw = true;
         g_redrawTHLevelsNeeded = true;
         tflags = REFRESH_ALL;
      }
      else if(tfeat == CIR_FACTOR_OVERRIDE)
      {
         if(g_factorValueOverride == 0) g_factorValueOverride = 25;
         else if(g_factorValueOverride == 25) g_factorValueOverride = 50;
         else if(g_factorValueOverride == 50) g_factorValueOverride = 100;
         else if(g_factorValueOverride == 100) g_factorValueOverride = 144;
         else g_factorValueOverride = 0;
         string factorGvarName = "Biotak_Factor_" + GetCachedChartIdStr();
         if(g_factorValueOverride == 0) GlobalVariableDel(factorGvarName);
         else GlobalVariableSet(factorGvarName, g_factorValueOverride);
         g_forceClearOnNextDraw = true;
         g_redrawTHLevelsNeeded = true;
         tflags = REFRESH_ALL;
      }
      ToolsUpdateItemState(tidx);
      UpdateCircularBadges();
      SaveUIStates();
      return tflags;
   }

   int idx = CircIndexFromName(clickedObject);
   if(idx < 0) return REFRESH_NONE;

   if(StringFind(clickedObject, g_UI.btnPrefix + "CircBadge") == 0)
   {
      UISuppressNextClick();
      PnlOpen(RingPanel(idx));
      return REFRESH_NONE;
   }

   if(g_LongPressFired)
   {
      g_LongPressFired = false;
      g_LongPressItem  = -1;
      return REFRESH_NONE;
   }

   int feat = RingFeature(idx);
   if(feat == CIR_TOOLS)
   {
      if(g_ToolsOpen) DeleteToolsMenu();
      else CreateToolsMenu();
      return REFRESH_NONE;
   }

   int refreshFlags = REFRESH_NONE;
   if(feat == CIR_TRIGGER)
   {
      g_triggerLevelsEnabled = !g_triggerLevelsEnabled;
      string triggerGvarName = "Biotak_TriggerLevels_" + GetCachedChartIdStr();
      GlobalVariableSet(triggerGvarName, g_triggerLevelsEnabled ? 1.0 : 0.0);
      g_forceClearOnNextDraw = true;
      g_redrawTHLevelsNeeded = true;
      refreshFlags = REFRESH_ALL;
   }
   else if(feat == CIR_ZONES)
   {
      g_showMidZones = !g_showMidZones;
      g_redrawTHLevelsNeeded = true;
      refreshFlags = REFRESH_BUFFERS;
   }
   else if(feat == CIR_ATR)
   {
      g_atrLabelsVisible = !g_atrLabelsVisible;
      g_showATRLabels = g_atrLabelsVisible;   // keep the ATR card mirror in sync
      string atrGvarNameKey = "Biotak_ATRLabels_" + GetCachedChartIdStr();
      GlobalVariableSet(atrGvarNameKey, g_atrLabelsVisible ? 1.0 : 0.0);
      string objectPrefix = inpObjectPrefix + "_" + GetCurrentTimeframe() + "_";
      SetATRLabelsVisibility(objectPrefix, g_atrLabelsVisible);
      g_labelsRelayoutNeeded = true;
      refreshFlags = REFRESH_ALL;
   }
   else if(feat == CIR_TH)
   {
      if(g_thLabelsMode == 1) {
         if(inpShowStandardTHs) g_thLabelsMode = 3;
         else g_thLabelsMode = 0;
      }
      else if(g_thLabelsMode == 3) {
         g_thLabelsMode = 0;
      }
      else {
         g_thLabelsMode = 1;
      }
      g_thLabelsVisible = (g_thLabelsMode != 0);
      SyncTHFlagsFromMode();   // flags follow the mode → TH card stays in sync
      string thGvar = "Biotak_THLabels_" + GetCachedChartIdStr();
      GlobalVariableSet(thGvar, (double)g_thLabelsMode);
      string objectPrefix = inpObjectPrefix + "_" + GetCurrentTimeframe() + "_";
      SetTHLabelsVisibility(objectPrefix, g_thLabelsMode);
      g_labelsRelayoutNeeded = true;
      refreshFlags = REFRESH_ALL;
   }
   else if(feat == CIR_VLOCK)
   {
      // View Lock needs no indicator recalc — it only pins the chart view.
      ViewLockSetEnabled(!g_viewLockEnabled);
      CircUpdateItemState(idx);
      ThrottledChartRedraw();
      SaveUIStates();
      return REFRESH_NONE;
   }
   // TH3TOOL-OFF:
   //else if(feat == CIR_TH3)
   //{
   //   g_enableTH3Tool = !g_enableTH3Tool;
   //   UpdateAllTH3Objects();
   //   refreshFlags = REFRESH_ALL;
   //}
   else if(feat == CIR_HTF)
   {
      g_UI.showHTF = !g_UI.showHTF;
      refreshFlags = REFRESH_HTF;
   }

   CircUpdateItemState(idx);
   UpdateCircularBadges();
   SaveUIStates();
   return refreshFlags;
}

void ToggleMenuVisibility()
{
   bool willShow = !g_UI.menuVisible;
   if(willShow) PnlLockForeground();
   else PnlUnlockForeground();
   g_UI.menuVisible = willShow;
   if(!g_UI.menuVisible) PnlCloseAll();
   DeleteMenu();
   CreateMenu();
   SaveUIStates();
   ChartRedraw();
}

void CleanupUIStates(const int reason)
{
   if(StringLen(g_UI.gvPrefix) == 0) return;   // UI never initialized
   if(reason == REASON_REMOVE)
   {
      ClearAllGVs();
      CleanupHTFCandlesGVs();
   }
   else
   {
      SaveUIStates(true);
      SaveHTFCandlesSettings();
   }
}

#endif // BIOTAK_MENU_MQH
