//+------------------------------------------------------------------+
//|                                             BiotakPanels.mqh   |
//|        Settings panels — TV-white modern dialogs (R-PANELMOD)       |
//|   White cards (pre-rendered BMP skins from gen-th3-icons.js) ·       |
//|   single-line rows: checkbox / dropdown-select / pills / underline  |
//|   tabs · full-width sliders · Reset/Done (live-apply, TV look)      |
//+------------------------------------------------------------------+
#property strict

//--- embedded panel skins (generated by tools/gen-icons.js)
#resource "\\Files\\Icons\\pnl_card1.bmp"
// ICON-DIET 2026-09-27: pnl_card1f..pnl_card10f are retired (4.71 MB = 34% of
// the icon payload, each differing from its plain twin in 26 rows). PnlCardFade()
// cards overlay this one wash instead — the same move the wide body makes with
// pnl_cardWfade.bmp.
#resource "\\Files\\Icons\\pnl_cardfade.bmp"
#resource "\\Files\\Icons\\pnl_card2.bmp"
#resource "\\Files\\Icons\\pnl_card3.bmp"
#resource "\\Files\\Icons\\pnl_card4.bmp"
#resource "\\Files\\Icons\\pnl_card5.bmp"
#resource "\\Files\\Icons\\pnl_card6.bmp"
#resource "\\Files\\Icons\\pnl_card7.bmp"
#resource "\\Files\\Icons\\pnl_card8.bmp"
#resource "\\Files\\Icons\\pnl_card9.bmp"
#resource "\\Files\\Icons\\pnl_card10.bmp"
// ICON-DIET 2026-09-27: pnl_card11..16 (+f) are 11.4 MB with NO runtime path.
// PnlIsWide() sends any card over PNL_WIDE_MIN_ROWS 10 to the COMPOSED body
// (pnl_cardWtop/mid/bot/fade), and the baked lookup runs only in the !wide
// branch, so the index it clamps is at most 10. The range stays 1..10.
#resource "\\Files\\Icons\\pnl_knob.bmp"
#resource "\\Files\\Icons\\pnl_cb_on.bmp"
#resource "\\Files\\Icons\\pnl_cb_off.bmp"
//--- Base Box MINI strip icons (TradingView-style) — R-BKSTRIP 2026-09-07,
//--- TV-parity 2026-09-07: pencil (border) + T (text) join the bucket (fill).
//--- bk_done retired with the done slot (TV dismisses via outside-click/Esc).
#resource "\\Files\\Icons\\bk_strip.bmp"
#resource "\\Files\\Icons\\bk_style0.bmp"
#resource "\\Files\\Icons\\bk_style1.bmp"
#resource "\\Files\\Icons\\bk_style2.bmp"
#resource "\\Files\\Icons\\bk_style3.bmp"
#resource "\\Files\\Icons\\bk_style4.bmp"
#resource "\\Files\\Icons\\bk_w1.bmp"
#resource "\\Files\\Icons\\bk_w2.bmp"
#resource "\\Files\\Icons\\bk_w3.bmp"
#resource "\\Files\\Icons\\bk_w4.bmp"
#resource "\\Files\\Icons\\bk_w5.bmp"
#resource "\\Files\\Icons\\bk_pencil.bmp"
#resource "\\Files\\Icons\\bk_bucket.bmp"
#resource "\\Files\\Icons\\bk_text.bmp"
#resource "\\Files\\Icons\\bk_lock_off.bmp"
#resource "\\Files\\Icons\\bk_lock_on.bmp"
#resource "\\Files\\Icons\\bk_del.bmp"
#resource "\\Files\\Icons\\bk_more.bmp"
#resource "\\Files\\Icons\\bk_chev.bmp"
#resource "\\Files\\Icons\\bk_dds.bmp"
#resource "\\Files\\Icons\\bk_ddw.bmp"

//--- R-PANELUI2 (2026-09-11): every remaining panel bitmap. The redesign
//--- draws its chrome from pre-rendered BMPs (MT4 cannot blur, gradient or
//--- round a corner at runtime), so each one MUST be embedded here — an
//--- undeclared bitmap fails silently and the row renders as bare labels.
//--- P-UI-06: one runtime bitmap = one #resource. Generated by
//--- tools/gen-th3-icons.js; list maintained by tools/add-panel-resources.py.
//--- card skins, icon chips, switches, rails, washes and pills
//--- the wide card's COMPOSED body (P-UI-71c). `pnl_cardW{n}` stops at 12
//--- pair-lines while card 2 needs 13 and the Base Box card 19, so a wide body
//--- is built from these four pieces (top cap + one band per pair-line + the
//--- footer cap + the `.fade` wash — tools/slice-card-skins.py). A piece that is
//--- sliced but NOT declared here compiles clean and renders as NO CARD AT ALL:
//--- that is exactly what shipped (the user's "پشت پس زمینه نداره"), so
//--- `tools/panel-wiring-audit.py` now fails the build when a runtime
//--- `::Files\\Icons\\*.bmp` reference has no declaration (its [chrome] check).
#resource "\\Files\\Icons\\pnl_cardWbot.bmp"
#resource "\\Files\\Icons\\pnl_cardWfade.bmp"
#resource "\\Files\\Icons\\pnl_cardWmid.bmp"
#resource "\\Files\\Icons\\pnl_cardWtop.bmp"

//--- R-PANELUI2 (2026-09-11): every remaining panel bitmap. The redesign
//--- draws its chrome from pre-rendered BMPs (MT4 cannot blur, gradient or
//--- round a corner at runtime), so each one MUST be embedded here — an
//--- undeclared bitmap fails silently and the row renders as bare labels.
//--- P-UI-06: one runtime bitmap = one #resource. Generated by
//--- tools/gen-th3-icons.js; list maintained by tools/add-panel-resources.py.
//--- card skins, icon chips, switches, rails, washes and pills
// ICON-DIET 2026-09-27: pnl_cardW1..12 (+f) are 25.4 MB and produced by nothing.
// The wide card body is COMPOSED (P-UI-71c) from the four pieces below; this
// whole baked family was the pre-P-UI-71 lookup table. Deleting it is the
// single largest byte win in the repo and costs no runtime path.
// (PNL_WIDE_ROWS_MAX, the constant that named this range, is gone too.)
//--- P-DRAW-73: `pnl_hairW_gold` and `pnl_topbarW_gold` moved DOWN to DrawStrip.mqh,
//--- the only module with a runtime path for them (the wide gear head). They were
//--- declared here, so a wide panel's head art depended on this file being included
//--- in the same compilation unit (F-03: a workaround is named where it is used).
#resource "\\Files\\Icons\\pnl_secbandW.bmp"

//--- R-PANELUI2 (2026-09-11): every remaining panel bitmap. The redesign
//--- draws its chrome from pre-rendered BMPs (MT4 cannot blur, gradient or
//--- round a corner at runtime), so each one MUST be embedded here — an
//--- undeclared bitmap fails silently and the row renders as bare labels.
//--- P-UI-06: one runtime bitmap = one #resource. Generated by
//--- tools/gen-th3-icons.js; list maintained by tools/add-panel-resources.py.
//--- card skins, icon chips, switches, rails, washes and pills
#resource "\\Files\\Icons\\pnl_glass22.bmp"
#resource "\\Files\\Icons\\pnl_glass38.bmp"
#resource "\\Files\\Icons\\pnl_glass46.bmp"
#resource "\\Files\\Icons\\pal_cell26.bmp"
#resource "\\Files\\Icons\\pal_ring26.bmp"
#resource "\\Files\\Icons\\pal_cell22.bmp"
#resource "\\Files\\Icons\\pal_ring22.bmp"
#resource "\\Files\\Icons\\pal_grip.bmp"
#resource "\\Files\\Icons\\pnl_nav.bmp"
#resource "\\Files\\Icons\\pnl_trackgloss.bmp"
#resource "\\Files\\Icons\\pal_card26.bmp"
#resource "\\Files\\Icons\\pal_card22.bmp"

//--- R-PANELUI2 (2026-09-11): every remaining panel bitmap. The redesign
//--- draws its chrome from pre-rendered BMPs (MT4 cannot blur, gradient or
//--- round a corner at runtime), so each one MUST be embedded here — an
//--- undeclared bitmap fails silently and the row renders as bare labels.
//--- P-UI-06: one runtime bitmap = one #resource. Generated by
//--- tools/gen-th3-icons.js; list maintained by tools/add-panel-resources.py.
//--- 57 glyph inks x (6 accents + muted) — preview const I{}
#resource "\\Files\\Icons\\gl_box_i_gold.bmp"
#resource "\\Files\\Icons\\gl_candle_i_gold.bmp"
#resource "\\Files\\Icons\\gl_check_i_gold.bmp"
#resource "\\Files\\Icons\\gl_crosshair_i_gold.bmp"
#resource "\\Files\\Icons\\gl_gauge_i_gold.bmp"
#resource "\\Files\\Icons\\gl_layers_i_gold.bmp"
#resource "\\Files\\Icons\\gl_line_i_gold.bmp"
#resource "\\Files\\Icons\\gl_pin_i_gold.bmp"
#resource "\\Files\\Icons\\gl_sigma_i_gold.bmp"
#resource "\\Files\\Icons\\gl_steps_i_gold.bmp"
#resource "\\Files\\Icons\\gl_target_i_gold.bmp"
#resource "\\Files\\Icons\\gl_type_i_gold.bmp"
#resource "\\Files\\Icons\\gl_wave_i_gold.bmp"
//--- card skins, icon chips, switches, rails, washes and pills
#resource "\\Files\\Icons\\pnl_btn_ghost.bmp"
#resource "\\Files\\Icons\\pnl_btn_prim_gold.bmp"
//--- card skins, icon chips, switches, rails, washes and pills
// ICON-DIET 2026-09-27: pnl_card<n>f retired — the .fade wash is one overlay
// now (pnl_cardfade.bmp, declared at the top of this block with the cards).

//--- R-PANELUI2 (2026-09-11): every remaining panel bitmap. The redesign
//--- draws its chrome from pre-rendered BMPs (MT4 cannot blur, gradient or
//--- round a corner at runtime), so each one MUST be embedded here — an
//--- undeclared bitmap fails silently and the row renders as bare labels.
//--- P-UI-06: one runtime bitmap = one #resource. Generated by
//--- tools/gen-th3-icons.js; list maintained by tools/add-panel-resources.py.
//--- 57 glyph inks x (6 accents + muted) — preview const I{}
#resource "\\Files\\Icons\\gl_alignC_gold.bmp"
#resource "\\Files\\Icons\\gl_alignC_m.bmp"
#resource "\\Files\\Icons\\gl_alignL_gold.bmp"
#resource "\\Files\\Icons\\gl_alignL_m.bmp"
#resource "\\Files\\Icons\\gl_back_gold.bmp"
#resource "\\Files\\Icons\\gl_back_m.bmp"
#resource "\\Files\\Icons\\gl_bold_gold.bmp"
#resource "\\Files\\Icons\\gl_bold_m.bmp"
#resource "\\Files\\Icons\\gl_box_gold.bmp"
#resource "\\Files\\Icons\\gl_box_m.bmp"
#resource "\\Files\\Icons\\gl_candle_gold.bmp"
#resource "\\Files\\Icons\\gl_candle_m.bmp"
#resource "\\Files\\Icons\\gl_check_gold.bmp"
#resource "\\Files\\Icons\\gl_check_m.bmp"
#resource "\\Files\\Icons\\gl_clock_gold.bmp"
#resource "\\Files\\Icons\\gl_clock_m.bmp"
#resource "\\Files\\Icons\\gl_contrast_gold.bmp"
#resource "\\Files\\Icons\\gl_contrast_m.bmp"
#resource "\\Files\\Icons\\gl_crosshair_gold.bmp"
#resource "\\Files\\Icons\\gl_crosshair_m.bmp"
#resource "\\Files\\Icons\\gl_droplet_gold.bmp"
#resource "\\Files\\Icons\\gl_droplet_m.bmp"
#resource "\\Files\\Icons\\gl_eye_gold.bmp"
#resource "\\Files\\Icons\\gl_eye_m.bmp"
#resource "\\Files\\Icons\\gl_flag_gold.bmp"
#resource "\\Files\\Icons\\gl_flag_m.bmp"
#resource "\\Files\\Icons\\gl_fn_gold.bmp"
#resource "\\Files\\Icons\\gl_fn_m.bmp"
#resource "\\Files\\Icons\\gl_gap_gold.bmp"
#resource "\\Files\\Icons\\gl_gap_m.bmp"
#resource "\\Files\\Icons\\gl_gauge_gold.bmp"
#resource "\\Files\\Icons\\gl_gauge_m.bmp"
#resource "\\Files\\Icons\\gl_info_gold.bmp"
#resource "\\Files\\Icons\\gl_info_m.bmp"
#resource "\\Files\\Icons\\gl_layers_gold.bmp"
#resource "\\Files\\Icons\\gl_layers_m.bmp"
#resource "\\Files\\Icons\\gl_line_gold.bmp"
#resource "\\Files\\Icons\\gl_line_m.bmp"
#resource "\\Files\\Icons\\gl_linestyle_gold.bmp"
#resource "\\Files\\Icons\\gl_linestyle_m.bmp"
// ICON-DIET 2026-09-27: gl_magnet_{gold,m} — "magnet" is in no PnlSpecAdd ico
// census and no PnlMarkIcon(); the magnet card rows went with BKMAGNET2-OFF.
// gl_reset_gold — the Reset footer button is created with primary=false, so it
// only ever resolves gl_reset_m.bmp.
#resource "\\Files\\Icons\\gl_nav_gold.bmp"
#resource "\\Files\\Icons\\gl_nav_m.bmp"
#resource "\\Files\\Icons\\gl_pin_gold.bmp"
#resource "\\Files\\Icons\\gl_pin_m.bmp"
#resource "\\Files\\Icons\\gl_plus_gold.bmp"
#resource "\\Files\\Icons\\gl_plus_m.bmp"
#resource "\\Files\\Icons\\gl_power_gold.bmp"
#resource "\\Files\\Icons\\gl_power_m.bmp"
#resource "\\Files\\Icons\\gl_reset_m.bmp"
#resource "\\Files\\Icons\\gl_ruler_gold.bmp"
#resource "\\Files\\Icons\\gl_ruler_m.bmp"
#resource "\\Files\\Icons\\gl_sigma_gold.bmp"
#resource "\\Files\\Icons\\gl_sigma_m.bmp"
#resource "\\Files\\Icons\\gl_sparkles_gold.bmp"
#resource "\\Files\\Icons\\gl_sparkles_m.bmp"
#resource "\\Files\\Icons\\gl_square_gold.bmp"
#resource "\\Files\\Icons\\gl_square_m.bmp"
#resource "\\Files\\Icons\\gl_squarefill_gold.bmp"
#resource "\\Files\\Icons\\gl_squarefill_m.bmp"
#resource "\\Files\\Icons\\gl_steps_gold.bmp"
#resource "\\Files\\Icons\\gl_steps_m.bmp"
#resource "\\Files\\Icons\\gl_swap_gold.bmp"
#resource "\\Files\\Icons\\gl_swap_m.bmp"
#resource "\\Files\\Icons\\gl_tag_gold.bmp"
#resource "\\Files\\Icons\\gl_tag_m.bmp"
#resource "\\Files\\Icons\\gl_target_gold.bmp"
#resource "\\Files\\Icons\\gl_target_m.bmp"
#resource "\\Files\\Icons\\gl_template_gold.bmp"
#resource "\\Files\\Icons\\gl_template_m.bmp"
#resource "\\Files\\Icons\\gl_textsize_gold.bmp"
#resource "\\Files\\Icons\\gl_textsize_m.bmp"
#resource "\\Files\\Icons\\gl_timer_gold.bmp"
#resource "\\Files\\Icons\\gl_timer_m.bmp"
#resource "\\Files\\Icons\\gl_type_gold.bmp"
#resource "\\Files\\Icons\\gl_type_m.bmp"
#resource "\\Files\\Icons\\gl_valign_gold.bmp"
#resource "\\Files\\Icons\\gl_valign_m.bmp"
#resource "\\Files\\Icons\\gl_wave_gold.bmp"
#resource "\\Files\\Icons\\gl_wave_m.bmp"
#resource "\\Files\\Icons\\gl_weight_gold.bmp"
#resource "\\Files\\Icons\\gl_weight_m.bmp"
#resource "\\Files\\Icons\\gl_wick_gold.bmp"
#resource "\\Files\\Icons\\gl_wick_m.bmp"
#resource "\\Files\\Icons\\gl_x_gold.bmp"
#resource "\\Files\\Icons\\gl_x_m.bmp"
//--- card skins, icon chips, switches, rails, washes and pills
#resource "\\Files\\Icons\\pnl_actbg_gold.bmp"
#resource "\\Files\\Icons\\pnl_add_gold.bmp"
#resource "\\Files\\Icons\\pnl_chev_gold.bmp"
#resource "\\Files\\Icons\\pnl_chevr_gold.bmp"
#resource "\\Files\\Icons\\pnl_chip.bmp"
#resource "\\Files\\Icons\\pnl_chip_gold.bmp"
#resource "\\Files\\Icons\\pnl_cntchip.bmp"
#resource "\\Files\\Icons\\pnl_dsw_off.bmp"
#resource "\\Files\\Icons\\pnl_dsw_on_gold.bmp"
#resource "\\Files\\Icons\\pnl_hair_gold.bmp"
#resource "\\Files\\Icons\\pnl_keycap.bmp"
#resource "\\Files\\Icons\\pnl_mark_gold.bmp"
#resource "\\Files\\Icons\\pnl_rail_gold.bmp"
#resource "\\Files\\Icons\\pnl_secband.bmp"
#resource "\\Files\\Icons\\pnl_secdot_gold.bmp"
#resource "\\Files\\Icons\\pnl_subdot_amber.bmp"
#resource "\\Files\\Icons\\pnl_subdot_jade.bmp"
#resource "\\Files\\Icons\\pnl_sw_off.bmp"
#resource "\\Files\\Icons\\pnl_sw_on_gold.bmp"
#resource "\\Files\\Icons\\pnl_topbar_gold.bmp"
#resource "\\Files\\Icons\\pnl_vchip_gold.bmp"
#resource "\\Files\\Icons\\pnl_xbtn.bmp"

#include "BiotakPanels_State.mqh"
#include "BiotakPanels_PalA.mqh"
#include "BiotakPanels_PalB.mqh"
#include "BiotakPanels_Apply.mqh"
#include "BiotakPanels_Rows.mqh"
#include "BiotakPanels_Build.mqh"
#include "BiotakPanels_Hit.mqh"
#include "BiotakPanels_Route.mqh"
#include "BiotakPanels_Life.mqh"
