// BiotakMenu_A.mqh - BiotakMenu.mqh split 2026-09-29: exact lines 8-1420, byte-identical, zero renames.
#ifndef BIOTAK_MENU_A_MQH
#define BIOTAK_MENU_A_MQH


#property strict

#include "HTFCandles.mqh"

//+------------------------------------------------------------------+
//| Embedded icon resources (BMP, generated by tools/gen-icons.ps1)   |
//+------------------------------------------------------------------+
#resource "\\Files\\Icons\\zone_off.bmp"
#resource "\\Files\\Icons\\zone_on.bmp"
#resource "\\Files\\Icons\\zones_off.bmp"
#resource "\\Files\\Icons\\zones_on.bmp"
#resource "\\Files\\Icons\\dots_off.bmp"
#resource "\\Files\\Icons\\dots_on.bmp"
#resource "\\Files\\Icons\\atr_off.bmp"
#resource "\\Files\\Icons\\atr_on.bmp"
// box_off/box_on (a PADLOCK, drawn for the retired View Lock) are RETIRED
// 2026-09-14: Base / Knot is a MEASURING tool, so it draws a ruler now.
#resource "\\Files\\Icons\\ruler_off.bmp"
#resource "\\Files\\Icons\\ruler_on.bmp"
#resource "\\Files\\Icons\\htf_off.bmp"
#resource "\\Files\\Icons\\htf_on.bmp"
// TH3TOOL-ON (2026-09-19): restored from TH3TOOL-OFF.
#resource "\\Files\\Icons\\custom_off.bmp"
#resource "\\Files\\Icons\\custom_on.bmp"
#resource "\\Files\\Icons\\leg_off.bmp"
#resource "\\Files\\Icons\\leg_on.bmp"
#resource "\\Files\\Icons\\pin_off.bmp"
#resource "\\Files\\Icons\\pin_on.bmp"
#resource "\\Files\\Icons\\tools_off.bmp"
#resource "\\Files\\Icons\\tools_on.bmp"
// P-UI-131: the GENERAL cell's face. Same gear art the strip's "..." cell wears
// (ART.gear == BK_GEAR in tools/gen-th3-icons.js), baked by that one generator.
#resource "\\Files\\Icons\\gear_off.bmp"
#resource "\\Files\\Icons\\gear_on.bmp"
// P-HR-01: the Horizontal Ray cell's face (ART.hray, baked by the generator).
#resource "\\Files\\Icons\\hray_off.bmp"
#resource "\\Files\\Icons\\hray_on.bmp"
#resource "\\Files\\Icons\\path_off.bmp"
#resource "\\Files\\Icons\\path_on.bmp"
#resource "\\Files\\Icons\\orb_bg.bmp"
//--- ORBWORD-OFF (2026-09-12, user decision — no wordmark on the orb, ever:
//--- the "TRex" text over the bow read as mud on the chart). The open-state
//--- skin + its builder stay in place for a one-line restore (uncomment the
//--- word branch in CircOrbRes below): tools/orb/make-orb-word.ps1 (master),
//--- tools/gen-th3-icons.js (embed), Files/Icons/orb_word.bmp (skin).
// ICON-DIET 2026-09-27: the orb_word.bmp #resource itself is gone. ORBWORD-OFF
// commented out the only call site on 2026-09-12, so 20 KB rode along unused.
// CircOrbRes now returns orb_bg.bmp unconditionally (see below).
// P-UI-120: the hover chip's FACE (rounded plate + gold frame + tilted title, the
// orb's chip only). Baked by tools/orb/make-tip-face.ps1 from the measured palette
// of the user's own plate into tools/orb/tip-face-master.bgra; the generator embeds
// it here and lists it in the manifest.
#resource "\\Files\\Icons\\tip_face.bmp"
// P-UI-123: the same master's three other sides, derived by the generator (mirror V,
// 90 CW, 90 CCW) - the arc's opening must face the orb on every side it can open on.
#resource "\\Files\\Icons\\circ_off.bmp"
#resource "\\Files\\Icons\\circ_on.bmp"
// R-SUBLADDER (2026-09-11): Tools grid panel + its cells. cell_*.bmp is the
// rounded-square tile (46px canvas == the 46px pitch); sub_panel_r<N>[p].bmp is
// the panel backdrop, one per visible row count 1..4 ('p' = with pager strip).
// One BMP per height because stretching a single rounded panel would turn its
// 13px corners into ellipses and blur its 1px border (P-ICONS-* — never scale).
#resource "\\Files\\Icons\\cell_off.bmp"
#resource "\\Files\\Icons\\cell_on.bmp"
#resource "\\Files\\Icons\\sub_panel_r1.bmp"
#resource "\\Files\\Icons\\sub_panel_r1p.bmp"
#resource "\\Files\\Icons\\sub_panel_r2.bmp"
#resource "\\Files\\Icons\\sub_panel_r2p.bmp"
#resource "\\Files\\Icons\\sub_panel_r3.bmp"
#resource "\\Files\\Icons\\sub_panel_r3p.bmp"
#resource "\\Files\\Icons\\sub_panel_r4.bmp"
#resource "\\Files\\Icons\\sub_panel_r4p.bmp"
#resource "\\Files\\Icons\\step_off.bmp"
#resource "\\Files\\Icons\\step_on.bmp"

//+------------------------------------------------------------------+
//| Circular menu geometry                                           |
//+------------------------------------------------------------------+
#define CIRC_BTN_SIZE    44
#define CIRC_ICON_SIZE   28
#define CIRC_BG_SIZE     52    // circular glass skin: 44px diameter + 4px glow margin
#define CIRC_BG_MARGIN   4
#define CIRC_ICON_OFFSET ((CIRC_BTN_SIZE - CIRC_ICON_SIZE) / 2)
#define CIRC_ORB_SIZE    64
#define CIRC_ORB_RADIUS  (CIRC_ORB_SIZE / 2)
#define CIRC_ORB_BG_SIZE 72    // scaled orb canvas: 64px orb + 4px glow margin
#define CIRC_ORB_BG_MARGIN 4
#define CIRC_BADGE_SIZE  16
#define CIRC_BADGE_FLOAT 12   // badge float gap outside the item skin edge
#define CIRC_ITEM_REACH  (CIRC_BTN_SIZE / 2 + CIRC_BADGE_FLOAT + CIRC_BADGE_SIZE / 2)  // outermost badge pixel from item center
// Nine main-ring items need r >= (44+6)/2 / sin(π/9) = 73.1 px. Raised from 64
// when RING_LEG was appended (was 64 with 8 items, 6.4 px spare; now 80 gives 6.9 px).
#define CIRC_RADIUS      80
#define CIRC_GAP         6
#define CIRC_RAIL        90
#define CIRC_PAD         10
#define CIRC_HIDE_POS   -500
#define CIRC_EDGE_TRIGGER 90
#define CIRC_MIN_RADIUS  40
#define ORB_DRAG_THRESHOLD 3  // px of movement before a press counts as a drag

//--- feature indices (panel + state keys — stable, never reorder)
//    Slot 0/1 = ZONES & LEVELS — the PRIMARY feature of this indicator.
//    (The old separate Lines-Visibility toggle is gone: its master switch
//    is row 0 of the Zones & Levels card, and hotkey L still toggles it.)
#define CIR_ZONES           1   // Zones & Levels — main card (levels + mid zones)
#define CIR_TRIGGER         0   // Trigger Zones (overlay; unified lines live on card 7)
#define CIR_ATR             2   // ATR Labels (g_atrLabelsVisible)
#define CIR_TH              3   // TH Labels (g_thLabelsVisible)
// VIEWLOCK-OFF: CIR_VLOCK slot retired (was 4, View Lock) — ring is now 6 items.
// #define CIR_VLOCK           4   // View Lock (g_viewLockEnabled; old TF-lock is keyboard-only now)
// TH3TOOL-ON (2026-09-19): restored from TH3TOOL-OFF (slot 5 was vacant).
#define CIR_TH3             5   // TH3 Tool / movement step
#define CIR_HTF             6   // HTF Candles
#define CIR_TOOLS           7   // Tools sub-menu
#define CIR_LEG             11  // Leg Measure tool (trendline 2-click, pips/ATR/TF info)

// Tools half-circle
#define CIR_PIN             8   // Custom Price Pin
#define CIR_STEP_OVERRIDE   9   // Step Mode Override
// FACTORBTN-OFF: #define CIR_FACTOR_OVERRIDE 10  // Factor Override button retired (settings live in the Step card now)
#define CIR_BASEKNOT        10  // Base / Knot Measurement Tool (drag-draw or 2-click box + Entry/SL/TP).
                                // P-UI-95: a MAIN-RING item now — never behind the Tools ladder
#define CIR_GENERAL         14  // P-UI-131 — General Settings card. Its code IS its panel
                                // index (FeaturePanel's identity fallback), and 13 is the mini
                                // STRIP (no rows), so 14 is the first free slot that can own one
#define CIR_HRAY            15  // P-HR-01 — Horizontal Ray (Tools cell: arm → 1 click places)
#define CIR_PATH            16  // Path tool (Tools cell: arm → click per vertex, dbl-click commits)
//--- ring layout (main circle — 8 items; Zones first = the main feature)
// TH3TOOL-ON (2026-09-19): RING_TH3 comes back APPENDED (slot 7), never in the
// middle — HTF/TOOLS/BASEKNOT keep the numbers they were renumbered to when
// TH3TOOL-OFF removed it, and every persisted state key keeps its meaning.
// VIEWLOCK-OFF: RING_VLOCK slot retired (was 4) — HTF/TOOLS shifted down again.
// P-UI-95 (2026-09-16, user: «ایتم اندازه گیری بیس رو بیار توی منوی اصلی»): THE
// MEASURING TOOL IS A MAIN-RING ITEM. It was TOOL_BASEKNOT — the third cell of the
// Tools sub-menu, behind one more click than the features it measures those levels
// for. It is APPENDED (`RING_BASEKNOT`), so no existing slot moves and every
// persisted state key keeps its meaning.
// The item needs NO new machinery: it has no on/off state of its own (the light is
// `BaseKnotSessionActive`, the same query every momentary item uses), a PRESS arms
// the draw session through the ONE arm path (`CircArmBaseKnot`) and a HOLD opens the
// Base Box card (`FeaturePanel`) — both of which the Tools cell already ran.
// Seven items need r >= (44 + 6) / 2 / sin(180/7) = 57.6 px to keep their pitch; the
// shipped CIRC_RADIUS is 64, so the default look clears it with 6.4 px to spare — and
// a menu dragged near an edge collapses to the rail at CIRC_EDGE_TRIGGER anyway.
// RING_LEG appended as slot 8 — no existing slot moves.
// Nine items: min-r = (44+6)/2 / sin(π/9) = 73.1 px → CIRC_RADIUS raised to 80.
#define RING_COUNT 9
#define CIRC_ITEM_COUNT RING_COUNT  // alias for legacy code
#define RING_ZONES    0
#define RING_TRIGGER  1
#define RING_ATR      2
#define RING_TH       3
// VIEWLOCK-OFF: #define RING_VLOCK    4
#define RING_HTF      4
#define RING_TOOLS    5
#define RING_BASEKNOT 6   // P-UI-95: the MEASURING tool — click arms, hold = Base Box card
#define RING_TH3      7   // TH3TOOL-ON (2026-09-19): the TH3 tool / frequency — APPENDED, so no slot moves
#define RING_LEG      8   // Leg Measure — APPENDED, so no existing slot moves

//--- Tools sub-menu (sub-menu under Tools) — SCALABLE LADDER
// FACTORBTN-OFF: Factor button retired (was 2) — its settings live inline in
// the Step Mode card now.
// UIBK-OFF (P-UI-95): Base/Knot was the cell at 2 (click = draw, hold = Base Box
// style card); the MEASURING tool is a MAIN-RING item now (RING_BASEKNOT), so the
// ladder is back to two cells. Restore it by counting 3 back into TOOL_COUNT and
// uncommenting the three sites marked UIBK-OFF (the define, ToolFeature's line and
// the click branch in HandleButtonClick) — the layout needs no change, because
// TOOL_COUNT is the only number it reads.
// Add new tools here AND to ToolFeature()/ToolPanel()/CircIconRes(); TOOL_COUNT
// is the only number the layout reads — it picks its own geometry from it.
#define TOOL_COUNT 5
#define TOOL_PIN              0
#define TOOL_STEP_OVERRIDE    1
#define TOOL_GENERAL          2   // P-UI-131 — the cross-card settings door (a gear)
#define TOOL_HRAY             3   // P-HR-01 — Horizontal Ray (arm → 1 click places, APPENDED so no slot moves)
#define TOOL_PATH             4   // Path tool (arm → vertex clicks, double-click commits, APPENDED)
// UIBK-OFF: #define TOOL_BASEKNOT         2
// FACTORBTN-OFF: #define TOOL_FACTOR_OVERRIDE  2

// R-SUBLADDER (2026-09-11): the sub-menu picks its geometry from TOOL_COUNT so
// that adding a tool can never make two buttons collide. The 6 main-ring items
// are HIDDEN while the sub-menu is open (CreateToolsMenu), so the orb is the
// only other thing on screen — the arc maths is measured from the MENU CENTRE,
// never from the Tools button, so the button can never push an item into a ring
// item. Proven by tools/submenu_geometry_check.js (720 cases: 4 chart sizes x
// 9 menu positions x counts 1..20 — no collision, no orb overlap, nothing
// off-chart).
//   count 1..6  -> FAN   180 deg arc, r = min(112, fit), floor = chord radius
//   count 7..8  -> RING  full 360 deg, r = 100
//   count 9+    -> GRID  4-column panel beside the orb; PAGES when the live
//                        chart cannot show every cell at once
// Near a chart edge the arc collapses to a straight TRAIN mirrored to the side
// with the most room (the ring's own rail rule) — and if even the train cannot
// fit, the layout ESCALATES to the grid panel. The radius is NEVER shrunk below
// the chord radius: that was P-UI-13's failure mode (items stacked on one line).
#define SUB_FAN_MAX      6      // <= this many tools -> 180 deg arc
#define SUB_RING_MAX     8      // <= this many tools -> full ring
// Grid metrics — MUST equal the SUB_* constants in tools/gen-th3-icons.js, or
// the cell art stops lining up with the panel art. Cell canvas == pitch on
// purpose: adjacent canvases abut with ZERO overlap, so an ON cell's glow can
// never wash onto its neighbour (a larger canvas made the winner depend on
// object Z-order, i.e. it flickered).
#define SUB_CELL_VIS     40     // visible rounded square (the .tcell)
#define SUB_CELL_GAP     6      // gap between two cells (.cells gap)
#define SUB_CELL_MARG    3      // baked glow/shadow margin inside cell_*.bmp
#define SUB_CELL_CANVAS  (SUB_CELL_VIS + 2 * SUB_CELL_MARG)   // 46 — the BMP side
#define SUB_GRID_COLS    4      // fixed: 4 columns, exactly like the preview
#define SUB_GRID_PAD     10     // panel padding around the cell block
#define SUB_GRID_HDR     28     // header strip (accent dot + TOOLS + count)
#define SUB_GRID_PGR     24     // pager strip (paged panels only)
// P-UI-34: the sub-menu captions' NOMINAL (design) point sizes. The readout x below is
// MEASURED with PnlTextW instead of the old `5 * StringLen` guess.
#define SUB_PT_READOUT   8      // header count + "page/total"
#define SUB_PT_PAGER     10     // the < > chevrons
#define SUB_GRID_PITCH   (SUB_CELL_VIS + SUB_CELL_GAP)        // 46 — == canvas
#define SUB_PANEL_MARG   12     // baked shadow margin inside sub_panel_*.bmp
#define SUB_PAGE_ROWS    4      // MAX visible rows; a short chart drops lower
// The page size is NOT a compile-time constant: SubPageSize() derives it from
// the LIVE chart so paging turns on at whatever this chart can really show,
// instead of a fixed 16 that would push rows past the bottom edge.
#define SUB_MIN_GAP      CIRC_GAP   // one gap language (the rail pitch uses CIRC_GAP too)
#define SUB_RING_RADIUS  100
#define SUB_ORB_GAP      10     // px between the orb edge and the grid panel
// TOOL_RADIUS / TOOL_SPREAD keep their names: they are the FAN's target geometry.
#define TOOL_RADIUS 112
#define TOOL_SPREAD 180.0
#define TOOL_GAP    SUB_MIN_GAP

// Sub-menu geometry modes. UI-local enum (no external consumer) — declared here
// so every layout function below can use it (MQL4 is one translation unit).
enum ENUM_SUB_MODE
{
   SUB_MODE_FAN = 0,    // 180 deg arc around the menu centre
   SUB_MODE_RAIL,       // straight train near a chart edge
   SUB_MODE_RING,       // full 360 deg ring
   SUB_MODE_GRID,       // 4-column panel beside the orb
   SUB_MODE_GRID_PAGED  // same panel, paged
};

//--- palette (glass-like dark buttons; skins carry the visuals, buttons are hit areas)
#define CLR_CIRC_BG_OFF     clrNONE
#define CLR_CIRC_BORDER_OFF clrNONE
#define CLR_CIRC_BG_ON      clrNONE
#define CLR_CIRC_BORDER_ON  clrNONE
#define CLR_CIRC_ORB_BG     clrNONE
#define CLR_CIRC_ORB_BORDER clrNONE
#define CLR_CIRC_ORB_TXT    C'255,200,60'
// P-UI-69c: the ink BEHIND the orb's baked skin (`orb_bg.bmp`). It was a bare
// `C'30,22,10'` at the OBJPROP_BGCOLOR call site — a literal at a call site is
// what the owner law forbids: invisible to every reader and to every audit.
// Deliberately NOT `CLR_CIRC_ORB_BG` above (that one is the BUTTON's face,
// clrNONE, because the skin carries the look): two roles, two names. The first
// cut of this fix reused the name and the compiler answered `warning 30: macro
// redefinition` — the ladder's own measurement that the name was taken.
#define CLR_CIRC_ORB_SKIN   C'30,22,10'
// P-UI-69c: this IS the brand amber — the palette's own cell 0 (#FFAB00). The
// menu had pasted the value; it now points at the one owner (BIO_CLR_BRAND, the
// same literal BioPal(0) returns), so a palette change can never leave the
// badge behind.
#define CLR_CIRC_BADGE_BG   BIO_CLR_BRAND
#define CLR_CIRC_BADGE_TXT  BIO_CLR_DEEP   // P-UI-117: the shared deep navy, not a
                                            // second literal of the same value

// Refresh flags are owned by BiotakKit.mqh (REFRESH_NONE..REFRESH_ALL).

//+------------------------------------------------------------------+
//| UI State Management (UIState/g_UI/GetGVName live in BiotakKit) |
//+------------------------------------------------------------------+

// Tools sub-panels mapping
//--- WHICH CARD DOES ONE FEATURE OPEN? ONE OWNER for both families (P-UI-95).
// A ring item's card used to be its feature code by IDENTITY, which could only hold
// while no ring item needed a card of its own: the measuring tool opens the Base Box
// style card (12) — the answer the Tools cell always gave, and the reason a HOLD on
// the NEW ring item must not fall through to panel 10 (the retired Factor card).
// With one owner the ring's hold and the (retired) Tools cell's hold can never open
// two different cards, and a future item that needs its own changes THIS function.
// `-1` (an unknown tool index) keeps the callers' own "nothing to open" guard valid.
int FeaturePanel(const int feat)
{
   if(feat == CIR_PIN)           return 8;    // Custom Price Pin card
   if(feat == CIR_STEP_OVERRIDE) return 9;    // Step Mode override card
   // FACTORBTN-OFF: if(feat == CIR_FACTOR_OVERRIDE) return 10; // Factor override card
   if(feat == CIR_BASEKNOT)      return 12;   // Base Box style card (a press still arms drawing)
   return feat;                               // every other feature's card IS its code
}

int RingPanel(const int ringIdx)  { return FeaturePanel(RingFeature(ringIdx)); }
int ToolPanel(const int toolIdx)  { return FeaturePanel(ToolFeature(toolIdx)); }

//--- Ring / Tools mapping helpers (feature indices are stable panel keys)
int RingFeature(const int ringIdx)
{
   switch(ringIdx)
   {
      case RING_ZONES:   return CIR_ZONES;
      case RING_TRIGGER: return CIR_TRIGGER;
      case RING_ATR:     return CIR_ATR;
      case RING_TH:      return CIR_TH;
       // VIEWLOCK-OFF: case RING_VLOCK: return CIR_VLOCK;
       case RING_TH3: return CIR_TH3;   // TH3TOOL-ON (2026-09-19)
       case RING_HTF:     return CIR_HTF;
      case RING_TOOLS:   return CIR_TOOLS;
      case RING_BASEKNOT: return CIR_BASEKNOT;   // P-UI-95: the measure tool's own ring slot
      case RING_LEG:      return CIR_LEG;         // Leg Measure — APPENDED
   }
   return -1;
}

int ToolFeature(const int toolIdx)
{
   if(toolIdx == TOOL_PIN)             return CIR_PIN;
   if(toolIdx == TOOL_STEP_OVERRIDE)   return CIR_STEP_OVERRIDE;
   if(toolIdx == TOOL_GENERAL)         return CIR_GENERAL;   // P-UI-131
   if(toolIdx == TOOL_HRAY)            return CIR_HRAY;      // P-HR-01
   if(toolIdx == TOOL_PATH)            return CIR_PATH;      // Path tool
   // UIBK-OFF (P-UI-95): if(toolIdx == TOOL_BASEKNOT) return CIR_BASEKNOT;
   // FACTORBTN-OFF: if(toolIdx == TOOL_FACTOR_OVERRIDE) return CIR_FACTOR_OVERRIDE;
   return -1;
}

// Tools half-circle state (transient, not persisted)
static bool g_ToolsOpen = false;

//--- real-time orb drag state (CHARTEVENT_MOUSE_MOVE engine)
static bool g_OrbDragging   = false;
static bool g_OrbWasDragged = false;   // suppresses the click that fires after a drag
static bool g_OrbMovedThisEvent = false;
static int  g_OrbGrabDX = 0, g_OrbGrabDY = 0;
static int  g_OrbPressX = 0, g_OrbPressY = 0;
static uint g_OrbLastRedrawTick = 0;

//--- ring item long-press state (hold 500ms → open settings panel)
static int  g_LongPressItem   = -1;     // which item is being held (-1 = none)
static uint g_LongPressStart  = 0;      // GetTickCount when press started
static int  g_LongPressX      = 0;      // mouse X at press start
static int  g_LongPressY      = 0;      // mouse Y at press start
static bool g_LongPressFired  = false;  // true after panel opened (prevents toggle on release)
#define LONG_PRESS_TIME 500   // one hold language everywhere (P-UI-14): 250ms fired on press-pause-drags
#define LONG_PRESS_MOVE 8
#define CIRC_DRAG_REDRAW_INTERVAL 30

//--- chart lock while dragging or while a settings panel is open
//
// P-UI-90: `g_ChartLockCount` counts only MINE (the ring's/panels' own claims),
// exactly as it always did, and the PROPS are no longer saved or restored here
// — that is `ChartViewLock*`'s single job now (see the block note in
// GlobalVariables.mqh: four owners each saved "what the user had", read it while
// another owner held the lock, and the LAST release then wrote OUR false back).
// This layer keeps only what it owns: its own count and the context-menu force.
static int  g_ChartLockCount        = 0;

void CircLockChart()
{
   ChartViewLockAcquire();                    // the props' ONE owner (capture on 0 -> 1)
   if(g_ChartLockCount++ == 0)
      ChartSetInteger(0, CHART_CONTEXT_MENU, false);   // modal: the menu must not steal the press
}

void CircUnlockChart()
{
   if(g_ChartLockCount == 0) return;
   g_ChartLockCount--;
   ChartViewLockRelease();                    // restores only when the LAST owner lets go
}
// Re-assert an owned menu/panel lock (LEARNING §5 rule 2, UI side of
// BaseKnotReassertLock): a one-time CircLockChart is not enough — a third
// writer (BK raw unlock at its gesture end, template/terminal resets) can
// flip the props back mid-drag and the chart pans under the hand. Writes
// only on drift, so steady state costs two reads. Call on every throttled
// move of every gesture (orb / panel-move / slider / mixer).
void CircReassertLock()
{
   if(g_ChartLockCount <= 0) return;
   ChartViewLockAssert();
   if((bool)ChartGetInteger(0, CHART_CONTEXT_MENU))
      ChartSetInteger(0, CHART_CONTEXT_MENU, false);
}

//--- drag arbitration (DRAG_* names shared with the settings panels)
enum DragEngineOwner
{
   DRAG_NONE        = 0,
   DRAG_MENU        = 1,   // orb move / ring-item long-press
   DRAG_PANEL_KNOB  = 3,   // settings-panel slider knob
   DRAG_PANEL_MOVE  = 5    // settings-panel drag-to-move (header grab)
};
static DragEngineOwner g_DragOwner = DRAG_NONE;

bool DragCanGrab(const DragEngineOwner who)
{
   return (g_DragOwner == DRAG_NONE || g_DragOwner == who);
}

void DragClaim(const DragEngineOwner who)
{
   g_DragOwner = who;
}

void DragReleaseIf(const DragEngineOwner who)
{
   if(g_DragOwner == who) g_DragOwner = DRAG_NONE;
}

static bool g_MouseWasDown = false;

// P-UI-65: one press = one sequence number. It is the identity a click claim is
// bound to, so a claim can never be spent on a later, unrelated gesture.
static uint g_UIPressSeq = 0;

bool MousePressStart(const bool leftDown)
{
   const bool pressStart = (leftDown && !g_MouseWasDown);
   g_MouseWasDown = leftDown;
   if(pressStart) g_UIPressSeq++;
   // P-UI-92b: the counter the claim's identity is bound to IS published state,
   // because the domain half of the release has to apply the same "a new press owns
   // the click" rule without reaching into this file's statics. Written on the press
   // EDGE only, through the one publisher, so the mirror can never disagree with the
   // state machine it mirrors — this edge is what retires a stale claim for BOTH
   // halves at the same instant.
   if(pressStart) UIPublishClickClaim();
   return pressStart;
}

//+------------------------------------------------------------------+
// P-UI-65 (2026-09-13) - THE CLICK CLAIM BELONGS TO ONE GESTURE.
//
// `UISuppressNextClick()` means exactly one thing: "the button-up that ends
// THIS gesture is already spent - the release must not act a second time". Its
// identity used to be a wall-clock deadline (`GetTickCount() + 350`), and both
// halves of that were wrong in ways the user feels as flakiness:
//
//  * LEAK - the deadline is armed at PRESS time (nearly every arm site) and the
//    release is the event it must eat. Hold the button longer than the window
//    (press, read, release) and the claim is dead before its own release: the
//    release then runs HandleButtonClick / PnlHandleClick as if nothing had
//    happened, on a control whose press already acted. How long a press takes is
//    the USER's choice, so the failure is random by construction.
//  * OVER-EATING - `UIShouldSuppressClick()` never cleared the deadline, so one
//    release consumed the time test and the REMAINDER of the window ate the
//    NEXT genuine click. "Press close, nothing happens, press again and it
//    works" - and whether it happens depends on how deep into the window the
//    previous release fell. That is the P-UI-01 symptom, and the P-UI-40c note
//    already fixed exactly this shape for the long-press latch; the window
//    around it was left behind.
//
// The fix is the rule the rest of the kit already follows - a latch carries the
// identity of its own gesture and is consumed by it exactly once:
//   * armed while the button is DOWN -> bound to the live press, so its release
//     eats it however long the user holds (no clock at all);
//   * armed while the button is UP   -> the release it belongs to is the event
//     already in flight (an orb/panel drag end, a card opened by a release), so
//     that form keeps a short TTL instead of a press to bind to;
//   * TAKEN once - and then UI_RELEASE_ECHO_MS of echo, because one physical
//     release can be delivered as both CHARTEVENT_CLICK and
//     CHARTEVENT_OBJECT_CLICK and both belong to the same gesture;
//   * a NEW press retires an unconsumed claim, so it can never outlive its
//     gesture and eat a later click.
// Steady state (no claim armed): two flag reads. Zero timers, zero drift.
//+------------------------------------------------------------------+
#define UI_RELEASE_ECHO_MS   80    // window for the same release's second event
#define UI_UP_CLAIM_TTL_MS  350    // a claim armed ON the release (no press to bind)

static bool s_uiClickClaim     = false;
static bool s_uiClickClaimDown = false;  // armed under a live press (bound by seq)
static uint s_uiClickClaimSeq  = 0;      // the press it was armed under
static uint s_uiClickClaimMs   = 0;      // TTL for the up-armed form
static uint s_uiReleaseEchoMs  = 0;      // we already ate this release

//+------------------------------------------------------------------+
// P-UI-92b (2026-09-16) — THE CLAIM'S SINGLE PUBLISHER (the WHOSE half of
// UIPointerOverSurface's WHERE half).
//
// The claim above is this file's private state, and the composer runs the DOMAIN
// half of an event BEFORE this half. So the domain could not ask the only code that
// knows whose release a click is — it read an orb drag's end, a long-press release
// or a panel press-release as a plain chart click. The mirror (GlobalVariables) is
// the published form of the SAME three-part rule, and this function is its ONLY
// writer, called from every transition of the claim (arm, consume, retire-on-new-
// press, echo, reset) plus the press counter's edge.
//
// It recomputes instead of being told: the mirror is derived from the state machine,
// so the two can never drift — the failure mode a hand-maintained flag would bring.
// Cost: four stores on a press/release transition only; nothing on the move path.
//+------------------------------------------------------------------+
void UIPublishClickClaim()
{
   uint nowMs = GetTickCount();
   // The echo: this hand already took this release, and its twin event is in flight.
   if(s_uiReleaseEchoMs != 0 && (int)(nowMs - s_uiReleaseEchoMs) < 0)
   {
      g_uiClickClaimLive = true;
      g_uiClickClaimDown = false;
      g_uiClickClaimSeq  = g_UIPressSeq;
      g_uiClickClaimMs   = s_uiReleaseEchoMs;
      g_uiPressSeq       = g_UIPressSeq;
      return;
   }
   g_uiPressSeq = g_UIPressSeq;              // always current, claimed or not
   if(!s_uiClickClaim)
   {
      g_uiClickClaimLive = false;
      g_uiClickClaimDown = false;
      g_uiClickClaimMs   = 0;
      return;
   }
   g_uiClickClaimLive = true;
   g_uiClickClaimDown = s_uiClickClaimDown;
   g_uiClickClaimSeq  = s_uiClickClaimSeq;
   // Press-bound form: the click it eats is its own release, so the published
   // deadline is only the stuck-claim safety bound (UIPeekClickClaim checks the
   // press identity FIRST, exactly like this file's predicate).
   g_uiClickClaimMs = (s_uiClickClaimDown ? (nowMs + UI_CLAIM_TTL_MS) : s_uiClickClaimMs);
}

void UISuppressNextClick()
{
   s_uiClickClaim     = true;
   s_uiClickClaimDown = g_MouseWasDown;
   s_uiClickClaimSeq  = g_UIPressSeq;
   s_uiClickClaimMs   = GetTickCount() + UI_UP_CLAIM_TTL_MS;
   UIPublishClickClaim();   // P-UI-92b: the domain half of this gesture reads the mirror
}

bool UIShouldSuppressClick()
{
   uint nowMs = GetTickCount();
   // The second event of the release this hand just took - still this gesture's.
   if(s_uiReleaseEchoMs != 0 && (int)(nowMs - s_uiReleaseEchoMs) < 0) return true;
   if(!s_uiClickClaim) return false;
   // A press-time claim dies with ITS press: a new press owns the click.
   if(s_uiClickClaimDown && s_uiClickClaimSeq != g_UIPressSeq)
   {
      s_uiClickClaim = false;
      return false;
   }
   // An up-armed claim has no press to bind to, so it keeps its short TTL.
   if(!s_uiClickClaimDown && (int)(nowMs - s_uiClickClaimMs) >= 0)
   {
      s_uiClickClaim = false;
      return false;
   }
   s_uiClickClaim    = false;                    // consumed by its own release, once
   s_uiReleaseEchoMs = nowMs + UI_RELEASE_ECHO_MS;
   // P-UI-92b: published AFTER the state moved, so the domain half of the very same
   // event (which ran first and only PEEKED) gets one consistent story: it was either
   // told the press was the UI's before this release, or it is told now that this
   // release's twin event is the UI's too. The early returns above change NOTHING in
   // the state machine — their mirror was already published correctly by the last
   // transition (the press edge re-publishes the counter, the expiry is a deadline the
   // reader applies itself) — so no branch can leave the mirror ahead of or behind the
   // claim it mirrors.
   UIPublishClickClaim();
   return true;
}

// Attach / timeframe switch: none of the claim state may cross an instance - a
// claim, an echo or a press counter left armed would eat the first click of the
// next instance (the ResetHideAllState rule). Called from the one UI entry point
// every attach runs (CreateMenu). Two fences, both of them one bool read, so a
// menu re-created during a click can never change that click's outcome:
//   * never under a live press - a down-armed claim is still owed its release;
//   * never mid-release - the twin event of the release this hand just took is
//     still in flight (the echo window), and CreateMenu is reachable from
//     HandleButtonClick, i.e. inside that very dispatch.
void UIReleaseClaimReset()
{
   if(g_MouseWasDown) return;
   if(s_uiReleaseEchoMs != 0 && (int)(GetTickCount() - s_uiReleaseEchoMs) < 0) return;
   s_uiClickClaim     = false;
   s_uiClickClaimDown = false;
   s_uiClickClaimSeq  = 0;
   s_uiClickClaimMs   = 0;
   s_uiReleaseEchoMs  = 0;
   g_UIPressSeq       = 0;
   UIPublishClickClaim();   // P-UI-92b: the mirror is part of the claim state
}

//+------------------------------------------------------------------+
// P-UI-40c (2026-09-13) - THE LONG-PRESS LATCH BELONGS TO ONE GESTURE.
//
// `g_LongPressFired` has exactly one job: the release-click of a hold that
// ALREADY opened a card must not also toggle the item under the cursor. It was
// only ever cleared in two places - the arming pass (a fresh press on an item)
// and the two `if(g_LongPressFired)` guards in HandleButtonClick.
//
// The suppressed release paths skip those guards entirely: on the button-up the
// menu calls UISuppressNextClick() again, and both `if(UIShouldSuppressClick())
// return;` sites in BiotakPanels leave BEFORE HandleButtonClick. So a hold whose
// release landed inside the suppression window left the latch SET, and the next
// click that reached HandleButtonClick without an arming pass first was eaten -
// that is precisely a click with NO mouse movement, and MT4 emits no
// CHARTEVENT_MOUSE_MOVE for a motionless press (same trap as P-BK-03). The
// symptom is the P-UI-01 one: "sometimes the first press on a control does
// nothing".
//
// The suppression window has already classified that release as "this gesture's,
// and already acted on" - so clearing the latch there is the SAME decision,
// taken once, instead of a latch that outlives its gesture. The late-release
// case is untouched: a click arriving after the window still meets the guards,
// which is the only place the latch is genuinely needed. One owner, two plain
// writes, and it runs only on the suppressed return - zero steady-state cost.
//+------------------------------------------------------------------+
void UILongPressLatchClear()
{
   g_LongPressFired = false;
   g_LongPressItem  = -1;
}

//+------------------------------------------------------------------+
//| Ring item under the cursor (-1 = none).                          |
//+------------------------------------------------------------------+
int CircItemAt(const int mx, const int my)
{
   if(g_ToolsOpen) return -1;   // the ring is hidden while the Tools fan is open
   for(int i = 0; i < RING_COUNT; i++)
   {
      int ix, iy;
      CircLayout(i, ix, iy);
      int bx = ix - CIRC_BTN_SIZE / 2;
      int by = iy - CIRC_BTN_SIZE / 2;
      if(mx >= bx - CIRC_BG_MARGIN && mx <= bx + CIRC_BTN_SIZE + CIRC_BG_MARGIN &&
         my >= by - CIRC_BG_MARGIN && my <= by + CIRC_BTN_SIZE + CIRC_BG_MARGIN)
         return i;
   }
   return -1;
}

//+------------------------------------------------------------------+
//| P-UI-116 — THE MENU'S OWN PIXELS, ONE TEST.                       |
//|                                                                  |
//| This is the WHERE half of P-UI-92 for the ring: which pixels does |
//| the menu OWN? `UIPointerOverSurface` composes it (BiotakPanels)   |
//| so the domain half reads the menu's own disc as UI and never as a  |
//| chart point — the custom-price pick, the box tool's                |
//| deselect-on-chart-click and the strip's hold latch all ask that    |
//| one function.                                                     |
//|                                                                  |
//| It was written for exactly this question and — measured with       |
//| `git log -S CircPointOnMenu` — had ZERO callers in every commit   |
//| since the day it was born (`UIPointerOverSurface`'s own header     |
//| promised the ring's pixels while its body tested everything but    |
//| them). So the sentence and the code disagreed for as long as the   |
//| claim has existed: a menu the user sees as solid UI was, to the    |
//| domain, free chart.                                               |
//|                                                                  |
//| WHAT IS *NOT* CLAIMED, deliberately: the transparent gaps between  |
//| items and the hole between the orb and the ring. Those pixels are  |
//| not drawn — a click that hits no control IS a chart click, and      |
//| claiming the ring's bounding box would steal a 240px patch of      |
//| chart from the tool (the reason P-BK-02 gates the whole test on     |
//| `g_UI.menuVisible`).                                              |
//+------------------------------------------------------------------+
bool CircPointOnMenu(const int mx, const int my)
{
   int ox = g_UI.menuX - CIRC_ORB_SIZE/2 - CIRC_ORB_BG_MARGIN;
   int oy = g_UI.menuY - CIRC_ORB_SIZE/2 - CIRC_ORB_BG_MARGIN;
   int os = CIRC_ORB_SIZE + 2*CIRC_ORB_BG_MARGIN;
   if(mx >= ox && mx <= ox + os && my >= oy && my <= oy + os) return true;   // the orb (with its glow)
   if(CircItemAt(mx, my) >= 0) return true;                       // every ring item's own box
   if(ToolsItemAt(mx, my) >= 0) return true;                      // fan / rail / grid tiles
   // P-UI-116: the grid panel's PLATE — header strip, padding and the pager
   // arrows ride it (`SubPagerGeom` places them inside this rect). The card is
   // the precedent: a plate is a surface, so its whole rect is claimed, not only
   // the controls sitting on it. The pager's clicks are routed BY OBJECT NAME in
   // the click handler, but a click that lands on the plate must still never
   // reach the chart.
   if(g_ToolsOpen && SubIsPanelMode())
   {
      int px = 0, py = 0, pw = 0, ph = 0;
      SubPanelRect(px, py, pw, ph);
      if(mx >= px && mx <= px + pw && my >= py && my <= py + ph) return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Circular menu object names                                       |
//+------------------------------------------------------------------+
string CircOrbBg()        { return g_UI.btnPrefix + "CircOrbBg"; }
// ORBSTATE: the orb is the menu's own button, so it reports the menu's state —
// ORBWORD-OFF (2026-09-12, user decision): open keeps the bow medallion too,
// the "TRex" wordmark swap is retired (text over the bow read as mud).
// ICON-DIET 2026-09-27: the word branch is deleted rather than commented —
// keeping a dead #resource for it cost 20 KB in every .ex4. Restoring the
// wordmark is a re-add: make-orb-word.ps1 → the generator → the #resource.
string CircOrbRes()
{
   return "::Files\\Icons\\orb_bg.bmp";
}
// Re-point the orb's bitmap. Called from CreateMenu() so EVERY open/close path
// (orb click, long-press card, Base Knot arm/disarm, init) lands on the right
// skin without each caller having to remember. Setting OBJPROP_BMPFILE forces a
// decode (P-PERF-01), which is why this sits on the state change and not in
// OnCalculate.
// P-PERF-51 (2026-09-25): and the write is now CHANGE-GUARDED. ORBSTATE is
// retired (one skin), so a toggle wrote the same resource twice and paid a
// decode for a picture that did not change — read back, compare, write only on
// a real swap. One owner, so every caller gets the guard.
void CircRefreshOrbSkin()
{
   string orbBg = CircOrbBg();
   if(ObjectFind(0, orbBg) < 0) return;
   string res = CircOrbRes();
   if(ObjectGetString(0, orbBg, OBJPROP_BMPFILE, 0) == res) return;
   ObjectSetString(0, orbBg, OBJPROP_BMPFILE, 0, res);
   ObjectSetString(0, orbBg, OBJPROP_BMPFILE, 1, res);
}
string CircOrbIcon()      { return g_UI.btnPrefix + "CircOrbIcon"; }
string CircBtn(const int i)      { return g_UI.btnPrefix + "CircBtn" + IntegerToString(i); }
string CircIcon(const int i)     { return g_UI.btnPrefix + "CircIcon" + IntegerToString(i); }
string CircBg(const int i)        { return g_UI.btnPrefix + "CircBg" + IntegerToString(i); }
string CircBadgeBg(const int i)  { return g_UI.btnPrefix + "CircBadge" + IntegerToString(i); }
string CircBadgeTxt(const int i) { return g_UI.btnPrefix + "CircBadgeTxt" + IntegerToString(i); }

#define UI_STATE_VERSION 12   // P-UI-118 (2026-09-25): 11 -> 12 — the orb's default home is
                              // the chart's CENTRE now, and this is the project's own way to
                              // apply a new UI default: a version mismatch clears the saved
                              // BIOMENU_* block once and re-seeds from CircDefaultMenuPos.

//+------------------------------------------------------------------+
//| P-UI-118 — THE ORB'S DEFAULT HOME IS THE CHART'S CENTRE, ONE OWNER.|
//|                                                                  |
//| User order 2026-09-25: «منو وسط باز بشه از هر طرف» — the menu must |
//| open as a RING, fanning from every side. `CircLayout` leaves the   |
//| arc the moment the orb is within `CIRC_EDGE_TRIGGER` (90 px) of    |
//| any edge and collapses the ring into a train along it — which is   |
//| exactly what a corner-parked orb does, and what the Tools          |
//| sub-menu escalates away from (fan -> rail -> grid). The centre is  |
//| the ONLY position where every layout family is reachable as         |
//| designed, so it is the default.                                    |
//|                                                                  |
//| BOTH readers ask here — the first-attach default and the fallback  |
//| when a saved position is missing — so the two can never disagree    |
//| about where "default" is. A SAVED position still wins: the user's   |
//| drag is the truth, and only a chart with no stored pair lands here. |
//| The value is clamped like every other orb write on the next pass.   |
//+------------------------------------------------------------------+
void CircDefaultMenuPos(int &x, int &y)
{
   int cw = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS, 0);
   int ch = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS, 0);
   if(cw <= 0) cw = 1920;
   if(ch <= 0) ch = 1080;
   x = cw / 2;
   y = ch / 2;
}

//--- P-UI-131e — A HOME THAT OUTLIVES THE CHART AND THE SYMBOL. User order: «در هر چارت
//--- در هر شرایط همون جا باشه، بدون هزینه». A placed surface is the HAND's preference,
//--- not a fact of one window: the keys still carried ChartID(), and a CLAMP was saved
//--- back into the live pair (so one narrow chart ratcheted the place for good). A home
//--- lives under a key with no chart and no symbol in it; the value that paints is never
//--- the value stored; cost is one read at load and one write when the hand really moves.
string GVHomeName(const string id,const bool y) { return "BIOMENU_HOME_" + id + (y ? "Y" : "X"); }

//--- one home, three readers (the orb, the strip, the chip): the chart-free pair first,
//--- then the pre-131e per-chart pair it replaced, so the upgrade keeps the place the
//--- hand already chose instead of re-seeding the default. Absent both = no home.
bool GVHomeLoad(const string id,const string legacyInfix,int &x,int &y)
{
   string nx = GVHomeName(id,false), ny = GVHomeName(id,true);
   if(GlobalVariableCheck(nx) && GlobalVariableCheck(ny))
   {
      x = (int)GlobalVariableGet(nx); y = (int)GlobalVariableGet(ny);
      if(x >= 0 && y >= 0) return true;
   }
   string lx = GetGVName(legacyInfix + "X"), ly = GetGVName(legacyInfix + "Y");
   if(GlobalVariableCheck(lx) && GlobalVariableCheck(ly))
   {
      x = (int)GlobalVariableGet(lx); y = (int)GlobalVariableGet(ly);
      if(x >= 0 && y >= 0) return true;
   }
   x = -1; y = -1;
   return false;
}

//--- the orb's own home. -1 = the hand has never placed it: CircDefaultMenuPos answers.
static int s_OrbHomeX = -1, s_OrbHomeY = -1;
bool CircOrbHomeGet(int &x,int &y)
{
   x = s_OrbHomeX; y = s_OrbHomeY;
   return (s_OrbHomeX >= 0 && s_OrbHomeY >= 0);
}
void CircOrbHomeSet(const int x,const int y) { s_OrbHomeX = x; s_OrbHomeY = y; }

//--- P-UI-126: THE CHIP'S OWN PLACE — P-DRAW-41's home, one surface over, and owned
//--- here because the UI-state block below is its only reader and writer. (-1,-1) =
//--- the hand has never placed it: the chart's middle then answers, measured LIVE so a
//--- resized chart is never stuck with a stale centre. Stored as the BOX's centre.
static int s_TipHomeX = -1, s_TipHomeY = -1;
bool CircTipHomeGet(int &x, int &y)
{
   x = s_TipHomeX; y = s_TipHomeY;
   return (s_TipHomeX >= 0 && s_TipHomeY >= 0);
}
void CircTipHomeSet(const int x, const int y) { s_TipHomeX = x; s_TipHomeY = y; }

void ResetUIToDefaults()
{
   // P-UI-131e: FLAGS ONLY. The placements have their own owner now (`LoadUIPlaces`) and a
   // home is chart-free, so this reset — which fires per symbol — must never move a surface
   // on every chart, and the orb's live pair must not be re-derived behind the loader's back.
   g_UI.menuVisible = true;
   g_UI.showHTF = false;
   g_UI.tipPin = false;   // P-UI-126: the chip's default MODE is hover; its place is not this
}

//--- P-UI-131e — WHERE THE THREE PLACEABLE SURFACES STAND, one owner for both init paths.
//--- Called BEFORE the version branch: a version reset is about the saved FORMAT, and it
//--- must not silently re-home a surface (it used to, and it also saved the wipe back).
void LoadUIPlaces()
{
   //--- the orb: its chart-free home, else the chart's centre. A migrated legacy value that
   //--- is STILL this chart's centre means the hand never moved it (every chart's first
   //--- init wrote that pair) — adopting it as an absolute home would off-centre the orb
   //--- on a chart of another size.
   int defX = 0, defY = 0;
   CircDefaultMenuPos(defX, defY);               // P-UI-118: the ONE answer to "default"
   int ohx = -1, ohy = -1;
   bool haveOrbHome = GVHomeLoad("ORB", "MENU", ohx, ohy);
   if(haveOrbHome && ohx == defX && ohy == defY) haveOrbHome = false;
   if(haveOrbHome) CircOrbHomeSet(ohx, ohy);     // the home outlives the SESSION, not the reset
   g_UI.menuX = haveOrbHome ? ohx : defX;
   g_UI.menuY = haveOrbHome ? ohy : defY;
   //--- P-DRAW-41: THE STRIP'S HOME — the plate comes back where it was left, instead of
   //--- being re-placed beside the drawing on every attach (the placement that put it on
   //--- the user's own work). Absent key = no home: the first open measures one.
   int hx = -1, hy = -1;
   GVHomeLoad("STRIP", "HOME", hx, hy);
   DrawStripHomeSet(hx, hy);
   //--- P-UI-126: the chip's own place. An absent pair means the hand has never placed it —
   //--- a state, not a reset: a fresh chart starts in hover mode with no place of its own.
   int tx = -1, ty = -1;
   if(GVHomeLoad("CHIP", "TIP", tx, ty)) CircTipHomeSet(tx, ty);
}

void LoadUIState()
{
   string gvMen   = GetGVName("MEN");
   string gvHtf   = GetGVName("HTF_EN");

   g_UI.menuVisible = GlobalVariableCheck(gvMen)   ? (GlobalVariableGet(gvMen)   > 0.5) : true;
   g_UI.showHTF     = GlobalVariableCheck(gvHtf)   ? (GlobalVariableGet(gvHtf)   > 0.5) : false;
   if(GlobalVariableCheck(GetGVName("TIPPIN")))
      g_UI.tipPin = (GlobalVariableGet(GetGVName("TIPPIN")) > 0.5);
   // P-DRAW-89: the plate's transparency setting is retired. Its GV is swept on
   // attach below so a chart that carried the old key cannot resurrect the look.
   GlobalVariableDel(GetGVName("PLATE"));
}

void DeleteLegacyMenuObjects()
{
   string legacy = "BiotakMenu_" + IntegerToString(ChartID()) + "_";
   for(int i = 0; i < RING_COUNT; i++)
   {
      ObjectDelete(0, legacy + "CircIcon" + IntegerToString(i));
      ObjectDelete(0, legacy + "CircBg" + IntegerToString(i));
      ObjectDelete(0, legacy + "CircBadge" + IntegerToString(i));
      ObjectDelete(0, legacy + "CircBadgeTxt" + IntegerToString(i));
   }
   for(int t = 0; t < TOOL_COUNT; t++)
   {
      ObjectDelete(0, legacy + "ToolsBg" + IntegerToString(t));
      ObjectDelete(0, legacy + "ToolsIcon" + IntegerToString(t));
      ObjectDelete(0, legacy + "ToolsBadge" + IntegerToString(t));
      ObjectDelete(0, legacy + "ToolsBadgeTxt" + IntegerToString(t));
   }
   ObjectDelete(0, legacy + "CircOrbBg");
   ObjectDelete(0, legacy + "CircOrbIcon");
}

//--- P-UI-131e — THE ONE LEGACY READ. A pre-131e build keyed this block by _Symbol AND
//--- ChartID(); without this, the upgrade itself looks like the bug it fixes (nothing
//--- found -> defaults -> the trigger moves once, and the card overrides it could not see
//--- would re-seed from the dialog inputs). It copies EVERY slot of the legacy block,
//--- not a list of names, so the `OV_`/`PNLP` families survive the prefix change too.
//--- One walk of the terminal's table, only while the new block is absent, never per
//--- tick. The legacy keys stay where they are: a rollback still finds its own place.
void MigrateLegacyUIState()
{
   if(GlobalVariableCheck(GetGVName("VER"))) return;         // the new block is here
   const string head = "BIOMENU_" + _Symbol + "_";
   const int    hl = StringLen(head);
   string legacy = "";
   for(int i = GlobalVariablesTotal() - 1; i >= 0 && legacy == ""; i--)
   {
      string n = GlobalVariableName(i);
      if(StringLen(n) < hl + 5 || StringSubstr(n, 0, hl) != head) continue;
      int k = hl, digits = 0;
      while(k < StringLen(n)
            && StringGetCharacter(n, k) >= '0' && StringGetCharacter(n, k) <= '9')
         { k++; digits++; }
      if(digits <= 0 || digits > 10) continue;
      if(k >= StringLen(n) || StringGetCharacter(n, k) != '_') continue;
      legacy = StringSubstr(n, 0, k + 1);                    // "BIOMENU_XAUUSD_131074_"
   }
   if(legacy == "") return;
   // collect FIRST: GlobalVariableSet re-shapes the table this walk is reading
   string slots[64];
   int n = 0, ll = StringLen(legacy);
   for(int i = GlobalVariablesTotal() - 1; i >= 0; i--)
   {
      string nm = GlobalVariableName(i);
      if(StringLen(nm) <= ll || StringSubstr(nm, 0, ll) != legacy) continue;
      if(n >= 64) break;                                     // a block is tens of keys
      slots[n++] = StringSubstr(nm, ll);
   }
   for(int s = 0; s < n; s++)
   {
      string nk = GetGVName(slots[s]);
      if(!GlobalVariableCheck(nk)) GlobalVariableSet(nk, GlobalVariableGet(legacy + slots[s]));
   }
}

void InitializeUIStates()
{
   DeleteLegacyMenuObjects();
   g_UI.btnPrefix = "BiotakMenuV2_" + IntegerToString(ChartID()) + "_";
   // P-UI-131e: the KEY carries the SYMBOL, never the chart id. A chart id is handed out
   // per session and per window, so after a terminal restart (or in a freshly opened
   // chart) every key was absent: the version check failed, the whole block was wiped
   // and re-seeded from the defaults — the user's «اندیکاتور خاموش و روشن میکنی …
   // جاش عوض میشه». Per symbol: durable across restarts, shared by that symbol's windows.
   g_UI.gvPrefix = "BIOMENU_" + _Symbol + "_";
   RuntimeSettingsSetPersistPrefix(g_UI.gvPrefix);   // OV_ overrides saved under this prefix
   MigrateLegacyUIState();   // P-UI-131e: adopt a pre-131e per-chart block, once

   // Orphan purge: panel/palette objects survive a TF-switch (chart objects
   // are NOT deleted on REASON_CHARTCHANGE) while our open-state statics
   // reset — without this a dead, unresponsive panel haunts the chart.
   // Runs once per init; steady state untouched.
   ObjectsDeleteAll(0, g_UI.btnPrefix + "Pnl");
   ObjectsDeleteAll(0, g_UI.btnPrefix + "Pal_");
   // The sub-menu panel (backdrop, header, pager, dots) shares the same fate: it
   // survives a TF switch (chart objects are NOT deleted on REASON_CHARTCHANGE)
   // while g_ToolsOpen resets to false, leaving an orphan panel that no longer
   // answers anything. One sweep, once per init.
   ObjectsDeleteAll(0, g_UI.btnPrefix + "Sub");

   bool versionOk = false;
   if(GlobalVariableCheck(GetGVName("VER")))
   {
      double ver = GlobalVariableGet(GetGVName("VER"));
      versionOk = ((int)ver == UI_STATE_VERSION);
   }

   LoadUIPlaces();   // P-UI-131e: the homes first — the reset branch below must not lose them
   if(versionOk && GlobalVariableCheck(GetGVName("INIT")))
   {
      LoadUIState();
      PrimeUIStatesShadow();   // P-PERF-44: what the load read is on disk
   }
   else
   {
      ClearAllGVs();
      ResetUIToDefaults();
      SaveUIStates(true);
   }
}

void ClearAllGVs()
{
   const string pfx = g_UI.gvPrefix;
   const int    len = StringLen(pfx);
   if(len == 0) return;   // never sweep with an unset prefix (would hit every GV)
   for(int i = GlobalVariablesTotal() - 1; i >= 0; i--)
   {
      const string name = GlobalVariableName(i);
      if(StringLen(name) >= len && StringSubstr(name, 0, len) == pfx)
         GlobalVariableDel(name);
   }
   // P-PERF-27c: every write-shadow that claims these keys exist is now wrong.
   // Without this, the version-reset path (ClearAllGVs -> ResetUIToDefaults ->
   // SaveUIStates) and any later save would compare against deleted keys and
   // skip the writes that put them back.
   GVShadowsInvalidate();
}

void SaveUIStates(const bool flushNow = false)
{
   // P-PERF-27c: these keys only change when the menu is shown, moved, the HTF
   // toggle flips or the strip's home moves — yet a timeframe switch flushed the
   // terminal's WHOLE global-variable table for them every time. Guard them the same
   // way the override pass is guarded: unchanged values cost zero writes, no flush.
   static double s_uiShadow[13];
   static bool   s_uiKnown[13];
   static int    s_uiEpoch = -1;
   int uiChanged = 0;
   // P-PERF-44: PER KEY. The old pass wrote all six keys whenever ONE of them
   // moved, which is the same "re-assert for safety" that R-PERF bans - and it
   // made this block's own report a guess instead of a count.
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 0, UI_STATE_VERSION))
      { GlobalVariableSet(GetGVName("VER"), UI_STATE_VERSION); uiChanged++; }
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 1, 1.0))
      { GlobalVariableSet(GetGVName("INIT"), 1.0); uiChanged++; }
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 2, g_UI.menuVisible ? 1.0 : 0.0))
      { GlobalVariableSet(GetGVName("MEN"), g_UI.menuVisible ? 1.0 : 0.0); uiChanged++; }
   // P-UI-131e: the orb's HOME is what is written, not `g_UI.menuX/menuY`. Those are the
   // live pair and every create/update CLAMPS them (a smaller chart, a tighter band), so
   // saving them ratcheted the place inward for good. The key is chart-free too.
   int ohx = 0, ohy = 0;
   const bool haveOrbHome = CircOrbHomeGet(ohx, ohy);
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 3, haveOrbHome ? (double)ohx : -1.0))
      { GlobalVariableSet(GVHomeName("ORB",false), haveOrbHome ? (double)ohx : -1.0); uiChanged++; }
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 4, haveOrbHome ? (double)ohy : -1.0))
      { GlobalVariableSet(GVHomeName("ORB",true), haveOrbHome ? (double)ohy : -1.0); uiChanged++; }
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 5, g_UI.showHTF ? 1.0 : 0.0))
      { GlobalVariableSet(GetGVName("HTF_EN"), g_UI.showHTF ? 1.0 : 0.0); uiChanged++; }
   // P-DRAW-41 (2026-09-25): the strip's home is a user position like the menu
   // orb's, so it is stored with the same keys and under the same guards — one pair,
   // written only when the hand really moved it. No version bump: a chart whose
   // keys are missing simply has no home yet and its first open measures one.
   int hx = 0, hy = 0;
   const bool haveHome = DrawStripHomeGet(hx, hy);
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 6, haveHome ? (double)hx : -1.0))
      { GlobalVariableSet(GVHomeName("STRIP",false), haveHome ? (double)hx : -1.0); uiChanged++; }
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 7, haveHome ? (double)hy : -1.0))
      { GlobalVariableSet(GVHomeName("STRIP",true), haveHome ? (double)hy : -1.0); uiChanged++; }
   // P-DRAW-89: the plate's transparency writer is gone with the setting; slot 8
   // of the shadow set is free again.
   // P-UI-126: the chip's own place and mode — the hand's answers, written only when
   // they really moved (the drag's release and the card's switch are the whole set).
   int thx = 0, thy = 0;
   const bool haveTipHome = CircTipHomeGet(thx, thy);
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 9, haveTipHome ? (double)thx : -1.0))
      { GlobalVariableSet(GVHomeName("CHIP",false), haveTipHome ? (double)thx : -1.0); uiChanged++; }
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 10, haveTipHome ? (double)thy : -1.0))
      { GlobalVariableSet(GVHomeName("CHIP",true), haveTipHome ? (double)thy : -1.0); uiChanged++; }
   if(GVSlotChanged(s_uiEpoch, s_uiKnown, s_uiShadow, 11, g_UI.tipPin ? 1.0 : 0.0))
      { GlobalVariableSet(GetGVName("TIPPIN"), g_UI.tipPin ? 1.0 : 0.0); uiChanged++; }
   // P-PERF-44 (3): report BEFORE the early return. A skip count that survives a
   // no-op pass would describe a teardown that already happened.
   GVLedgerReport(GV_BLOCK_UI, uiChanged, 12);
   // Nothing changed: no writes. No flush either - there is nothing new to make
   // durable, and the keys themselves stay in the terminal's table regardless
   // (GlobalVariablesFlush only forces the DISK copy, which the terminal also
   // writes on shutdown).
   if(uiChanged == 0) return;
   // P-PERF-44 (2): `flushNow` means "these keys must be DURABLE when this call
   // returns", and every caller on that path (the version reset, the teardown)
   // sits outside any other flush transaction - so it asks AND commits. The
   // plain saves only ask, and the one commit pays for all of them.
   if(flushNow) { GVFlushRequest(); GVFlushCommit(); }
}

// P-PERF-44 (1): prime this block from its own LOAD pass. LoadUIState() has just
// read these six keys, so replaying this write order in dry-run teaches the
// shadow "this is already on disk" - the rule P-PERF-27b applied to the override
// table, which was the ONE block that had it (and the reason `save=125ms` could
// not be attributed: this saver recorded its first value in the teardown it cost).
void PrimeUIStatesShadow()
{
   if(StringLen(g_UI.gvPrefix) == 0) return;   // UI never initialized
   GVShadowDryRun(true);
   SaveUIStates(false);
   GVShadowDryRun(false);
}

//+------------------------------------------------------------------+
// P-PERF-41 - ONE SWITCH PER ITEM, AND NO CROSS-EFFECTS
//
// The ring item sits on the "Zones & Levels" card, and the card has TWO rows
// (0 = MID ZONES, 1 = SHOW LINES) with their own controls. So this item owns
// exactly ONE of them: `g_showMidZones`. It MUST NOT touch the line switch.
//
// That is not a stylistic choice - it was tried and reverted: making the item a
// "master" over both layers meant a press could switch ON a layer the user had
// deliberately switched OFF (zones on + lines off, press, lines are back). A
// control that silently changes a different control's state is a behaviour bug,
// and the fix for "feels unreliable" is never to move more state - it is to move
// the right state reliably. The light, the badge, the tooltip and the click all
// read/write this one flag, so they can never disagree about it.
//+------------------------------------------------------------------+

// P-UI-93 — THE LIGHT ANSWERS THE SAME QUESTION THE CHART DOES.
//
// `CircFeatureOn` below answers the SWITCH's own question: it is the value the
// item owns, and the press inverts it. It must stay that way — the family
// isolation this file is built on (one item, one switch, no cross-effects) is
// only meaningful while the switch owner speaks about one switch.
//
// The F mute is NOT a switch. It is the whole-indicator master that every
// family's writer already shares (`... && !IsIndicatorHidden()`), so a light
// that read the switch alone stayed LIT on a blank chart — the ring and the
// chart disagreeing, which is the report «این دکمه های با پنل هماهنگ نیستش».
//
// So the mute is folded in `CircFeatureLit` below, in the question the LIGHT
// asks, and the four family lights are exactly the four families the F key
// hides. Everything the ring DRAWS goes through it (light, icon, badge, and the
// state fingerprint that decides when to repaint); everything the ring DECIDES
// stays on `CircFeatureOn`, so a press is still an inversion of its own switch.
bool CircFeatureOn(const int i)
{
   if(i == CIR_ZONES)           return g_showMidZones;
   if(i == CIR_TRIGGER)         return g_triggerLevelsEnabled;
   if(i == CIR_ATR)             return g_atrLabelsVisible;
   if(i == CIR_TH)              return g_thLabelsVisible;
   // VIEWLOCK-OFF: if(i == CIR_VLOCK) return g_viewLockEnabled;
   // TH3TOOL-ON (2026-09-19): restored from TH3TOOL-OFF.
   // P-UI-96 (2026-09-19) — MOMENTARY, like the measuring tool one line below:
   // the light is the ARMED AB=CD DRAW, not the ENABLED switch. It used to read
   // `g_enableTH3Tool`, which is what made the item look armed while no session
   // existed anywhere (the user: pressing the tool leaves nothing to draw with).
   // The switch keeps the card's row 0 (PnlGetSetting/SetSetting case 5 row 0)
   // and is NAMED in the tooltip, so nothing became unreachable.
#ifndef BUILD_LITE
   if(i == CIR_TH3)             return TH3SessionActive();
#else
   if(i == CIR_TH3)             return g_enableTH3Tool;   // Lite ships no draw engine
#endif
#ifndef BUILD_LITE
   if(i == CIR_LEG)             return LegMeasureSessionActive();
#else
   if(i == CIR_LEG)             return false;
#endif
   if(i == CIR_HTF)             return g_UI.showHTF;
   if(i == CIR_PIN)             return g_customPriceLineCreated;
   // CIR_BASEKNOT is momentary: lit while the draw session is armed.
   if(i == CIR_BASEKNOT)        return BaseKnotSessionActive();
   // P-HR-01 is momentary too: lit while the ray session is armed.
   if(i == CIR_HRAY)            return HRaySessionActive();
   if(i == CIR_PATH)            return PathSessionActive();
   // STEPOVERRIDE-OFF: single Step Mode — the Tools step button is a plain
   // cycle button (no on/off state); the mode itself is shown by the chart label.
   //if(i == CIR_STEP_OVERRIDE)   return (g_stepModeOverride != -1);
   // FACTORBTN-OFF: if(i == CIR_FACTOR_OVERRIDE) return (g_factorValueOverride > 0.0);
   if(i == CIR_TOOLS)           return g_ToolsOpen;
   return false;
}

// P-UI-93: the switch AND the whole-indicator mute. The other items (HTF, pin,
// tools) have their own masks and are not part of the hide-all walk, so the mute
// is not one of their terms.
bool CircFeatureLit(const int i)
{
   if(!CircFeatureOn(i)) return false;
   if(i == CIR_ZONES || i == CIR_TRIGGER || i == CIR_ATR || i == CIR_TH)
      return !IsIndicatorHidden();
   return true;
}

bool CircHasBadge(const int i)
{
   // NOBADGES (user decision 2026-09-04): NO badges on ring buttons at all —
   // neither the "On" marker nor value texts ("Aut"/"H1"/...). Every badge
   // create/show/move/update path is gated by this function; the delete
   // paths stay to purge badges left by older versions. Settings panels
   // still open via long-press. To restore: return (i != CIR_TOOLS).
   return false;
   // return (i != CIR_TOOLS);   // every main-ring feature shows a badge; Tools opens its sub-menu
}

void CircConfigureIcon(const string name, const int i, const bool on, const int x, const int y)
{
   ObjectSetInteger(0, name, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, name, OBJPROP_XDISTANCE, x - CIRC_ICON_SIZE / 2);
   ObjectSetInteger(0, name, OBJPROP_YDISTANCE, y - CIRC_ICON_SIZE / 2);
   ObjectSetInteger(0, name, OBJPROP_XSIZE, CIRC_ICON_SIZE);
   ObjectSetInteger(0, name, OBJPROP_YSIZE, CIRC_ICON_SIZE);
   string res = CircIconRes(i, on);
   ObjectSetString(0, name, OBJPROP_BMPFILE, 0, res);
   ObjectSetString(0, name, OBJPROP_BMPFILE, 1, res);
   ObjectSetString(0, name, OBJPROP_TOOLTIP, "");   // P-UI-119
   ObjectSetInteger(0, name, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, name, OBJPROP_HIDDEN, true);
   ObjectSetInteger(0, name, OBJPROP_BACK, false);
   ObjectSetInteger(0, name, OBJPROP_ZORDER, Z_MENU_ICON);
}

string CircIconRes(const int i, const bool on)
{
   string base;
   if(i == CIR_ZONES)           base = "zones";   // Mid-zone band icon (the main Zones & Levels feature)
   else if(i == CIR_TRIGGER)    base = "zone";    // Trigger level-ladder icon
   else if(i == CIR_ATR)        base = "atr";     // ATR range-bracket icon
   else if(i == CIR_TH)         base = "dots";    // TH dotted-level icon
   // VIEWLOCK-OFF: else if(i == CIR_VLOCK) base = "box";   // View lock — `box` was a
   //   PADLOCK (ART.box in tools/gen-th3-icons.js), never a rectangle; retired 2026-09-14.
   else if(i == CIR_TH3)        base = "custom";  // TH3 tool/gauge icon   // TH3TOOL-ON (2026-09-19)
   else if(i == CIR_HTF)        base = "htf";     // HTF candle icon
   else if(i == CIR_PIN)        base = "pin";     // Pin icon
    else if(i == CIR_STEP_OVERRIDE)   base = "step";    // Step mode override icon
    // FACTORBTN-OFF: else if(i == CIR_FACTOR_OVERRIDE) base = "factor";  // Factor slider icon
    else if(i == CIR_BASEKNOT)   base = "ruler";   // Base / Knot MEASURE = a scale bar with ticks
    else if(i == CIR_HRAY)       base = "hray";    // P-HR-01 — Horizontal Ray cell
    else if(i == CIR_PATH)       base = "path";    // Path tool cell
    else if(i == CIR_LEG)        base = "leg";     // Leg Measure — trendline + bracket
    else if(i == CIR_TOOLS)      base = "tools";
    // P-UI-131: the gear — a settings DOOR, so it wears the same art the strip's
    // "..." cell uses (one gear in the product, not two).
    else if(i == CIR_GENERAL)    base = "gear";
   else                         base = "htf";
   return "::Files\\Icons\\" + base + (on ? "_on.bmp" : "_off.bmp");
}

//+------------------------------------------------------------------+
//| CARD HEADER ICON — one glyph PER SETTINGS CARD, chosen for the   |
//| content of that card (not the ring toggle that opened it).       |
//|  0 Trigger Zones = zone ladder · 1 Zones & Levels = band ·       |
//|  2 ATR = range bracket · 3 TH = dotted wave · 4 retired (was View lock) · |
//|  5 retired (was TH3) · 6 HTF = candles · 7 Lines = line ·        |
//|  8 CustomPrice = pin · 9 StepMode = stairs · 10 Factor = gauge · |
//|  11 Structure = stair levels                                     |
//+------------------------------------------------------------------+
string CircCardIcon(const int item, const bool on)
{
   string base = "htf";
   if(item == 1)          base = "zones";   // Zones & Levels — MAIN card
   else if(item == 0)     base = "zone";    // Trigger zones overlay
   else if(item == 2)     base = "atr";     // ATR labels (range bracket)
   else if(item == 3)     base = "dots";    // TH labels
   // VIEWLOCK-OFF: else if(item == 4) base = "box";   // View lock
   else if(item == 5)     base = "custom";  // TH3 tool   // TH3TOOL-ON (2026-09-19)
   else if(item == 6)     base = "htf";     // HTF candles
   else if(item == 7)     base = "tl";      // Lines — DEAD ART: `tl` sits in DEAD_ART
                                             // (no tl_*.bmp is emitted), so this header
                                             // would load NOTHING. Harmless only because
                                             // nothing calls CircCardIcon() yet — repoint
                                             // it at live art before wiring that up
                                             // (P-ICONS-08: check `base` against ART).
   else if(item == 8)     base = "pin";     // Custom price pin
   else if(item == 9)     base = "step";    // Step mode
   else if(item == 10)    base = "factor";  // Factor step
   else if(item == 11)    base = "step";    // Structure levels (stair levels)
   else if(item == 12)    base = "ruler";   // Base Box card — the same measuring tool as the ring item
   return "::Files\\Icons\\" + base + (on ? "_on.bmp" : "_off.bmp");
}

string CircBadgeText(const int i)
{
   if(i == CIR_ZONES)           return g_showMidZones ? "On" : "";
   if(i == CIR_TRIGGER)         return IntegerToString(inpMaxLevels);
   if(i == CIR_ATR)             return g_atrLabelsVisible ? "On" : "";
   if(i == CIR_TH)
   {
       if(g_thLabelsMode == 1) return "Fr";
       if(g_thLabelsMode == 2) return "St";
       return "";
   }
   // VIEWLOCK-OFF:
   //if(i == CIR_VLOCK)
   //{
   //   if(g_viewLockEnabled) return "On";
   //   return "";
   //}
   // TH3TOOL-ON (2026-09-19): restored from TH3TOOL-OFF.
   if(i == CIR_TH3)
   {
      if(g_th3FreqOverride > 0) return DoubleToString(g_th3FreqOverride, 1) + "x";
      return "Aut";
   }
   if(i == CIR_HTF)     return CircHtfBadgeLabel(g_HTFPeriod);
   if(i == CIR_PIN)
   {
      if(g_customTHStartPrice > 0) return DoubleToString(g_customTHStartPrice, 1);
      return "Off";
   }
   if(i == CIR_STEP_OVERRIDE)
   {
      // STEPOVERRIDE-OFF: badge follows the single live mode (badges are OFF
      // globally via NOBADGES — this only feeds the tooltip text).
      ENUM_STEP_CALCULATION_MODE sm = GetCurrentStepMode();
      if(sm == TH_STEP) return "TH";
      if(sm == SS_LS_STEP) return "SS";
      if(sm == COMBO_STEP) return "Co";
      if(sm == FACTOR_STEP) return "Fa";
      return "";
   }
   // FACTORBTN-OFF:
   //if(i == CIR_FACTOR_OVERRIDE)
   //{
   //   if(g_factorValueOverride > 0) return DoubleToString(g_factorValueOverride, 0);
   //   return "Auto";
   //}
   if(i == CIR_BASEKNOT)
   {
      int n = BaseKnotCount();
      return (n > 0 ? IntegerToString(n) : "");
   }
   return "";
}

string CircHtfBadgeLabel(const int periodMinutes)
{
   if(periodMinutes <= 0) return "";
   // P-HTF-SYN: the two synthetic top rungs (6M/12M, HTFCandles_Geom.mqh) read as
   // MONTHS. This is the overlay's only human-facing TF label — the ring tooltip
   // and the badge both come through here — and "360D" is not what the rung is.
   // MN1's own "30D" is deliberately untouched: this names the rungs the synthetic
   // ladder added, not the whole ladder.
   if(periodMinutes >= 259200 && (periodMinutes % 43200) == 0)
      return IntegerToString(periodMinutes / 43200) + "M";
   if(periodMinutes >= 1440) return IntegerToString(periodMinutes / 1440) + "D";
   if(periodMinutes >= 60)   return IntegerToString(periodMinutes / 60) + "H";
   return IntegerToString(periodMinutes) + "M";
}

// Live status fragment for a ring/tools feature ("ON", "H4", "Combo", ...).
// CircItemTooltip embeds it so the hover text always shows the CURRENT state:
// every state change re-runs CircConfigureIcon (icon tooltip) +
// CircUpdateItemState/ToolsUpdateItemState (bg tooltip), and the per-tick
// UpdateMenuSyncIfChanged fingerprint already covers all these values
// (on/off flags + CircBadgeText), so hotkey/panel changes refresh tooltips too.
string CircTooltipStatus(const int i)
{
   if(i == CIR_ZONES)             return g_showMidZones ? "ON" : "OFF";
   if(i == CIR_TRIGGER)           return g_triggerLevelsEnabled ? "ON" : "OFF";
   if(i == CIR_ATR)               return g_atrLabelsVisible ? "ON" : "OFF";
   if(i == CIR_TH)
   {
       if(g_thLabelsMode == 1) return "Fractal";
       if(g_thLabelsMode == 2) return "Standard";
       return "Off";
   }
   // VIEWLOCK-OFF:
   //if(i == CIR_VLOCK)             return g_viewLockEnabled ? "ON" : "OFF";
   // TH3TOOL-ON (2026-09-19): restored from TH3TOOL-OFF.
   // P-UI-96: the status is a STATE, not a sentence — the audit substitutes the
   // longest literal here into EVERY tooltip title (`ui-text-audit`
   // `tooltip_texts`), so a longer phrase does not just widen this one tip, it
   // pushes all ten past CIRC_TIP_INNER at every DPI (measured: 328px for 270px
   // of room). "Ready"/"Drawing"/"Disabled" are the same three words the
   // measuring tool next door uses, and they are what the NEXT press does.
   if(i == CIR_TH3)
   {
#ifndef BUILD_LITE
      if(TH3SessionActive())   return "Drawing";
      if(!g_enableTH3Tool)     return "Disabled";
      return "Ready";
#else
      return g_enableTH3Tool ? "Enabled" : "Disabled";
#endif
   }
   if(i == CIR_HTF)
   {
      string st = g_UI.showHTF ? "ON" : "OFF";
      // P-UI-92: the badge names the TF, so the MODE has to be named here or
      // Structure and Pattern are indistinguishable (both read "4H" on M15).
      string mode = HTFTfModeName();
      if(mode != "") st += " · " + mode;
      string lbl = CircHtfBadgeLabel(g_HTFPeriod);
      if(lbl != "") st += " · " + lbl;
      return st;
   }
   if(i == CIR_PIN)
   {
      if(g_customPriceLineCreated && g_customTHStartPrice > 0)
         return DoubleToString(g_customTHStartPrice, Digits);
      return "Not placed";
   }
   if(i == CIR_STEP_OVERRIDE)
   {
      ENUM_STEP_CALCULATION_MODE sm = GetCurrentStepMode();
      if(sm == SS_LS_STEP) return "SS-LS";
      if(sm == COMBO_STEP) return "Combo";
      if(sm == FACTOR_STEP) return "Factor";
      return "TH";
   }
   // FACTORBTN-OFF:
   //if(i == CIR_FACTOR_OVERRIDE)
   //{
   //   if(g_factorValueOverride > 0) return DoubleToString(g_factorValueOverride, 0);
   //   return "Auto";
   //}
   if(i == CIR_BASEKNOT)
   {
      if(BaseKnotSessionActive()) return "Drawing";
      int n = BaseKnotCount();
      return (n > 0 ? IntegerToString(n) + " set" : "Ready");
   }
    if(i == CIR_HRAY)   // P-HR-01: the next press arms/cancels, like the measure tool
    {
       if(HRaySessionActive()) return "Drawing";
       return "Ready";
    }
    if(i == CIR_PATH)
    {
       if(PathSessionActive()) return "Drawing";
       return "Ready";
    }
#ifndef BUILD_LITE
   if(i == CIR_LEG)
   {
      if(LegMeasureSessionActive()) return "Drawing";
      return "Ready";
   }
#endif
   if(i == CIR_TOOLS)             return g_ToolsOpen ? "Open" : "Closed";
   return "";
}

string CircItemTooltip(const int i)
{
   switch(i)
   {
      // P-UI-120: ONE line per item now — the state fragment IS the second sentence
      // that used to sit under the title, so the chip says what the NEXT press does
      // without a second caption nobody's eye reached. The old "Click: … · Hold: …"
      // tails are in git history (this is a one-string restore, not a lost rule).
      case CIR_ZONES:           return "Zones & Levels · " + CircTooltipStatus(i);
      case CIR_TRIGGER:         return "Trigger Zones · " + CircTooltipStatus(i);
      case CIR_ATR:             return "ATR Labels · " + CircTooltipStatus(i);
      case CIR_TH:              return "TH Labels · " + CircTooltipStatus(i);
       // VIEWLOCK-OFF: case CIR_VLOCK: return "View Lock";
      // "Movement step", not "frequency": the badge/label number is how far one
      // step of the move is (AB cut into 100/step pieces), not a frequency.
      // P-UI-96: the press ARMS the AB=CD draw (X, A, B, C) — the tool's own
      // momentary path, the same shape BASEKNOT uses. It used to toggle the
      // ENABLED flag, which is why "Click: toggle TH3" produced no drawing: the
      // AB=CD session was reachable only from the V key. The status fragment is
      // the item's own state, so the tip says what the NEXT press does instead
      // of what one flag is set to.
      case CIR_TH3:             return "TH3 Movement Step · " + CircTooltipStatus(i);   // TH3TOOL-ON (2026-09-19)
      case CIR_HTF:             return "HTF Candles · " + CircTooltipStatus(i);
      case CIR_PIN:             return "Custom Price Pin · " + CircTooltipStatus(i);
       case CIR_STEP_OVERRIDE:   return "Step Mode · " + CircTooltipStatus(i);
      // FACTORBTN-OFF: case CIR_FACTOR_OVERRIDE: return "Factor Override · ...";
      case CIR_BASEKNOT:        return "Base / Knot Measure · " + CircTooltipStatus(i);
      case CIR_HRAY:            return "Horizontal Ray · " + CircTooltipStatus(i);   // P-HR-01
      case CIR_PATH:            return "Path · " + CircTooltipStatus(i);
      case CIR_LEG:             return "Leg Measure · " + CircTooltipStatus(i);
      case CIR_TOOLS:           return "Biotak Tools · " + CircTooltipStatus(i);
      // P-UI-131: a DOOR has no state to report, so the tip names the card instead
      // of appending an empty status fragment (" · " with nothing after it).
      case CIR_GENERAL:         return "General Settings · engine, grid, interface";
   }
   return "";
}

#endif // BIOTAK_MENU_A_MQH
