// TH3Tool_A.mqh - TH3Tool.mqh split 2026-09-29: exact lines 8-1352, byte-identical, zero renames.
#ifndef TH3_TOOL_A_MQH
#define TH3_TOOL_A_MQH

#property strict

// Constants for magic numbers
#ifndef ABCD_MIN_DISTANCE_POINTS
#define ABCD_MIN_DISTANCE_POINTS 10
#endif
#ifndef ABCD_DEBOUNCE_MS
#define ABCD_DEBOUNCE_MS 300
#endif
#define ABCD_LABEL_OFFSET_PIPS 15.0
#define ABCD_MAX_PRICE_MULTIPLIER 10.0
#define ABCD_COLLINEARITY_THRESHOLD 0.0001

#define TH3_PATTERN_PREFIX_LEN  13

// P-LM-14/17: the leg meter's HANDLE RINGS are baked icons (see LegHandleAt) —
// the user's call («از ایکون بساز براش») after chart-space shapes failed twice:
// an ellipse whose anchors sat in one bar drew as a hairline (P-LM-13), and a
// one-bar-wide one was still not a circle. Baked pixels are exact at every zoom,
// and since P-LM-17 they come in a DIRECTION pair (green up, red down).
// Generated by tools/gen-th3-icons.js; embedded here so the leg module owns its
// own rasters (the ring menu's icons are declared beside their own consumers).
#resource "\\Files\\Icons\\leg_handle_up.bmp"
#resource "\\Files\\Icons\\leg_handle_up_mid.bmp"
#resource "\\Files\\Icons\\leg_handle_dn.bmp"
#resource "\\Files\\Icons\\leg_handle_dn_mid.bmp"
// P-LM-18: the SELECTED pair — hollow rings against the resting solid dots
#resource "\\Files\\Icons\\leg_handle_up_sel.bmp"
#resource "\\Files\\Icons\\leg_handle_up_mid_sel.bmp"
#resource "\\Files\\Icons\\leg_handle_dn_sel.bmp"
#resource "\\Files\\Icons\\leg_handle_dn_mid_sel.bmp"

// Drawing constants (from MT5)
// (TH3_ARROW_CODE 159 retired with the leg meter's glyph dot — P-LM-11/12)
#define TH3_POINT_WIDTH         3
#define TH3_POINT_ZORDER        10
#define TH3_TARGET_COUNT        4
#define TH3_TARGET_LINE_WIDTH   2
#define TH3_BAR_EXTENSION       100
#define TH3_SNAP_THRESHOLD_PIPS 5.0
#define TH3_MIN_BASENAME_LEN    20
#define TH3_MAX_TARGETS         7


// TH3 modular architecture: model + pure math + store + controller
#include "TH3\TH3Types.mqh"
#include "TH3\TH3Math.mqh"
#include "TH3\TH3PatternStore.mqh"
#include "TH3\TH3Controller.mqh"
#include "TH3\TH3Renderer.mqh"

// Registry state for fast TH3 bulk updates (avoids chart-wide scans)
static string g_th3PatternRegistry[];
static int    g_th3PatternRegistryCount = 0;

//+------------------------------------------------------------------+
//| Pattern Registry System (ported from MT5)                         |
//+------------------------------------------------------------------+
string ExtractPatternBaseName(const string objName)
{
    if(StringFind(objName, TH3_PATTERN_PREFIX) != 0) return "";
    string suffixes[] = {
        TH3_SUFFIX_LINE_AB, TH3_SUFFIX_LINE_BC, TH3_SUFFIX_TARGET,
        TH3_SUFFIX_POINT, TH3_SUFFIX_LABEL, TH3_SUFFIX_INFO, TH3_SUFFIX_ZONE
    };
    string baseName = objName;
    for(int s = 0; s < ArraySize(suffixes); s++) {
        int pos = StringFind(baseName, suffixes[s]);
        if(pos > 0) { baseName = StringSubstr(baseName, 0, pos); break; }
    }
    if(StringFind(baseName, TH3_PATTERN_PREFIX) != 0 || StringLen(baseName) < TH3_MIN_BASENAME_LEN)
        return "";
    return baseName;
}

int FindTH3PatternRegistryIndex(const string baseName)
{
    for(int i = 0; i < g_th3PatternRegistryCount; i++) {
        if(g_th3PatternRegistry[i] == baseName) return i;
    }
    return -1;
}

void RegisterTH3Pattern(const string baseName)
{
    if(baseName == "") return;
    if(FindTH3PatternRegistryIndex(baseName) >= 0) return;
    int newCount = g_th3PatternRegistryCount + 1;
    ArrayResize(g_th3PatternRegistry, newCount, 16);
    g_th3PatternRegistry[g_th3PatternRegistryCount] = baseName;
    g_th3PatternRegistryCount = newCount;
}

void UnregisterTH3Pattern(const string baseName)
{
    int idx = FindTH3PatternRegistryIndex(baseName);
    if(idx < 0) return;
    for(int i = idx; i < g_th3PatternRegistryCount - 1; i++) {
        g_th3PatternRegistry[i] = g_th3PatternRegistry[i + 1];
    }
    g_th3PatternRegistryCount--;
    if(g_th3PatternRegistryCount <= 0) {
        g_th3PatternRegistryCount = 0;
        ArrayResize(g_th3PatternRegistry, 0);
    } else {
        ArrayResize(g_th3PatternRegistry, g_th3PatternRegistryCount);
    }
}

void RebuildTH3RegistryFromChart()
{
    g_th3PatternRegistryCount = 0;
    ArrayResize(g_th3PatternRegistry, 0);
    int totalObjects = ObjectsTotal();
    for(int i = 0; i < totalObjects; i++) {
        string name = ObjectName(i);
        if(StringFind(name, TH3_PATTERN_PREFIX) != 0) continue;
        string baseName = ExtractPatternBaseName(name);
        if(baseName == "") {
            int underscorePos = StringFind(name, "_", TH3_PATTERN_PREFIX_LEN);
            baseName = (underscorePos > TH3_PATTERN_PREFIX_LEN)
                       ? StringSubstr(name, 0, underscorePos)
                       : name;
        }
        RegisterTH3Pattern(baseName);
    }
}

void BuildPatternNamesFromRegistry(string &patternNames[], int &patternCount)
{
    patternCount = 0;
    ArrayResize(patternNames, g_th3PatternRegistryCount);
    for(int i = 0; i < g_th3PatternRegistryCount; i++) {
        string baseName = g_th3PatternRegistry[i];
        if(baseName == "") continue;
        string lineAB = baseName + TH3_SUFFIX_LINE_AB;
        string lineBC = baseName + TH3_SUFFIX_LINE_BC;
        if(ObjectFind(lineAB) < 0 || ObjectFind(lineBC) < 0) {
            UnregisterTH3Pattern(baseName);
            i--;
            continue;
        }
        patternNames[patternCount++] = baseName;
    }
    if(patternCount < ArraySize(patternNames)) {
        ArrayResize(patternNames, patternCount);
    }
}

//+------------------------------------------------------------------+
//| Compute safe Y position for TH3 info label                       |
//| Accounts for ATR labels + all possible stacked mode labels       |
//+------------------------------------------------------------------+
int GetABCDInfoSafeYDistance()
{
    int y = inpABCDInfoYDistance;

    bool topCorner = (inpABCDInfoCorner == CORNER_LEFT_UPPER || inpABCDInfoCorner == CORNER_RIGHT_UPPER);
    if(!topCorner) return y;

    // ATR/TH label stack currently lives at top-left when label corner is LEFT_TOP.
    if(inpLabelCornerPosition == LABEL_CORNER_LEFT_TOP && inpABCDInfoCorner == CORNER_LEFT_UPPER) {
        int stackedTopY = inpLabelsMarginTop + g_modeLabelYOffset + inpSectionGap;
        if(y < stackedTopY) y = stackedTopY;
    }

    // Push below ALL stacked mode labels + lock label
    // P-TH3-INFO-02: the mode rows themselves stand a hardcoded +45 below the
    // ATR stack (ApplyModeLabelStyle) — a safe-Y that forgets it parks the
    // caption up to ~41 px INSIDE the mode rows (the user's top-left mash: the
    // dark caption plate behind the SS/LS row). Mirror the +45 here.
    if(inpModeLabelCorner == inpABCDInfoCorner) {
        int modeBlockHeight = GetModeLabelBlockHeight();
        int modeBottomY;
        if(modeBlockHeight > 0)
            modeBottomY = inpModeLabelYDistance + g_modeLabelYOffset + 45 + modeBlockHeight + 4;
        else
            modeBottomY = inpModeLabelYDistance + g_modeLabelYOffset + (inpModeLabelFontSize + 6) + 4;

        if(g_timeframeLocked) {
            modeBottomY += (inpModeLabelFontSize + 6);
        }
        if(y < modeBottomY) y = modeBottomY;
    }

    return y;
}

//+------------------------------------------------------------------+
//| Reposition all ABCD info labels (lightweight   Y update only)    |
//| Call after g_modeLabelYOffset changes to prevent overlap         |
//+------------------------------------------------------------------+
void RepositionABCDInfoLabels()
{
    // P-TH3-INFO-09: the VERIFY and the ORPHAN SWEEP are not the tool card's
    // privilege. A caption the tool drew (or a build mix left behind) must heal
    // even with the card switched off — with the early return below the passes
    // never ran, and the reported «متن داخل کادر سیاه دیده نمیشه» (a plate
    // whose ink went stale/behind) lived on the chart forever. Only the
    // REPOSITION work stays tool-gated: nothing to move when the tool draws
    // nothing new.
    int safeY = GetABCDInfoSafeYDistance();
    int patCount = TH3PatternStoreCount();
    bool reposition = inpEnableTH3Tool;
    for(int i = 0; i < patCount; i++)
    {
        // P-TH3-INFO-01: the caption is a stacked FAMILY, so the whole family
        // moves together - moving only `_Info` would pull line 1 up into the
        // mode labels and leave lines 2..n behind.
        // P-TH3-INFO-14: and it is its rows AND its plate, on the ONE Y
        // P-TH3-INFO-10 left: only the active family carries a plate, so the
        // slot grid (per-pattern index) is retired — every family is parked at
        // the base and the visible one sits exactly where the user expects it.
        // Whoever becomes active is re-placed by the draw pass on the same Y.
        // P-TH3-INFO-06c: verify FIRST (heal a visibility the redraw did not
        // write), then move.
        string pname = g_th3Patterns.items[i].name;
        TH3InfoFamilyVerify(pname, (pname == g_activeABCDPattern));
        if(reposition)
            TH3InfoFamilyReposition(pname, safeY);
    }
    // P-TH3-INFO-06b: plus the chart-wide sweep — a plate whose base never
    // reached the store (skipped restore, build mix) has no rows to count
    // above, and only this pass can see it.
    TH3InfoOrphanPlateSweep();
}

//+------------------------------------------------------------------+
//| Get Cached Daily ATR (Performance Optimization)                 |
//|              ATR                   Cache (                                  )                  |
//| Caches ATR for current bar to avoid repeated calculations       |
//+------------------------------------------------------------------+
//+------------------------------------------------------------------+
//| Set active AB=CD pattern (for info label display)               |
//|          AB=CD (      info label)                    |
//+------------------------------------------------------------------+
void SetActiveABCDPattern(string patternName)
{
    if(g_activeABCDPattern == patternName) return; // Already active

    // P-TH3-P6d (2026-09-19) — AT MOST ONE INFO IS VISIBLE. The old rule hid
    // only the remembered previous pattern's info: a second completion, a
    // restore, or an orphaned info from a deleted pattern left two
    // "AB=CD | AB:… | Step:…" captions stacked on the same corner, and the
    // user read the STALE number as the ladder's own. This is the one owner
    // of "which info shows": every other pattern info on this chart goes
    // dark first, and only the new active one's lights. A rare event (a
    // pattern activation), so a namespace sweep is the right cost.
    // P-TH3-INFO-01: the caption is a FAMILY of lines (_Info, _Info2.._Info4),
    // so the sweep and the show both go through the family owner. Matching the
    // literal "_Info" would recognise line 1 only and leave every continuation
    // line of the previous pattern lit beside the new one's.
    for(int i = ObjectsTotal(0, -1, -1) - 1; i >= 0; i--) {
        string nm = ObjectName(0, i, -1, -1);
        if(StringFind(nm, "ABCD_Pattern_") != 0) continue;
        if(!TH3IsInfoLabelName(nm))
        {
            // P-TH3-P6f (2026-09-22): the ladder follows the caption. Activation
            // flips no ladder by itself (only captions), so the newly-active
            // pattern would stay ladder-less until the next full redraw — this
            // branch masks every ladder here: own family lit, the rest dark.
            // Guarded writes (perf law); clearing ("") darkens every ladder.
            if(!TH3IsLadderName(nm)) continue;
            bool ownLadder = (patternName != "" && StringFind(nm, patternName + "_") == 0);
            int wantLad = ownLadder ? OBJ_ALL_PERIODS : OBJ_NO_PERIODS;
            if(ObjectGetInteger(0, nm, OBJPROP_TIMEFRAMES) != wantLad)
                ObjectSetInteger(0, nm, OBJPROP_TIMEFRAMES, wantLad);
            continue;
        }
        // P-TH3-INFO-04: the family is its ROWS and its PLATE. A plate matched as
        // "not ours" would be darkened while its own rows stay lit - a dark bar
        // with the new pattern's text on it.
        bool ownFamily = (nm == TH3InfoPlateName(patternName));
        for(int line = 0; line < TH3_INFO_MAX_LINES; line++) {
            if(nm == TH3InfoLineName(patternName, line)) { ownFamily = true; break; }
        }
        if(ownFamily) continue;
        // P-TH3-INFO-10: rows hide under their mask; the PLATE is DROPPED —
        // a mask does not hide an OBJ_RECTANGLE_LABEL, so every family this
        // sweep darkened used to leave its empty bar on the chart («فقط سیاه»).
        if(TH3IsInfoPlateName(nm)) ObjectDelete(0, nm);
        else ObjectSetInteger(0, nm, OBJPROP_TIMEFRAMES, OBJ_NO_PERIODS);
    }

    // Set new active pattern
    g_activeABCDPattern = patternName;
    
    // Show new pattern's caption family
    if(patternName != "")
        TH3InfoFamilySetVisible(patternName, true);
    
    ThrottledChartRedraw();
    
    #ifdef ENABLE_DEBUG_LOGS
    Print("==================== Active AB=CD pattern: ", patternName);
    #endif
}

//+------------------------------------------------------------------+
//| Calculate Optimal Default Frequency                             |
//|                                               |
//| Analyzes all frequencies to find best default for Steps 3,5,7   |
//+------------------------------------------------------------------+
double CalculateOptimalDefaultFrequency()
{
    //    
    //       D     Step N    
    // frequency = 100 / N
    // 
    // Step 3: 100/3 = 33.333%
    // Step 5: 100/5 = 20.0%
    // Step 7: 100/7 = 14.286%
    
    //                    
    double idealFrequencies[3];
    idealFrequencies[0] = 100.0 / 3.0;  // 33.333% for Step 3
    idealFrequencies[1] = 100.0 / 5.0;  // 20.0% for Step 5
    idealFrequencies[2] = 100.0 / 7.0;  // 14.286% for Step 7
    
    int bestIndices[3] = {-1, -1, -1};
    double minErrors[3] = {1000000.0, 1000000.0, 1000000.0};
    
    //                    
    for(int i = 0; i < 3; i++)
    {
        int bestIdx = FindNearestFreqIndex(idealFrequencies[i]);
        double minError = MathAbs(GetFrequencyByIndex(bestIdx) - idealFrequencies[i]);
        
        bestIndices[i] = bestIdx;
        minErrors[i] = minError;
    }
    
    //          
    #ifdef ENABLE_DEBUG_LOGS
    Print("========================================");
    Print("==================== OPTIMAL DEFAULT FREQUENCY ANALYSIS");
    Print("========================================");
    Print("Step 3 (Ideal: 33.333%):");
    Print("  ==================== Closest: ", DoubleToString(GetFrequencyByIndex(bestIndices[0]), 3), 
          "% (Index: ", bestIndices[0], ", Error: ", DoubleToString(minErrors[0], 3), "%)");
    Print("Step 5 (Ideal: 20.0%):");
    Print("  ==================== Closest: ", DoubleToString(GetFrequencyByIndex(bestIndices[1]), 3), 
          "% (Index: ", bestIndices[1], ", Error: ", DoubleToString(minErrors[1], 3), "%)");
    Print("Step 7 (Ideal: 14.286%):");
    Print("  ==================== Closest: ", DoubleToString(GetFrequencyByIndex(bestIndices[2]), 3), 
          "% (Index: ", bestIndices[2], ", Error: ", DoubleToString(minErrors[2], 3), "%)");
    Print("========================================");
    #endif
    
    //                                
    // Step 5      (     50%)
    // Step 3    7     25%         
    double weightedFreq = (GetFrequencyByIndex(bestIndices[0]) * 0.25) +
                          (GetFrequencyByIndex(bestIndices[1]) * 0.50) +
                          (GetFrequencyByIndex(bestIndices[2]) * 0.25);
    
    //                               
    int bestDefaultIdx = FindNearestFreqIndex(weightedFreq);
    double bestDefault = GetFrequencyByIndex(bestDefaultIdx);
    
    #ifdef ENABLE_DEBUG_LOGS
    Print("==================== RECOMMENDED DEFAULT FREQUENCY:");
    Print("  Weighted Average: ", DoubleToString(weightedFreq, 3), "%");
    Print("  Best Match: ", DoubleToString(bestDefault, 3), "% (Index: ", bestDefaultIdx, ")");
    Print("========================================");
    #endif
    
    return bestDefault;
}

//+------------------------------------------------------------------+
//| Get Current TH3 Frequency (with override support)               |
//+------------------------------------------------------------------+
double GetCurrentTH3Frequency() {
    if(g_th3FreqOverride > 0.0) return g_th3FreqOverride;
    
    // Validate input parameter (extended to 120%)
    if(inpTH3BaseStepPercent > 0.0 && inpTH3BaseStepPercent <= 120.0) {
        return inpTH3BaseStepPercent;
    }
    
    // Fallback to safe default
    return 28.125;
}

//+------------------------------------------------------------------+
//| Analyze Three-Wave Pattern (XA, AB, BC)                         |
//|             (XA  AB  BC)                                 |
//| Returns comprehensive wave analysis for frequency selection     |
//+------------------------------------------------------------------+
//|           (    Gann)                                    |
//| Returns: Angle in degrees (0-90)                                |
//| Logic: angle = atan(price_change / time_change)                 |
//+------------------------------------------------------------------+
//| Calculate Optimal Frequency from Wave Analysis                  |
//|                                                  |
//| Integrates: speed, consolidation, consistency, Fibonacci        |
//+------------------------------------------------------------------+
double CalculateFrequencyFromWaves(WaveAnalysis &waves)
{
    //                    
    // 1.             (Step 5 = 20%)
    // 2.                  (Impulsive/Correctional)
    // 3.             (Gann-inspired)
    // 4.            
    // 5.             Fibonacci
    
    double baseFrequency = 20.0; //     Step 5
    
    // ========================================
    //   1:                 
    // ========================================
    if(waves.isImpulsive) {
        baseFrequency *= 1.3; //   30%          
    }
    else if(waves.isCorrectional) {
        baseFrequency *= 0.7; //   30%        
    }
    
    // ========================================
    //   2:             (Gann-inspired)
    // ========================================
    //               ATR
    // OPTIMIZATION: Use cached ATR instead of repeated iATR() calls
    double dailyATR = GetCachedDailyATR();
    double pipSize = GetCachedPipSize();
    double minATR = pipSize * 10;  // Minimum 10 pips worth of ATR
    
    if(dailyATR <= 0 || dailyATR < minATR) {
        double avgRange = 0;
        for(int i = 1; i <= 20; i++) {
            avgRange += (iHigh(NULL, PERIOD_D1, i) - iLow(NULL, PERIOD_D1, i));
        }
        dailyATR = avgRange / 20.0;
    }
    
    double dailyATRInPips = dailyATR / pipSize;
    double referenceSpeed = dailyATRInPips / 1440.0;
    if(referenceSpeed <= 0) referenceSpeed = 0.1;
    
    double avgSpeedRatio = waves.avgSpeed / referenceSpeed;
    
    //             (    Gann)
    double speedWeight = 1.0;
    if(avgSpeedRatio >= 3.0) {
        speedWeight = 1.5; //    
    }
    else if(avgSpeedRatio >= 2.0) {
        speedWeight = 1.3; //   (Gann 2 
    }
    else if(avgSpeedRatio >= 1.5) {
        speedWeight = 1.15; //      
    }
    else if(avgSpeedRatio >= 0.8 && avgSpeedRatio <= 1.2) {
        speedWeight = 1.0; //   (Gann 1 
    }
    else if(avgSpeedRatio >= 0.5) {
        speedWeight = 0.85; //         (Gann 1 
    }
    else if(avgSpeedRatio >= 0.33) {
        speedWeight = 0.7; //    
    }
    else {
        speedWeight = 0.6; //      
    }
    
    baseFrequency *= speedWeight;
    
    // ========================================
    //   3:            
    // ========================================
    //                  
    double consistencyFactor = 0.8 + (waves.speedConsistency * 0.4); // 0.8   1.2
    baseFrequency *= consistencyFactor;
    
    // ========================================
    //   4:             AB/XA (Fibonacci)
    // ========================================
    //             Fibonacci           
    double fibRatios[7] = {0.382, 0.5, 0.618, 0.786, 1.0, 1.272, 1.618};
    double minFibDiff = 1000.0;
    
    for(int i = 0; i < 7; i++) {
        double diff = MathAbs(waves.AB_XA_Ratio - fibRatios[i]);
        if(diff < minFibDiff) minFibDiff = diff;
    }
    
    //         Fibonacci   (< 0.1)     
    if(minFibDiff < 0.1) {
        baseFrequency *= 1.1; //   10%
    }
    
    // ========================================
    //   5:             
    // ========================================
    if(baseFrequency < 3.125) baseFrequency = 3.125;
    if(baseFrequency > 120.0) baseFrequency = 120.0; // Extended to 120%
    
    return baseFrequency;
}
//|           (    Gann) -                  |
//| Returns: Speed ratio relative to reference (1.0 = balanced)     |
//| > 1.0 = Fast move, < 1.0 = Slow move                           |
//+------------------------------------------------------------------+
//| Analyze Harmonic Properties (Scientific Analysis)               |
//|             (                              |
//| Returns: Detailed analysis of harmonic ratios                   |
//+------------------------------------------------------------------+
void AnalyzeHarmonicProperties(WaveAnalysis &waves)
{
    #ifdef ENABLE_DEBUG_LOGS
    Print("========================================");
    Print("==================== HARMONIC ANALYSIS (SCIENTIFIC)");
    Print("========================================");
    
    // ========================================
    // 1. HARMONIC MEAN ANALYSIS
    // ========================================
    if(waves.XA_Speed > 0 && waves.AB_Speed > 0 && waves.BC_Speed > 0) {
        double recipSum = (1.0/waves.XA_Speed) + (1.0/waves.AB_Speed) + (1.0/waves.BC_Speed);
        double harmonicMean = 3.0 / recipSum;
        double arithmeticMean = (waves.XA_Speed + waves.AB_Speed + waves.BC_Speed) / 3.0;
        double geometricMean = MathPow(waves.XA_Speed * waves.AB_Speed * waves.BC_Speed, 1.0/3.0);
        
        Print("==================== PYTHAGOREAN MEANS:");
        Print("   Harmonic Mean:   ", DoubleToString(harmonicMean, 2), " pips/min");
        Print("   Geometric Mean:  ", DoubleToString(geometricMean, 2), " pips/min");
        Print("   Arithmetic Mean: ", DoubleToString(arithmeticMean, 2), " pips/min");
        Print("   Relationship: HM ==================== GM ==================== AM ", 
              (harmonicMean <= geometricMean && geometricMean <= arithmeticMean) ? "====================" : "====================");
        
        double meanRatio = harmonicMean / arithmeticMean;
        Print("   HM/AM Ratio: ", DoubleToString(meanRatio, 3));
        if(meanRatio > 0.9) {
            Print("   ==================== ==================== EXCELLENT: Very consistent speeds");
        } else if(meanRatio > 0.8) {
            Print("   ==================== ==================== GOOD: Moderately consistent speeds");
        } else if(meanRatio > 0.7) {
            Print("   ==================== ==================== FAIR: Some speed variation");
        } else {
            Print("   ==================== ==================== POOR: High speed variation");
        }
    }
    
    // ========================================
    // 2. GOLDEN RATIO ANALYSIS (PHI)
    // ========================================
    double phi = 1.618033988749;
    double phiInverse = 0.618033988749;
    
    Print("==================== GOLDEN RATIO (==================== = 1.618):");
    
    // AB/XA ratio
    double phiDev_AB_XA = MathAbs(waves.AB_XA_Ratio - phiInverse);
    Print("   AB/XA = ", DoubleToString(waves.AB_XA_Ratio, 3));
    if(phiDev_AB_XA < 0.05) {
        Print("   ==================== ==================== GOLDEN RATIO (0.618) detected! Deviation: ", 
              DoubleToString(phiDev_AB_XA * 100, 1), "%");
    } else {
        double phiDev_ext = MathAbs(waves.AB_XA_Ratio - phi);
        if(phiDev_ext < 0.08) {
            Print("   ==================== ==================== PHI EXTENSION (1.618) detected! Deviation: ", 
                  DoubleToString(phiDev_ext * 100, 1), "%");
        } else {
            Print("   ==================== No Golden Ratio (deviation: ", DoubleToString(phiDev_AB_XA * 100, 1), "%)");
        }
    }
    
    // BC/AB ratio
    double phiDev_BC_AB = MathAbs(waves.BC_AB_Ratio - phiInverse);
    Print("   BC/AB = ", DoubleToString(waves.BC_AB_Ratio, 3));
    if(phiDev_BC_AB < 0.05) {
        Print("   ==================== ==================== GOLDEN RATIO (0.618) detected! Deviation: ", 
              DoubleToString(phiDev_BC_AB * 100, 1), "%");
    } else {
        Print("   ==================== No Golden Ratio (deviation: ", DoubleToString(phiDev_BC_AB * 100, 1), "%)");
    }
    
    // ========================================
    // 3. SUMMARY
    // ========================================
    int harmonicScore = 0;
    if(waves.XA_Speed > 0 && waves.AB_Speed > 0 && waves.BC_Speed > 0) {
        double recipSum = (1.0/waves.XA_Speed) + (1.0/waves.AB_Speed) + (1.0/waves.BC_Speed);
        double harmonicMean = 3.0 / recipSum;
        double arithmeticMean = (waves.XA_Speed + waves.AB_Speed + waves.BC_Speed) / 3.0;
        double meanRatio = harmonicMean / arithmeticMean;
        if(meanRatio > 0.9) harmonicScore++;
    }
    
    if(phiDev_AB_XA < 0.05 || phiDev_BC_AB < 0.05) harmonicScore++;
    
    Print("========================================");
    Print("==================== HARMONIC QUALITY: ", harmonicScore, "/2");
    if(harmonicScore == 2) {
        Print("   ==================== EXCELLENT: Strong harmonic properties");
    } else if(harmonicScore == 1) {
        Print("   ==================== GOOD: Some harmonic properties");
    } else {
        Print("   ==================== NORMAL: No special harmonic properties");
    }
    Print("========================================");
    #endif
}

//+------------------------------------------------------------------+
//| Calculate Frequency Error for AB=CD Pattern                     |
//|              AB=CD                              |
//| Returns: Error percentage (0 = perfect match)                   |
//| CRITICAL FIX: Added division by zero protection                 |
//+------------------------------------------------------------------+
//| Find Optimal Frequency for XABCD Pattern - COMPLETE ANALYSIS    |
//|                  XABCD -                |
//| Multi-factor scoring: error, wave analysis, Fibonacci, symmetry |
//+------------------------------------------------------------------+
int FindOptimalFrequencyForABCD(datetime tX, double pX, datetime tA, double pA, 
                                datetime tB, double pB, datetime tC, double pC,
                                FrequencySearchResult &results[],
                                double maxErrorPercent = 5.0)
{
    //        
    ArrayResize(results, 0);
    
    double AB_Distance = MathAbs(pB - pA);
    if(AB_Distance <= 0) return 0;
    
    double pipSize = GetCachedPipSize();
    
    // ========================================
    //   1:         (Wave Analysis)
    // ========================================
    WaveAnalysis waves = AnalyzeThreeWaves(tX, pX, tA, pA, tB, pB, tC, pC);
    
    //             ( 
    AnalyzeHarmonicProperties(waves);
    
    //                    
    double suggestedFreq = CalculateFrequencyFromWaves(waves);
    
    //              
    double speedRatio = CalculateMovementSpeed(tA, pA, tB, pB);
    double timeSymmetry = waves.timeSymmetry;  //             struct
    
    //         Fibonacci
    double fibDeviation = CalculateFibonacciDeviation(waves.AB_XA_Ratio);
    
    //     Consolidation (          breakout)
    double consolidationFactor = CalculateConsolidationFactor(tA, tB, tC, waves);
    
    #ifdef ENABLE_DEBUG_LOGS
    Print("========================================");
    Print("==================== COMPLETE WAVE ANALYSIS (X-A-B-C):");
    Print("   Wave Distances: XA=", DoubleToString(waves.XA_Distance/pipSize, 1), 
          " | AB=", DoubleToString(waves.AB_Distance/pipSize, 1),
          " | BC=", DoubleToString(waves.BC_Distance/pipSize, 1), " pips");
    Print("   Wave Speeds: XA=", DoubleToString(waves.XA_Speed, 2), 
          " | AB=", DoubleToString(waves.AB_Speed, 2),
          " | BC=", DoubleToString(waves.BC_Speed, 2), " pips/min");
    Print("   AB/XA Ratio: ", DoubleToString(waves.AB_XA_Ratio, 3), 
          " (Fib Dev: ", DoubleToString(fibDeviation, 3), ")");
    Print("   Speed Consistency: ", DoubleToString(waves.speedConsistency * 100, 1), "%");
    Print("   Time Symmetry: ", DoubleToString(timeSymmetry * 100, 1), "%");
    Print("   Consolidation Factor: ", DoubleToString(consolidationFactor * 100, 1), "% (Energy buildup)");
    Print("   Pattern Type: ", waves.isImpulsive ? "Impulsive" : (waves.isCorrectional ? "Correctional" : "Balanced"));
    Print("   Suggested Frequency: ", DoubleToString(suggestedFreq, 3), "%");
    Print("   Speed Ratio: ", DoubleToString(speedRatio, 2), "x");
    
    //         
    if(waves.speedConsistency < 0.5) {
        Print("   ==================== WARNING: Low speed consistency - results may be unreliable");
    } else if(waves.speedConsistency < 0.7) {
        Print("   ==================== CAUTION: Moderate speed consistency");
    } else {
        Print("   ==================== Good speed consistency");
    }
    
    //     consolidation  
    if(consolidationFactor > 0.7) {
        Print("   ==================== HIGH CONSOLIDATION: Expect strong breakout - using larger steps");
    } else if(consolidationFactor > 0.4) {
        Print("   ==================== MODERATE CONSOLIDATION: Some energy buildup detected");
    }
    
    Print("========================================");
    #endif
    
    // ========================================
    //   2:           (Advanced Harmonic Analysis)
    // ========================================
    //         Gann         (  struct)
    double gannAngle = waves.AB_Angle;
    
    //       BC/AB        
    double bcToAbRatio = 0.0;
    if(waves.AB_Distance > 0) {
        bcToAbRatio = waves.BC_Distance / waves.AB_Distance;
    }
    
    // ========================================
    //   HARMONIC PATTERN RECOGNITION (Gartley, Bat, Butterfly, Crab)
    // ========================================
    //         Fibonacci    
    string harmonicPattern = "NONE";
    double harmonicConfidence = 0.0;
    double prz_Frequency = 0.0;  // Potential Reversal Zone frequency
    
    // Gartley Pattern: AB/XA = 0.618, BC/AB = 0.382-0.886, CD = 1.272 extension of BC
    if(waves.AB_XA_Ratio >= 0.580 && waves.AB_XA_Ratio <= 0.660) {
        if(bcToAbRatio >= 0.382 && bcToAbRatio <= 0.886) {
            harmonicPattern = "GARTLEY";
            harmonicConfidence = 0.786;  // 78.6% retracement point
            prz_Frequency = 28.0 + (bcToAbRatio * 30.0);  // 28-58% range
        }
    }
    // Bat Pattern: AB/XA = 0.382-0.500, BC/AB = 0.382-0.886, CD = 1.618-2.618 extension
    else if(waves.AB_XA_Ratio >= 0.382 && waves.AB_XA_Ratio <= 0.500) {
        if(bcToAbRatio >= 0.382 && bcToAbRatio <= 0.886) {
            harmonicPattern = "BAT";
            harmonicConfidence = 0.886;  // 88.6% retracement point
            prz_Frequency = 35.0 + (bcToAbRatio * 25.0);  // 35-60% range
        }
    }
    // Butterfly Pattern: AB/XA = 0.786, BC/AB = 0.382-0.886, CD = 1.618-2.24 extension
    else if(waves.AB_XA_Ratio >= 0.750 && waves.AB_XA_Ratio <= 0.820) {
        if(bcToAbRatio >= 0.382 && bcToAbRatio <= 0.886) {
            harmonicPattern = "BUTTERFLY";
            harmonicConfidence = 1.272;  // 127.2% extension
            prz_Frequency = 45.0 + (bcToAbRatio * 35.0);  // 45-80% range
        }
    }
    // Crab Pattern: AB/XA = 0.382-0.618, BC/AB = 0.382-0.886, CD = 2.24-3.618 extension
    else if(waves.AB_XA_Ratio >= 0.382 && waves.AB_XA_Ratio <= 0.618) {
        if(bcToAbRatio >= 0.382 && bcToAbRatio <= 0.886) {
            harmonicPattern = "CRAB";
            harmonicConfidence = 1.618;  // 161.8% extension
            prz_Frequency = 50.0 + (bcToAbRatio * 40.0);  // 50-90% range
        }
    }
    
    // ========================================
    //   ANDREWS PITCHFORK MEDIAN LINE ANALYSIS
    // ========================================
    //        80%:   80%             (Median Line)  
    //       Median Line         
    double medianPrice = (pX + pA + pB) / 3.0;  // Median of X, A, B
    double currentDistanceFromMedian = MathAbs(pC - medianPrice);
    double maxDistanceFromMedian = MathMax(MathAbs(pA - medianPrice), MathAbs(pB - medianPrice));
    
    double medianLineDeviation = 0.0;
    if(maxDistanceFromMedian > 0) {
        medianLineDeviation = currentDistanceFromMedian / maxDistanceFromMedian;
    }
    
    //             Median   (>80%)           
    bool strongMedianLinePull = (medianLineDeviation > 0.8);
    bool moderateMedianLinePull = (medianLineDeviation > 0.5 && medianLineDeviation <= 0.8);
    
    //                 Median Line
    double medianLineFrequency = 0.0;
    if(strongMedianLinePull) {
        //           Median                        
        medianLineFrequency = 55.0 + (medianLineDeviation * 30.0);  // 55-85% range
    } else if(moderateMedianLinePull) {
        //             Median                      
        medianLineFrequency = 35.0 + (medianLineDeviation * 30.0);  // 35-65% range
    }
    
    // ========================================
    //   AB=CD PATTERN VALIDATION
    // ========================================
    //        AB=CD: BC   61.8% retracement   AB  
    //              CD   127.2% extension   BC  
    bool isValidABCD = false;
    double abcdScore = 0.0;
    
    //   BC retracement (      0.618  
    double bcRetracementError = MathAbs(bcToAbRatio - 0.618);
    if(bcRetracementError < 0.15) {  //      
        isValidABCD = true;
        abcdScore = 1.0 - (bcRetracementError / 0.15);  // 0-1 score
    }
    
    //         Impulsive           
    bool isStrongImpulsive = (gannAngle > 75.0 && consolidationFactor < 0.1);
    bool isMediumImpulsive = (gannAngle >= 50.0 && gannAngle <= 75.0 && consolidationFactor < 0.1);
    bool hasDeepRetracement = (bcToAbRatio > 0.7);
    bool hasGoodTimeSymmetry = (timeSymmetry > 0.8);
    
    #ifdef ENABLE_DEBUG_LOGS
    Print("========================================");
    Print("==================== ADVANCED HARMONIC & PITCHFORK ANALYSIS:");
    Print("========================================");
    
    // Harmonic Pattern Detection
    if(harmonicPattern != "NONE") {
        Print("==================== HARMONIC PATTERN: ", harmonicPattern);
        Print("   AB/XA Ratio: ", DoubleToString(waves.AB_XA_Ratio, 3));
        Print("   BC/AB Ratio: ", DoubleToString(bcToAbRatio, 3));
        Print("   Confidence Level: ", DoubleToString(harmonicConfidence, 3));
        Print("   PRZ Frequency: ", DoubleToString(prz_Frequency, 1), "%");
        Print("   ==================== Using harmonic-based frequency selection");
    }
    
    // Median Line Analysis
    Print("==================== ANDREWS PITCHFORK (Median Line):");
    Print("   Median Price: ", DoubleToString(medianPrice, Digits));
    Print("   Distance from Median: ", DoubleToString(medianLineDeviation * 100, 1), "%");
    if(strongMedianLinePull) {
        Print("   ==================== STRONG PULL: Price far from median (>80%)");
        Print("   ==================== Expect strong reversal to median");
        Print("   ==================== Median Frequency: ", DoubleToString(medianLineFrequency, 1), "%");
    } else if(moderateMedianLinePull) {
        Print("   ==================== MODERATE PULL: Price moderately far (50-80%)");
        Print("   ==================== Median Frequency: ", DoubleToString(medianLineFrequency, 1), "%");
    } else {
        Print("   ==================== Near Median: Price close to equilibrium");
    }
    
    // AB=CD Validation
    Print("==================== AB=CD PATTERN VALIDATION:");
    Print("   BC Retracement: ", DoubleToString(bcToAbRatio, 3), " (Target: 0.618)");
    Print("   Error: ", DoubleToString(bcRetracementError, 3));
    if(isValidABCD) {
        Print("   ==================== VALID AB=CD: Score ", DoubleToString(abcdScore * 100, 1), "%");
        Print("   ==================== Using AB=CD frequency rules");
    } else {
        Print("   ==================== Not a classic AB=CD pattern");
    }
    
    Print("========================================");
    
    // Original Impulsive Pattern Detection
    if(isStrongImpulsive) {
        Print("==================== STRONG IMPULSIVE PATTERN DETECTED:");
        Print("   Gann Angle: ", DoubleToString(gannAngle, 2), "==================== (>75====================)");
        Print("   Consolidation: ", DoubleToString(consolidationFactor * 100, 1), "% (<10%)");
        Print("   BC/AB Ratio: ", DoubleToString(bcToAbRatio, 3));
        if(hasDeepRetracement) {
            Print("   Deep Retracement: YES - Expect strong continuation");
        }
        Print("   ==================== Adjusting scoring: Prefer higher frequencies (50-70% range)");
        Print("   ==================== Reducing penalties for low consistency and time symmetry");
    }
    else if(isMediumImpulsive) {
        Print("==================== MEDIUM IMPULSIVE PATTERN DETECTED:");
        Print("   Gann Angle: ", DoubleToString(gannAngle, 2), "==================== (50-75====================)");
        Print("   Consolidation: ", DoubleToString(consolidationFactor * 100, 1), "% (<10%)");
        Print("   BC/AB Ratio: ", DoubleToString(bcToAbRatio, 3));
        Print("   Time Symmetry: ", DoubleToString(timeSymmetry * 100, 1), "%");
        if(hasGoodTimeSymmetry) {
            Print("   Good Time Symmetry: Pattern is reliable");
        }
        Print("   ==================== Adjusting scoring: Prefer frequencies (35-50% range)");
        Print("   ==================== Reducing penalties for low consistency");
    }
    Print("========================================");
    #endif
    
    // ========================================
    //   3:                 
    // ========================================
    int targetSteps[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    int primarySteps[3] = {3, 5, 7}; //     
    
    //       Impulsive               2-3-4    
    if(isStrongImpulsive) {
        primarySteps[0] = 2;
        primarySteps[1] = 3;
        primarySteps[2] = 4;
    }
    //       Impulsive               2-3-5    
    else if(isMediumImpulsive) {
        primarySteps[0] = 2;
        primarySteps[1] = 3;
        primarySteps[2] = 5;
    }
    
    // ========================================
    //   4:         candidate
    // ========================================
    bool candidateFreqs[MAX_TH3_FREQ_INDEX + 1]; // Binary subdivision indices
    ArrayInitialize(candidateFreqs, false);
    
    //     1:           (100/N)
    for(int stepIdx = 0; stepIdx < 3; stepIdx++)
    {
        int targetStep = primarySteps[stepIdx];
        double idealFreq = 100.0 / targetStep;
        
        int closestIdx = FindNearestFreqIndex(idealFreq);
        
        // Mark        
        int startIdx = MathMax(MIN_TH3_FREQ_INDEX, closestIdx - 5);
        int endIdx = MathMin(MAX_TH3_FREQ_INDEX, closestIdx + 5);
        
        for(int i = startIdx; i <= endIdx; i++)
        {
            candidateFreqs[i] = true;
        }
    }
    
    //     2:           (suggested frequency)
    if(suggestedFreq > 0 && suggestedFreq <= 100.0)
    {
        int closestIdx = FindNearestFreqIndex(suggestedFreq);
        
        // Mark         suggested frequency
        int startIdx = MathMax(MIN_TH3_FREQ_INDEX, closestIdx - 3);
        int endIdx = MathMin(MAX_TH3_FREQ_INDEX, closestIdx + 3);
        
        for(int i = startIdx; i <= endIdx; i++)
        {
            candidateFreqs[i] = true;
        }
    }
    
    //     3:       Impulsive         50-70%          
    if(isStrongImpulsive) {
        int impStart = FindNearestFreqIndex(50.0);
        int impEnd = FindNearestFreqIndex(70.0);
        for(int i = impStart; i <= impEnd; i++)
        {
            candidateFreqs[i] = true;
        }
    }
    //     4:       Impulsive         35-50%          
    else if(isMediumImpulsive) {
        int medStart = FindNearestFreqIndex(35.0);
        int medEnd = FindNearestFreqIndex(50.0);
        for(int i = medStart; i <= medEnd; i++)
        {
            candidateFreqs[i] = true;
        }
    }
    
    // ========================================
    //   5:             
    // ========================================
    for(int freqIdx = MIN_TH3_FREQ_INDEX; freqIdx <= MAX_TH3_FREQ_INDEX; freqIdx++)
    {
        if(!candidateFreqs[freqIdx]) continue;
        
        double testFreq = GetFrequencyByIndex(freqIdx);
        
        for(int stepIdx = 0; stepIdx < 10; stepIdx++)
        {
            int testStep = targetSteps[stepIdx];
            double calcD, targetPrice;
            
            double errorPercent = CalculateFrequencyError(pA, pB, pC, testFreq, 
                                                          testStep, calcD, targetPrice);
            
            // ========================================
            //         (Multi-factor Scoring)
            //                
            // ========================================
            
            //            
            // Hardcoded weights (ML LearnedWeights removed)
            double w_step5Priority = 1.5;
            double w_step3_7Priority = 1.2;
            double w_step1Priority = 0.8;
            double w_errorWeight = 1.0;
            double w_speedConsistencyWeight = 1.0;
            double w_timeSymmetryWeight = 1.0;
            double w_fibonacciWeight = 1.0;
            double w_freqDeviationWeight = 0.5;
            double w_consolidationWeight = 0.8;
            double w_stepPriorityWeight = 1.0;
            
            // 1.       Step (          
            double stepPriority = 1.0;
            if(testStep == 5) {
                stepPriority = w_step5Priority;  //    
            } else if(testStep == 3 || testStep == 7) {
                stepPriority = w_step3_7Priority;  //    
            } else if(testStep == 1) {
                stepPriority = w_step1Priority;  //    
            }
            
            // 2.     (          
            double errorScore = errorPercent * w_errorWeight;
            
            // 3.     (          
            //   =     (1 - consistency)   20
            //       Impulsive            penalty    
            double speedConsistencyWeight = w_speedConsistencyWeight;
            if(isStrongImpulsive) {
                speedConsistencyWeight *= 0.3;  //   70% penalty
            }
            else if(isMediumImpulsive) {
                speedConsistencyWeight *= 0.5;  //   50% penalty
            }
            double speedScore = (1.0 - waves.speedConsistency) * 20.0 * speedConsistencyWeight;
            
            // 4.        (          
            //   =     (1 - symmetry)   100
            //       Impulsive       penalty    
            //                             
            double timeSymmetryWeight = w_timeSymmetryWeight;
            if(isStrongImpulsive && hasDeepRetracement) {
                timeSymmetryWeight *= 0.2;  //   80% penalty
            }
            else if(isMediumImpulsive && hasGoodTimeSymmetry) {
                timeSymmetryWeight *= 0.5;  //   50% penalty (       =       
            }
            double timeScore = (1.0 - timeSymmetry) * 100.0 * timeSymmetryWeight;
            
            // 5.       Fibonacci (          
            //   =  
            double fibScore = fibDeviation * 100.0 * w_fibonacciWeight;
            
            // 6.     suggested frequency (          
            double freqDeviation = 0.0;
            if(suggestedFreq > 0) {
                freqDeviation = MathAbs(testFreq - suggestedFreq) / suggestedFreq;
            }
            double freqScore = freqDeviation * 100.0 * w_freqDeviationWeight;
            
            // 7. Consolidation factor (          
            //   consolidation           (         
            //           penalty   
            double consolidationPenalty = 0.0;
            if(consolidationFactor > 0.3) {
                //           suggested   penalty  
                if(testFreq < suggestedFreq) {
                    double freqRatio = testFreq / suggestedFreq;
                    consolidationPenalty = (1.0 - freqRatio) * consolidationFactor * 100.0 * w_consolidationWeight;
                }
            }
            
            // 8.       Step Priority (          
            //                     
            double stepPriorityScore = stepPriority * w_stepPriorityWeight;
            
            // 9.                       Impulsive
            double impulsiveBonus = 0.0;
            if(isStrongImpulsive) {
                //             50-70%             (    =  
                if(testFreq >= 50.0 && testFreq <= 70.0) {
                    impulsiveBonus = -50.0;  //             =    
                }
                //              penalty  
                else if(testFreq < 30.0) {
                    impulsiveBonus = 100.0;  // penalty         
                }
            }
            else if(isMediumImpulsive) {
                //             35-50%            
                if(testFreq >= 35.0 && testFreq <= 50.0) {
                    impulsiveBonus = -30.0;  //            
                }
                //              penalty  
                else if(testFreq < 25.0) {
                    impulsiveBonus = 80.0;  // penalty         
                }
                //                           
                if(hasGoodTimeSymmetry && testFreq >= 40.0 && testFreq <= 45.0) {
                    impulsiveBonus -= 20.0;  //                   
                }
            }
            
            // ========================================
            // 10.   HARMONIC PATTERN BONUS (NEW)
            // ========================================
            double harmonicBonus = 0.0;
            if(harmonicPattern != "NONE" && prz_Frequency > 0) {
                //           PRZ            
                double przDeviation = MathAbs(testFreq - prz_Frequency) / prz_Frequency;
                if(przDeviation < 0.15) {  //   tolerance
                    harmonicBonus = -40.0 * (1.0 - przDeviation / 0.15);  // Max -40 bonus
                    
                    //                    
                    if(harmonicPattern == "CRAB") harmonicBonus *= 1.3;  // Crab =     
                    else if(harmonicPattern == "BUTTERFLY") harmonicBonus *= 1.2;
                    else if(harmonicPattern == "BAT") harmonicBonus *= 1.1;
                }
            }
            
            // ========================================
            // 11.   MEDIAN LINE BONUS (NEW)
            // ========================================
            double medianLineBonus = 0.0;
            if(medianLineFrequency > 0) {
                //           Median Line Frequency            
                double medianDeviation = MathAbs(testFreq - medianLineFrequency) / medianLineFrequency;
                if(medianDeviation < 0.20) {  //   tolerance
                    if(strongMedianLinePull) {
                        //           Median                
                        medianLineBonus = -35.0 * (1.0 - medianDeviation / 0.20);  // Max -35 bonus
                    } else if(moderateMedianLinePull) {
                        //             Median                
                        medianLineBonus = -20.0 * (1.0 - medianDeviation / 0.20);  // Max -20 bonus
                    }
                }
            }
            
            // ========================================
            // 12.   AB=CD VALIDATION BONUS (NEW)
            // ========================================
            double abcdBonus = 0.0;
            if(isValidABCD) {
                //     AB=CD                   score
                //             25-45%   (  AB=CD)
                if(testFreq >= 25.0 && testFreq <= 45.0) {
                    abcdBonus = -30.0 * abcdScore;  // Max -30 bonus
                    
                    //                 38.2%   (Fibonacci 0.382)
                    if(testFreq >= 36.0 && testFreq <= 40.0) {
                        abcdBonus -= 15.0;  // Extra -15 bonus
                    }
                }
            }
            
            // ========================================
            // 13.   ACCELERATION FACTOR (NEW - HIGH PRIORITY)
            // ========================================
            double accelerationScore = 0.0;
            
            //     =                      breakout    
            if(waves.AB_to_BC_Acceleration > 0.001) {
                //                
                double accelRatio = MathMin(waves.AB_to_BC_Acceleration / 0.01, 1.0);
                accelerationScore = -20.0 * accelRatio;  // Max -20 bonus
            }
            //       =                      breakout  
            else if(waves.AB_to_BC_Acceleration < -0.001) {
                double accelRatio = MathMin(MathAbs(waves.AB_to_BC_Acceleration) / 0.01, 1.0);
                accelerationScore = 20.0 * accelRatio;  // Max +20 penalty
            }
            
            // ========================================
            // 14.   RELATIVE STRENGTH FACTOR (NEW - HIGH PRIORITY)
            // ========================================
            double strengthScore = 0.0;
            
            //     BC
            if(waves.BC_RelativeStrength > 2.0) {
                // BC               D    
                strengthScore = -25.0;
            } else if(waves.BC_RelativeStrength < 1.0) {
                // BC           D  
                strengthScore = 25.0;
            }
            
            //       BC   AB (momentum change)
            double strengthRatio = waves.BC_RelativeStrength / MathMax(waves.AB_RelativeStrength, 0.1);
            if(strengthRatio > 1.2) {
                // BC       AB     momentum      
                strengthScore -= 15.0;
            } else if(strengthRatio < 0.8) {
                // BC     AB     momentum      
                strengthScore += 15.0;
            }
            
            // ========================================
            // 15.   CONFIDENCE SCORE SYSTEM (NEW - CRITICAL)
            // ========================================
            double confidence = 100.0;
            
            //   confidence          
            if(waves.speedConsistency < 0.5) confidence -= 30.0;  //     
            if(timeSymmetry < 0.6) confidence -= 20.0;  //      
            if(fibDeviation > 0.15) confidence -= 15.0;  //       Fibonacci
            if(errorPercent > 3.0) confidence -= 25.0;  //    
            
            //   confidence      
            if(harmonicPattern != "NONE") confidence += 15.0;  //          
            if(isValidABCD) confidence += 10.0;  // AB=CD  
            if(waves.BC_RelativeStrength > 2.0) confidence += 10.0;  //    
            if(MathAbs(waves.AB_to_BC_Acceleration) < 0.001) confidence += 5.0;  //    
            
            //          0-100
            if(confidence < 0) confidence = 0;
            if(confidence > 100) confidence = 100;
            
            // penalty   confidence   
            double confidencePenalty = 0.0;
            if(confidence < 50.0) {
                confidencePenalty = 50.0 * (1.0 - confidence / 50.0);  // Max +50 penalty
            }
            
            // ========================================
            // 16.   HARMONIC MEAN CONSISTENCY (SCIENTIFIC - PYTHAGOREAN)
            // ========================================
            //     Harmonic Mean        
            //                   
            double harmonicMeanScore = 0.0;
            
            if(waves.XA_Speed > 0 && waves.AB_Speed > 0 && waves.BC_Speed > 0) {
                //   Harmonic Mean
                double recipSum = (1.0/waves.XA_Speed) + (1.0/waves.AB_Speed) + (1.0/waves.BC_Speed);
                double harmonicMean = 3.0 / recipSum;
                
                //   Arithmetic Mean
                double arithmeticMean = (waves.XA_Speed + waves.AB_Speed + waves.BC_Speed) / 3.0;
                
                //     Harmonic   Arithmetic
                //       1.0                      
                double meanRatio = harmonicMean / arithmeticMean;
                
                //               (meanRatio > 0.9)
                if(meanRatio > 0.9) {
                    harmonicMeanScore = -15.0 * ((meanRatio - 0.9) / 0.1);  // Max -15 bonus
                }
                // penalty        (meanRatio < 0.7)
                else if(meanRatio < 0.7) {
                    harmonicMeanScore = 15.0 * ((0.7 - meanRatio) / 0.3);  // Max +15 penalty
                }
                
                #ifdef ENABLE_DEBUG_LOGS
                Print("   Harmonic Mean: ", DoubleToString(harmonicMean, 2), " pips/min");
                Print("   Arithmetic Mean: ", DoubleToString(arithmeticMean, 2), " pips/min");
                Print("   Ratio: ", DoubleToString(meanRatio, 3), 
                      " (", meanRatio > 0.9 ? "==================== Consistent" : (meanRatio < 0.7 ? "==================== Inconsistent" : "==================== Moderate"), ")");
                #endif
            }
            
            // ========================================
            // 17.   PHI RATIO BONUS (SCIENTIFIC - GOLDEN RATIO)
            // ========================================
            //           (   = 0.618)          
            //   Self-Fulfilling Prophecy (                    
            //       (300                
            double phiRatioScore = 0.0;
            
            double phi = 1.618033988749;
            double phiInverse = 0.618033988749;
            
            //   AB/XA       0.618
            double phiDeviation_AB_XA = MathAbs(waves.AB_XA_Ratio - phiInverse);
            if(phiDeviation_AB_XA < 0.05) {  //   tolerance
                //                    
                phiRatioScore -= 20.0 * (1.0 - phiDeviation_AB_XA / 0.05);  // Max -20 bonus
                
                #ifdef ENABLE_DEBUG_LOGS
                Print("   ==================== Golden Ratio detected in AB/XA: ", DoubleToString(waves.AB_XA_Ratio, 3));
                #endif
            }
            
            //   BC/AB       0.618
            double phiDeviation_BC_AB = MathAbs(waves.BC_AB_Ratio - phiInverse);
            if(phiDeviation_BC_AB < 0.05) {  //   tolerance
                phiRatioScore -= 15.0 * (1.0 - phiDeviation_BC_AB / 0.05);  // Max -15 bonus
                
                #ifdef ENABLE_DEBUG_LOGS
                Print("   ==================== Golden Ratio detected in BC/AB: ", DoubleToString(waves.BC_AB_Ratio, 3));
                #endif
            }
            
            //   AB/XA       1.618 (  )
            double phiDeviation_AB_XA_ext = MathAbs(waves.AB_XA_Ratio - phi);
            if(phiDeviation_AB_XA_ext < 0.08) {  //   tolerance (      extension)
                phiRatioScore -= 12.0 * (1.0 - phiDeviation_AB_XA_ext / 0.08);  // Max -12 bonus
                
                #ifdef ENABLE_DEBUG_LOGS
                Print("   ==================== Phi Extension detected in AB/XA: ", DoubleToString(waves.AB_XA_Ratio, 3));
                #endif
            }
            
            //     (  =  
            //           2        
            double totalScore = (errorScore + speedScore + timeScore + fibScore + freqScore + consolidationPenalty) 
                              * stepPriority * (1.0 + stepPriorityScore) 
                              + impulsiveBonus + harmonicBonus + medianLineBonus + abcdBonus
                              + accelerationScore + strengthScore + confidencePenalty
                              + harmonicMeanScore + phiRatioScore;  //     2        
            
            //      
            int size = ArraySize(results);
            ArrayResize(results, size + 1);
            
            results[size].frequency = testFreq;
            results[size].frequencyIndex = freqIdx;
            results[size].targetStep = testStep;
            results[size].errorPercent = errorPercent;
            results[size].calculatedD = calcD;
            results[size].targetPrice = targetPrice;
            results[size].errorPips = MathAbs(calcD - targetPrice) / pipSize;
            results[size].gannAngle = speedRatio;
            results[size].angleWeight = waves.speedConsistency;
            results[size].timeSymmetry = timeSymmetry;
            results[size].totalScore = totalScore;
        }
    }
    
    // ========================================
    //   6:          
    // ========================================
    int resultCount = ArraySize(results);
    for(int i = 0; i < resultCount - 1; i++)
    {
        int minIdx = i;
        for(int j = i + 1; j < resultCount; j++)
        {
            if(results[j].totalScore < results[minIdx].totalScore)
            {
                minIdx = j;
            }
        }
        
        if(minIdx != i)
        {
            FrequencySearchResult temp = results[i];
            results[i] = results[minIdx];
            results[minIdx] = temp;
        }
    }
    
    // ========================================
    //   7:         
    // ========================================
    int goodResults = 0;
    for(int i = 0; i < resultCount; i++)
    {
        if(results[i].errorPercent <= maxErrorPercent)
        {
            goodResults++;
        }
        else
        {
            break;
        }
    }
    
    if(goodResults > 0)
    {
        ArrayResize(results, goodResults);
        return goodResults;
    }
    else
    {
        //                threshold      
        //    10             
        int keepCount = MathMin(10, resultCount);
        ArrayResize(results, keepCount);
        
        #ifdef ENABLE_DEBUG_LOGS
        Print("==================== No results with error < ", maxErrorPercent, "%, keeping best ", keepCount, " results");
        #endif
        
        return keepCount;
    }
}

#endif // TH3_TOOL_A_MQH
