#!/usr/bin/env python3
"""R-PANELUI2 — declare a #resource for every panel bitmap the redesign uses.

MetaEditor only embeds a bitmap when a literal `#resource` names it, and
OBJPROP_BITMAP loads resolve against the embedded set. A bitmap that is
generated but never declared therefore fails SILENTLY at runtime: the object
is created, the load does nothing, and the card renders as bare labels.
That is exactly why the 13 redesigned cards still looked "old" on the chart.

This script appends the missing declarations (deduplicated against what the
file already declares) right after the last existing resource line. It is
idempotent: re-running it adds nothing.

Usage: python tools/add-panel-resources.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS = os.path.join(ROOT, "Files", "Icons")
TARGET = os.path.join(ROOT, "Biotak", "BiotakPanels.mqh")
ANCHOR = '#resource "\\\\Files\\\\Icons\\\\bk_ddw.bmp"'


def main():
    with open(TARGET, "r", encoding="utf-8", newline="") as fh:
        text = fh.read()

    # Already declared? Parse every existing #resource line.
    declared = set(re.findall(r'^#resource\s+"\\\\Files\\\\Icons\\\\([^"]+)"', text, re.M))

    # Every bitmap the panel engine can reference at runtime.
    names = sorted(n for n in os.listdir(ICONS)
                   if n.endswith(".bmp") and (n.startswith("gl_") or n.startswith("pnl_")))

    missing = [n for n in names if n not in declared]
    if not missing:
        print("nothing to do: all %d panel bitmaps already declared" % len(names))
        return 0

    # Group for readability: glyph inks, then the chrome skins.
    glyphs = [n for n in missing if n.startswith("gl_")]
    chrome = [n for n in missing if not n.startswith("gl_")]

    lines = [
        "",
        "//--- R-PANELUI2 (2026-09-11): every remaining panel bitmap. The redesign",
        "//--- draws its chrome from pre-rendered BMPs (MT4 cannot blur, gradient or",
        "//--- round a corner at runtime), so each one MUST be embedded here — an",
        "//--- undeclared bitmap fails silently and the row renders as bare labels.",
        "//--- P-UI-06: one runtime bitmap = one #resource. Generated by",
        "//--- tools/gen-th3-icons.js; list maintained by tools/add-panel-resources.py.",
    ]
    if glyphs:
        lines.append("//--- 57 glyph inks x (6 accents + muted) — preview const I{}")
        for n in glyphs:
            lines.append('#resource "\\\\Files\\\\Icons\\\\%s"' % n)
    if chrome:
        lines.append("//--- card skins, icon chips, switches, rails, washes and pills")
        for n in chrome:
            lines.append('#resource "\\\\Files\\\\Icons\\\\%s"' % n)

    block = "\n".join(lines) + "\n"

    idx = text.find(ANCHOR)
    if idx < 0:
        print("ERROR: anchor not found: %s" % ANCHOR, file=sys.stderr)
        return 1
    end = text.index("\n", idx) + 1

    with open(TARGET, "w", encoding="utf-8", newline="") as fh:
        fh.write(text[:end] + block + text[end:])

    print("declared %d new resources (%d glyph inks + %d chrome skins)"
          % (len(missing), len(glyphs), len(chrome)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
