/* extract-glyphs.js — one-shot: pull the 57-glyph `I` table out of
 * panel_all_redesign_preview.html and emit tools/glyphs.js so the icon
 * generator stops depending on a scratch preview file.
 *
 *   node tools/extract-glyphs.js
 *
 * Run once; tools/glyphs.js is committed and is then the source of truth.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'panel_all_redesign_preview.html');
const OUT = path.join(__dirname, 'glyphs.js');

const html = fs.readFileSync(SRC, 'utf8');

// const I = { ... };  — the object literal is plain JS, so slice it out and eval.
const start = html.indexOf('const I = {');
if (start < 0) throw new Error('const I = { not found in ' + SRC);
const end = html.indexOf('\n};', start);
if (end < 0) throw new Error('end of I object not found');
const literal = html.slice(start + 'const I = '.length, end + 2);

const I = eval('(' + literal + ')');
const names = Object.keys(I);
if (names.length !== 57) {
  console.warn('WARNING: expected 57 glyphs, found ' + names.length);
}

const body = names.map(n => {
  const v = I[n].replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return "  " + n + ": '" + v + "'";
}).join(',\n');

const out =
  '/* glyphs.js — AUTO-GENERATED by tools/extract-glyphs.js. Do not hand-edit.\n' +
  ' * Source: panel_all_redesign_preview.html (const I).\n' +
  ' * ' + names.length + ' stroke glyphs, designed on a 24x24 grid,\n' +
  ' * stroke-width 1.7, round caps/joins, fill=none unless a subpath says\n' +
  ' * fill="currentColor" stroke="none".\n' +
  ' */\n' +
  "'use strict';\n\n" +
  'module.exports = {\n' + body + '\n};\n';

fs.writeFileSync(OUT, out);
console.log('wrote ' + path.relative(ROOT, OUT) + ' — ' + names.length + ' glyphs');
console.log(names.join(' '));
